poc/README.md, poc/tenant-controller/data/manifests/rbac.yaml, poc/tenant-controller/pkg/controllers/tenants/controller.go
Refactor the code and add the functionality to:
- synchronize namespaces when Tenant object is updated, including namespace deletion/creation;
- synchronize RBAC inside namespaces when Tenant object is updated, for tenant admins;
- add OwnerReferences to be managed by garbage collector.
=> tenant-controller: add namespace/rbac sync on update of tenant

poc/tenant-controller/data/manifests/sample-nstemplate.yaml, poc/tenant-controller/data/manifests/sample-tenant.yaml, poc/tenant-controller/go.sum, poc/tenant-controller/pkg/controllers/tenants/controller.go, poc/tenant-controller/pkg/controllers/tenants/kubectl.go
A simple implementation for applying policy objects defined in NamespaceTemplate into tenant namespaces:
- The NamespaceTemplate must exist if it's referenced by the Tenant, otherwise creating Tenant will fail;
- NamespaceTemplate is only applied when Tenant is created or updated;
- Updates on NamespaceTemplate won't be applied to Tenant namespaces which are already created.
Behavior changes since last commit:
-  The tenant namespace name is constructed with tenant name as prefix, e.g. `tenant-a` puts `ns-1` in Tenant CR, the final namespace name will be `tenant-a-ns-1`.
=> apply namespace template into tenant namespaces

tenant/config/crds/tenancy_v1alpha1_tenant.yaml, tenant/config/rbac/rbac_role.yaml, tenant/pkg/apis/tenancy/v1alpha1/tenant_types.go, tenant/pkg/controller/tenant/tenant_controller.go, tenant/pkg/controller/tenant/tenant_controller_test.go
This change adds a TenantAdminNamespaceName field in Tenant CR. Tenant controller will create a namespace using the specified name (future change). 
Later, all tenant related policy objects and custom resources will use the TenantAdminNamespace. 
This change also removes the unused example code generated by Kubebuilder.
=> Add TenantAdminNamespaceName field and remove unused code

tenant/config/rbac/rbac_role.yaml, tenant/config/samples/tenancy_v1alpha1_tenant.yaml, tenant/pkg/controller/tenant/tenant_controller.go, tenant/pkg/controller/tenant/tenant_controller_test.go
This change implements creating TenantAdminNamespace upon tenant creation.
Controller adds tenant OwnerReference to TenantAdminNamespace. TenantAdminNamespace will be deleted when tenant CR is deleted. Reconcile fails if the TenantAdminNamespace has been created but owned by others. 
The reconcile logic for namespace deletion will be done in next change.
=> Reconcile for creating TenantAdminNamespace on Tenant creation

tenant/pkg/controller/tenant/tenant_controller.go, tenant/pkg/controller/tenant/tenant_controller_test.go
This change adds watcher for tenantAdminNamespace. As a result, if tenantAdminNamespace is deleted for some reason, the tenant controller will create a new one with the same name.
=> Add watcher for tenantAdminNamespace

tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml, tenant/config/rbac/rbac_role.yaml, tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
This change adds Name field in TenantNamespace CRD plus corresponding controller code for reconciling the tenant namespace CR. A few notes:
1) Controller will add OwnerReference to TenantNamespace CR for the newly created tenant namespace; 
2) Controller will add OwnerReference to TenantNamespace CR for existing namespace if the name matches instead of reporting error (not in this change);
3) One namespace can only be owned by one TenantNamespace CR. An admission Webhook will be added later to guarantee this;
4) Controller will not add prefix to the namespace name. It is up to user to resolve any naming conflict. 
5) TenantNamespace CR's namespace has be one tenant admin namespace. An admission Webhook will be added later to guarantee this;
=> Add Name field in TenantNamespace CRD

tenant/config/manager/all_in_one.yaml, tenant/config/manager/manager.yaml, tenant/config/rbac/rbac_role_binding.yaml, tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml, tenant/config/webhook/webhookmanifests.yaml, tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go, tenant/pkg/webhook/add_default_server.go, tenant/pkg/webhook/default_server/add_validating_tenantnamespace.go, tenant/pkg/webhook/default_server/server.go, tenant/pkg/webhook/default_server/tenantnamespace/validating/create_update_webhook.go, tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go, tenant/pkg/webhook/default_server/tenantnamespace/validating/webhooks.go
This change adds kubebuilder scaffold codes for TenantNamespace CRD webhook. i.e., codes generated by following cmd
kubebuilder alpha webhook --group tenancy --version v1alpha1 --kind TenantNamespace --type=validating --operations=create,update 
In addition, I change controller manager namespace to tenant-system and 
add an all_in_one.yaml for easy installation. 
The image name will be changed later once we have a formal docker hub account.
=> Add scaffolding code for TenantNameSpace CRD Webhook

tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml, tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
This change makes Name as an optional field in TenantNamespaceSpec.
Two unit tests are added and test code is refactored.
=> Support optional Name in TenantNamespaceSpec

tenant/pkg/apis/apis.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_event_handler.go
This change fix a problem of adding reconcile request for tenant namespace deletion event.
The problem is that default EnqueueRequestForOwner event handler alway uses watching object's namespace (which is empty since a namespace object does not have Namespace in this case) to find the owner object (i.e., tenantnamespace CR), which always fails since it never matches the tenantnamespace CR's namespace, i.e., tenantAdminNamespace.
To fix the problem, we have to implement customized event handler for watching namespace objects. We add a tenantAdminNamespace annotation for every tenant namespace so that the namespace event handler can find the correct tenantnamespace CR when creating reconcile request.
A few notes:
I have manually verified the change in minikube. A deleted tenant namespace …
=> Fix tenantnamespace controller event handler for namespace changes

incubator/hnc/controllers/hierarchy_controller.go, incubator/hnc/controllers/hierarchy_controller_test.go, incubator/hnc/controllers/object_controller.go, incubator/hnc/controllers/object_controller_test.go, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/forest/forest_test.go
Previously, if we hadn't actually seen a namespace on the apiserver, we
wouldn't create an entry for it in the forest. With this change, we
create an entry in the forest for any *referenced* namespace, even if it
doesn't exist, and mark that ns as existing or not existing as
appropriate. This allows us to catch state changes (ie, not existing to
existing) and therefore to update any other affected namespace.
More concretely, this allows namespaces to be created out of order, and
as a side effect elegantly solves reconciliation problems when the
controller is started (since the controller reconciles namespaces in an
arbitrary order). If a child is reconciled first, it may briefly be
given the "missing parent" condition, but when the parent is later
reconciled, it will notice that the child …
=> Lets namespaces be created/reconciled out-of-order

incubator/hnc/controllers/object_controller.go, incubator/hnc/controllers/object_controller_test.go
This handles conflicts in propagated objects. It will delete obsolete objects or set annotation to modified objects.
If there's any conflicts in the propagated objects, it will prevent further propagation.
=> Report any conflicts in propagated objects

incubator/hnc/cmd/manager/main.go, incubator/hnc/kind-deploy, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/controllers/suite_test.go, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
This is the first nontrivial validating webhook. It determines if a
change would cause an error condition due to the structure of the
hierarchy and, if so, returns the error.
Tested: manually plus new unit tests
=> Prevent cycles in validating webhook

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
This change fixes a problem such that if namespace has other annotations, the TenantAdminNamespaceAnnotation will not be added.
=> Fix a small bug

tenant/pkg/webhook/default_server/add_validating_tenant.go, tenant/pkg/webhook/default_server/tenant/validating/create_update_webhook.go, tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go, tenant/pkg/webhook/default_server/tenant/validating/webhooks.go
This change adds file generated by the following cmd:
kubebuilder alpha webhook --group tenancy --version v1alpha1 --kind Tenant --type=validating --operations=create,update
=> Add scaffolding code for Tenant CRD webhook

tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go
This change adds a few validation admission checks for TenantNamespace CR. 
OnCreation: TenantNamespace CR's namespace needs to be a tenantadminnamespace.
OnUpdate: TenantNamespace CR's `spec.name` cannot be changed.
=> Add validation admission checks for TenantNamespace - Part I

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go, tenant/pkg/util/tenant_utils.go, tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go
Let us fail the tenantnamespace CR creation if the to-be-created namespace name is invalid. 
Otherwise, the failure will happen in reconcile loop which is harder to be aware of.
=> Add namespace name validity check  for TenantNamespace CR

incubator/hnc/README.md, incubator/hnc/config/crd/kustomization.yaml, incubator/hnc/config/default/kustomization.yaml
Hey there delilah,
This PR is being done due to the difficulties I encountered when setting up the HNC project. I have added them to the README. 
There is one change, though, which is the renaming `patches` to `patchesStrategicMerge` on the config yml files due to this issue https://github.com/kubernetes-sigs/kustomize/issues/1429
=> Rename 'patches' to 'patchesStrategicMerge' and update README with missing dependencies install intructions

incubator/hnc/config/crd/kustomization.yaml, incubator/hnc/config/default/kustomization.yaml
`make deploy` failed because `kustomize build config/default` failed due to typos introduced in the previous CLs 
Test: run `kustomize build config/default` and see it succeed
/assign @adrianludwin
=> HNC: Fix for typo in kustomization yaml file

incubator/hnc/hack/ci-test.sh
Hey there delilah,
Here we set GOPATH/bin in PATH env var (because is not included or existing by default in Prow) in the `incubator/hnc/hack/ci-test.sh`. This is part of an ongoing discussion present on the issue https://github.com/kubernetes/test-infra/issues/9469.
=> Add GOPATH/bin to PATH env var in ci-test.sh

incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go, incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/forest/forest_test.go
Add a `<namespace>.tree.hnc.x-k8s.io/depth` label to all namespaces with
nontrivial hierarchies (i.e. one or more children or any parent).
Resolve: #92
=> Add the `tree` label to all namespaces with explicit hierarchies

incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/vn-agent/server/route.go, incubator/virtualcluster/pkg/vn-agent/server/server_test.go, incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh
vn-agent support exec, attach, portForward proxy.
First, we generate the testing certification chain. Each certification is signed by a root CA.
Second, vn-agent will require the client providing the tenant cert, make the connection goes on HTTPS.
streaming server is inside the fakeKubelet, kubelet communicate with local streaming server through http.
=> [incubator][vc] vn-agent support streaming api

incubator/hnc/pkg/kubectl/root.go
**What this PR does / why we need it**:
This PR fixes error in following command :
` kubectl hnc set-parent team-a acme-org `
where acme-org and team-a are two namespaces
**Which issue(s) this PR fixes**:
Fixes #
```
Error setting the parent of team-a to acme-org: the server could not find the requested resource (post hierarchies.hnc.x-k8s.io hierarchy)
```
Ref #144
=> kubectl hnc set-parent command fix

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/kubectl/root.go
**What this PR does / why we need it**:
This PR added a constant for resource to replace hardcoded value of resource `hierarchyconfigurations`
**Which issue(s) this PR fixes**:
Fixes #146
=> HNC: hardcoded value for resource is replaced by constant

incubator/virtualcluster/.gitignore, incubator/virtualcluster/Makefile, incubator/virtualcluster/hack/lib/build.sh, incubator/virtualcluster/hack/lib/docker-image.sh, incubator/virtualcluster/hack/lib/init.sh, incubator/virtualcluster/hack/lib/util.sh, incubator/virtualcluster/hack/make-rules/build.sh, incubator/virtualcluster/hack/make-rules/release-images.sh
1. build binaries
```bash
➜  virtualcluster git:(make-image) ✗ make all WHAT=cmd/vn-agent
hack/make-rules/build.sh cmd/vn-agent
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/vn-agent
➜  virtualcluster git:(make-image) ✗ make all
hack/make-rules/build.sh
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/manager
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/syncer
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/vn-agent
```
2. build images
```bash
➜  virtualcluster git:(make-image) ✗ make release-images
hack/make-rules/release-images.sh
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/manager
Building github.com/multi-tenancy/incubator/virtualcluster/cmd/syncer
Building …
```
=> [incubator][vc] add script to build docker image for each component

incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
This implements the logic described in the design doc to prevent a
subadmin from depriving a superadmin of access to a namespace by
assigning it away, and from gaining access to a new namespace's
propagated objects by joining it as a child.
Tested: new unit tests. Also manually verified that by default, acting
as a service account did not allow me to change the hierarchy of a
subnamespace even if I had get/update permissions on its
hierarchyconfig. Verified that as I added rolebindings to the parents,
the error messages changed accordingly as the reasons for failures
changed until I had sufficient permissions, at which point it passed. I
have not tested this exhaustively, apart from the unit tests.
=> Check authz when changing a namespace's parent

incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/controllers/setup.go
A recent refactoring started panicking on Kind because Kind has PSPs by
default, which it turns out aren't namespaced (oops). This change adds
some logspam in case this ever happens again and removes PSPs from the
HNC.
Tested: verified logspam before removing PSPs (and that it didn't
crash), then removed PSPs from setup.go and verified the logspam went
away.
/assign @srampal
=> PSPs aren't namespaced and shouldn't be watched by the HNC

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/suite_test.go, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/kubectl/root.go, incubator/hnc/pkg/kubectl/tree.go
We used to import the HNC API as `tenancy` because the APIs were
initially in the `tenancy.k8s.io` group (or something like that). Now,
however, they're in `hnc.x-k8s.io` and calling that API "tenancy"
doesn't really make sense anymore. Importing it as `api` is unambiguous
in the context of the HNC (all other imported APIs are named) and is
also shorter to type and easier to read.
/cc @yiqigao217 
/cc @lafh 
=> Change API package import to 'api'

incubator/hnc/pkg/validators/hierarchy.go
I'd left this out because I was too lazy to do the type conversion in
the initial checkin and it didn't seem to be needed, but GKE uses it for
supplemental authn information when authorizing via IAM instead of RBAC.
Tested: validation fails without this change on GKE, passes with it.
=> Include UserInfo.Extra in authz check

incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/kubectl/show.go, incubator/hnc/pkg/kubectl/tree.go
Changes:
- Better human-readable message for critical conditions in an ancestor.
- In `kubectl-hnc show`, pretty-prints all information from the
conditions, including the code and affected namespaces.
- In `kubectl-hnc tree`, the condition codes are now shown.
- Verbose log messages removed.
Tested: manually caused some conditions and verified that they were
reported correctly.
=> Improvements to generation and display of conditions

incubator/hnc/pkg/kubectl/root.go, incubator/hnc/pkg/kubectl/set.go, incubator/hnc/pkg/kubectl/show.go, incubator/hnc/pkg/kubectl/tree.go
Other changes:
- Fixed initialization segfault when the init() functions stopped
being called in the order I wanted (oops).
- Only all `getHierarchy` and `updateHierarchy` once during `set` with
better messages explaining what's going on.
Tested: manually confirmed that illegal names or valid, existing
required children were removed. Also retried --parent, --root and
--requiredChild in various combinations and everythign seems to work as
expected. Filed
https://github.com/kubernetes-sigs/multi-tenancy/issues/173 to add
better unit testing in the future.
/cc @vjdhama 
=> Add --optionalChild flag and assorted changes to kubectl-hnc-set

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go, incubator/hnc/pkg/controllers/object_controller.go
The constants all are part of the API so there's no point for them to be in the `controller` package.
Tested by running `make test`
/assign @adrianludwin
=> Code refactoring: move constants declared in `controller` to be in `api`

incubator/hnc/cmd/manager/main.go, incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/config/manager/manager.yaml, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/controllers/suite_test.go
Tested: manual testing on GKE. I also instrumented the logs (removed in
this commit) to report the maximum actual concurrency when I started 100
threads; it peaked at about 15. However, the "startup time" (the time
from when the controller starts to when it stops making changes) didn't
change on my test cases and remained constant at about 30s. However,
think it's a good idea to turn this on now to flush out any problems.
Fixes #102
=> Enable multithreading in the HC controller

incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
What this PR does / why we need it:
This PR fix validation on webhook to reject illegal character on namespace when execute kubectl with `--requiredChild` parameter.
Which issue(s) this PR fixes:
#172
=> Validator reject illegal namespace names

incubator/hnc/pkg/kubectl/root.go, incubator/hnc/pkg/kubectl/set.go, incubator/hnc/pkg/kubectl/show.go, incubator/hnc/pkg/kubectl/tree.go
Changes:
Create Client interface in kubectl package and some code refactoring. This change is done to make the kubectl package functions testable in future.
Tested:  manually run kubectl tree, show and set commands and verified that they were
reported correctly.
=> HNC: Added Client Interface to support test cases for kubectl commands

incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go
What this PR does / why we need it:
This PR fix label on namespace by removing all existing hnc.x-k8s.io labels (and annotations) when the hierarchy changes.
Which issue(s) this PR fixes:
#185
=> remove label when hierarchy changes

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/config/gvk.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/object.go, incubator/hnc/pkg/validators/object_test.go
`hnc.x-k8s.io/inheritedFrom` is used by the controller to determine which
objects to manage, so we decide to add a webhook to prevent users from
applying it directly.
Minor Code refactoring: move customized GVKs to `pkg/config` as the usage is not
limited to `controller` only.
/resolve #104
=> Prevent users from applying the inheritedFrom label

incubator/hnc/pkg/kubectl/set.go
Changes:
Separate out set command runnable function and introduce dependency function to make function testable.
Tested: manually run kubectl set commands and verified that they were
reported correctly.
=> HNC: Code refactoring to make set command function testable

incubator/virtualcluster/Dockerfile, incubator/virtualcluster/PROJECT, incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/cmd/vcctl/subcmd/delete.go, incubator/virtualcluster/cmd/vcctl/vcctl.go, incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/apis/addtoscheme_tenancy_v1alpha1.go, incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/doc.go, incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/register.go, incubator/virtualcluster/pkg/controller/add_clusterversion.go, incubator/virtualcluster/pkg/controller/add_virtualcluster.go, incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go, incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller_suite_test.go, incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller_test.go, incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go, incubator/virtualcluster/pkg/controller/pki/pki.go, incubator/virtualcluster/pkg/controller/secret/secret.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_suite_test.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go
replace the old import path (github.com/multi-tenancy -> github.com/kubernetes-sgis/multi-tenancy)
`make all` will fail, since import paths in the vn-agent and the syncer have not been replaced yet. To build `manager`, use the following commands.
```bash
make build WHAT=cmd/manager
make vcctl-osx
```
=> replace the old import path

incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/pkg/validators/object.go
Tested: applying the webhook fails without this change and passes with
it. Also manually tried an illegal change and verified that the response
came from a webhook that was clearly identified as HNC
("secrets.objects.hnc.x-k8s.io").
/assign @lafh
=> Fix object webhook configuration

incubator/virtualcluster/README.md, incubator/virtualcluster/cmd/syncer/app/config/config.go, incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/vn-agent/main.go, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/go.mod, incubator/virtualcluster/go.sum, incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion.go, incubator/virtualcluster/pkg/controller/pki/pki.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go, incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go, incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go, incubator/virtualcluster/pkg/syncer/controllers/node/controller.go, incubator/virtualcluster/pkg/syncer/controllers/node/node.go, incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/controllers/register.go, incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go, incubator/virtualcluster/pkg/syncer/syncer.go
vc-manager
1. fill the CommonName in tenant apiserver with vc.Name
2. fix the service name of the tenant apiserver
syncer
1. make the super master config optional. using in-cluster kubeconfig by default
2. backPopulate pod status to tenant master
3. register virtual node in tenant master
4. periodically update the heartbeats of each nodes
vn-agent
1. make the client ca config optional. don't verify the cert if client-ca is empty.
=> [incubator][VC] register virtual node in tenant master

incubator/virtualcluster/cmd/vn-agent/app/options/options.go, incubator/virtualcluster/cmd/vn-agent/app/server.go, incubator/virtualcluster/cmd/vn-agent/main.go, incubator/virtualcluster/pkg/vn-agent/certificate/cert.go, incubator/virtualcluster/pkg/vn-agent/config/config.go
refactor vn-agent command to k8s style.
`k8s.io/component-base/cli/globalflag` this package will auto register the klog options
=> [incubator][VC] vn-agent: support full klog options

incubator/hnc/pkg/controllers/object_controller.go
Changes-
isExcluded() function handles the case of object with non-empty finalizer field
Tested-
observed and verified that object with non empty finalizer is not propagated.
Fixes #106
=> Logic added to not propagate objects with nonempty finalizer list

incubator/hnc/api/v1alpha1/hierarchy_types.go
After this change, we can close #76 .
The object conditions will be re-discussed in v0.2.
=> Remove object conditions in v0.1

incubator/hnc/pkg/kubectl/tree.go
I had used the regular pipe character ("|", U+007C) but this wasn't
lining up correctly. The correct character appears to be "Box Drawings
Light Vertical" ("│", U+2502).
Tested: ran `tree` and confirmed it was more visually appealing.
=> Fix unicode character in kubectl-hnc tree

incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
A prior commit (0f10f39) updated the allowed codes and their
documentation but not the generated files. This commit simply includes
the modified files generated by the make process.
=> Update generated CRD manifest file

incubator/hnc/.gitignore, incubator/hnc/Makefile, incubator/hnc/README.md
Now users can try out HNC by saying `kubectl apply -f <some single
file>`.
=> Enable one-line installation and smooth onboarding experience

incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/object/object.go, incubator/hnc/pkg/validators/object.go, incubator/hnc/pkg/validators/object_test.go
Manual test:
org1
|
- team1
(1) Create a secret in org1. Modification to the origin secret is
allowed, but modification to the secret in team1 is not allowed.
(2) Create ResourceQuota in org1. Create a pod in org1 and see
ResourceQuota has been partially used, but the propagated ResourceQuota
for team1 is not affected.
P.S. #238 will be resolved in another PR. This PR will focus on the refactoring the canonical function.
/resolve #89
=> HNC: forbid propagated objects from being modified

tenant/config/crds/tenancy_v1alpha1_tenant.yaml, tenant/config/manager/all_in_one.yaml, tenant/config/rbac/rbac_role.yaml, tenant/pkg/controller/tenant/tenant_controller.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
This change mainly does the following:
1) Allow tenant admin to fully manage tenantnamespace CR in tenantAdminNamespace by setting role and rolebinding
2) Update tenant clusterrole to allow tenant admin to access the namespace created by tenantnamespace controller.
=> Add RBAC to allow tenant admin to create tenantnamespace CR and get the created namespace.

incubator/hnc/pkg/object/object.go, incubator/hnc/pkg/object/object_test.go
Currently the tree label will stay in the canocial version of the object
/resolve #238
=> fix Canonical function

tenant/config/crds/tenancy_v1alpha1_tenantnamespace.yaml, tenant/pkg/apis/tenancy/v1alpha1/tenantnamespace_types.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
This change simply adds a field to indicate the name of the created namespace, which is the result of considering multiple factors.
=> Add OwnedNamespace field in TenantNamespace CRD status

incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/syncer/controller/controller.go, incubator/virtualcluster/pkg/syncer/controllers/node/controller.go, incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/controllers/register.go, incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go, incubator/virtualcluster/pkg/syncer/controllers/service/controller.go, incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/utils/client.go
notes: CA in tenant scope must be same with super master, because tokens controller always reset the CA field to super master ca.
fixes: #248
=> [incubator][VC] support service account for tenant

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go, incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go, incubator/virtualcluster/pkg/syncer/controllers/node/controller.go, incubator/virtualcluster/pkg/syncer/controllers/node/uws.go, incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go, incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go, incubator/virtualcluster/pkg/syncer/controllers/service/controller.go, incubator/virtualcluster/pkg/syncer/controllers/service/uws.go, incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/syncer/syncer.go
distinguish StartUWS and StartDWS method in controller interface
fixes #251 
notes for reviewer:
1. refactor controller interface
```go
type Controller interface {
listener.ClusterChangeListener
StartUWS(stopCh <-chan struct{}) error
StartDWS(stopCh <-chan struct{}) error
}
```
Actually, every controller should implement this interface. And we register the listener when adding the controller to controller manager.
**How about start UWS and DWS in a method named `Start(stopCh <-chan struct{}) error`.**
Both looks good for me. Distinguish these two method will more clear to control the concurrent problem.
2. the workqueue code for each controller is mostly the same.
Yes, the work queue part is mostly the same. But we may have different …
=> [incubator][VC] add work queue for upward syncer

incubator/hnc/Makefile, incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/controllers/suite_test.go
This is setting flags to enable/disable the new object controller. Part of #195 
Tested manually by disabling the object propagation in the new object
controller and see if the propagation is enabled/disabled by
unsetting/setting the flag "--enable-new-object-controller" in
manager_auth_proxy_patch.yaml.
The test flag is tested by "make test NOC=1"
=> Set flags to enable new object controller

incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/pkg/controller/pki/pki.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go, incubator/virtualcluster/pkg/syncer/syncer.go
cluster should be identify by `<namespace>-<name>`, creating tenant component in their own namespace.
before
```bash
[root@vm vc]# kubectl get pod -A
NAMESPACE                          NAME                               READY   STATUS    RESTARTS   AGE
default                            test-deploy-6bdc6484-8czwk         1/1     Running   103        4d3h
kube-system                        coredns-6dcc67dcbc-4644w           1/1     Running   9          12d
kube-system                        coredns-6dcc67dcbc-rwk42           1/1     Running   9          12d
kube-system                        etcd-minikube                      1/1     Running   9          12d
kube-system                        kube-addon-manager-minikube        1/1     Running …
```
=> [incubator][VC] create tenant master under clusername namespace

incubator/hnc/Makefile, incubator/hnc/config/certmanager/certificate.yaml, incubator/hnc/config/certmanager/kustomizeconfig.yaml, incubator/hnc/config/crd/patches/cainjection_in_hierarchies.yaml, incubator/hnc/config/default/webhookcainjection_patch.yaml
Applied several changes in the wake of #276:
* Followed instructions in
https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/,
most importantly to change *all* the group API versions.
* Added hnc-webhook-service.hnc-system.svc as well as
hnc-webhook-service.hnc-system.svc.cluster.local as the allowed DNS
names for the HNC certificate - otherwise, connections from the
apiserver were rejected with a (surprisingly helpful) TLS connection
error message.
Tested: before this change, HNC was never coming up correctly (GKE
1.15). After this change, it comes up and I can create subnamespaces.
/cc @smileisak
=> Fix HNC to work with cert-manager v0.11.0

incubator/hnc/config/rbac/role.yaml, incubator/hnc/pkg/controllers/object_controller.go
I noticed that HNC wasn't able to copy a rolebinding to cluster-admin
since it was missing at least two verb (delete-collection and
impersonate). I added both of those as well as "use" (which, AFAIK, is
only used for PSP which aren't namespaced but it seemed like a safe
addition) and verified that HNC was now able to copy the rolebindings.
Since cluster-admin is the most powerful role in K8s (again, AFAIK), I
think this means that HNC can now copy any rolebinding.
=> Give the HNC service account all required verbs

incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/forest/forest.go
Fixes #189 , #195 ,  #278 
https://bit.ly/2sCRWgA is the design doc for the new object controller.
This commit implements the new object controller and SyncNamespace, with
changes to the forest, based on the doc. It includes:
Introduce a channel of event.GenericEvent to each object reconciler to
enqueue objects to reconcile. Make object reconcilers watch the event
channels in addition to the objects. Change SyncNamespace function to
enqueue affected objects.
Change the way the original objects get propagated to reduce unnecessary
propagation. Store original objects in the in-memory forest to help and
serve as source of truth for object propagation.
Update and add new object controller tests with flags to make sure they
work for both, the current and the new, object controllers, since some …
=> Initial version of new object controller

incubator/hnc/pkg/controllers/object_controller_test.go
Fixed the flaky test mentioned in #282 
The flaky test was caused by the design of the test. We need to make
sure the objects get propagated before checking if it's modified from
the source object.
Tested with "make test NOC=1" and it's not flaky any more.
=> Fix flaky object controller test

incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/conversion/equality_test.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go
check whether the metadata and the podSpec update
```
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="should.*update.*annotations.*on.*modification"
```
```
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="should.*update.*labels.*on.*modification"
```
test pass
=> [incubator][VC] feature: observe pod value update event

incubator/virtualcluster/pkg/syncer/controllers/node/node.go
fix test:
```bash
[Fail] [sig-cli] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2056
```
=> [incubator][VC] fix: assign node capacity to virtual node

incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/forest/forest.go
This is part of #282 and #195
This commit stops the object controller for further action if any
critical condition is found in the namespace. The object controller will
propagate/delete objects after the critical conditions are gone.
Tested with "make test NOC=1" with additional tests. It passed both
"make test" and "make test NOC=1". When commenting out the "create
missing parent" code in the test and some of the following expectations,
the test failed at expectations that we expect it to fail.
=> Check Crit condition in object controller

incubator/hnc/Makefile, incubator/hnc/README.md, incubator/hnc/hack/krew-hierarchical-namespaces.yaml, incubator/hnc/pkg/kubectl/root.go
See http://bit.ly/hnc-cli-naming for details on the rename. I also fixed
various Krew issues, most importantly that the source file
(hack/krew-hierarchical-namespaces.yaml) was being modified by the build
process.
Tested: manually verified that `kubectl hierarchical-namespaces tree`
and `kubectl hns tree` both work as expected after this change. Ran both
krew-install and krew-uninstall.
Addresses #302 but doesn't change the subcommands.
/assign @srampal 
=> Change name of kubectl plugin and fix krew.

incubator/hnc/Makefile, incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/pkg/controllers/suite_test.go
Part of #195 
Set v0.2 object controller as default in both controller manager and
tests.
Tested with "make test" by commenting out the if/else statement in the
object controller test for different behaviours of new/old object
controller handling a modified propagated object and leaving only the
expected behaviour of the new object controller. The "make test" passed
and "make test NOC=0" failed.
Then manually removed "-enable-new-object-controller=${NOC}" in go test
in Makefile and run "make test" again. It passed/failed with the default
value of newObjectController set to true/false in suite_test.go.
Finally tested manually to make sure the controller manager is using the
new object controller. The results were as expected.
=> Set v0.2 object controller as default

incubator/hnc/pkg/kubectl/create.go, incubator/hnc/pkg/kubectl/describe.go, incubator/hnc/pkg/kubectl/root.go, incubator/hnc/pkg/kubectl/set.go
See http://bit.ly/hnc-cli-naming for details. The two major changes here are
to rename `show` to `describe`, and to add a `create` subcommand as a
synonym for `set --requiredChild`.
In addition, this change allows both `set --requiredChild` and `set
--optionalChild` to take multiple values, either comma-delimited or with
repeated flags. It also slightly improves error messages.
Tested:
* Tried both --requiredChild and --optionalChild with a combination of
comma-delimited and repeated flags.
* Manually tried the `create` command.
* Manually tried the `describe` command.
Fixes #302
=> Improve kubectl subcommands to match naming doc

incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
1. change the clusterrolebinding's name of the vc-manager's service account to avoid the privilege problem on ACK.
2. increase the polling timeout to 180 seconds (i.e. pulling image from docker on ack may take longer).
=> change the vc setting for ACK 

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
See https://github.com/kubernetes-sigs/multi-tenancy/issues/235.
Enums are not backwards-compatible, but enum-like strings are just fine.
Since these are only generated by the controller, validation during
input isn't a concern anyway.
Also restructures some global vars and consts and improves
documentation.
Testing: builds and passes unit tests
Fixes: #235
=> Turn Condition.code into a string, not an enum

incubator/hnc/Makefile
Tested: HNC can install again on old versions of GKE.
=> Fix cert-manager for older versions of K8s

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go, incubator/hnc/pkg/forest/forest.go
This change downgrades RequiredChildConflict to be a non-critical
condition. It also only annotates it on the namespace *requesting* the
required child, not the child itself, so that one tenant cannot cause
another tenant's namespace to be marked as having a condition (critical
or otherwise).
Testing: manual with the validating webhook disabled. Found one bug and
added the unit test.
Fixed #307 
=> Improve RequiredChildConflict condition

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/setup.go
This commit created a reconcile counter to count total hier and object
reconciles and current ongoing object reconciles. It generates logs with
these numbers so we can get better idea of the controller performance,
for example, how long it takes to propagate objects. It would be when
the current ongoing number of object reconciles becomes zero.
Manually tested on GKE cluster and looking through the logs.
=> Create reconcile counters and a flag to enable it

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/forest/forest.go
Also prevent HC controller from invoking object controllers; since
object controllers can now invoke the HC controller, this was causing an
infinite loop.
Tested: manually create a namespace both with an uncopyable rolebinding
to cause a problem during the "write" stage and a secret with a
finalizer to cause a problem during the "sync" stage. Observed that all
expected conditions were applied to all namespaces, albeit with some
funny transient states that I should dig into. I also added a unit test
for objects with finalizers, but I can't stub out the "write" function
yet. This will come in a later PR.
Fixes #201
=> Add conditions for object problems

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/controllers/event/controller.go, incubator/virtualcluster/pkg/syncer/controllers/event/uws.go, incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go, incubator/virtualcluster/pkg/syncer/controllers/register.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
related #250 
lookup virtual ns from super ns when back pop pod
fix test
```
[Fail] [k8s.io] [sig-node] Events [It] should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/events.go:96
```
=> [incubator][VC] back populate pod related event to tenant

incubator/hnc/Makefile, incubator/hnc/README.md, incubator/hnc/cloudbuild.yaml, incubator/hnc/hack/ci-test.sh
This change updates `make release` so that as little as possible happens
on the host computer. All artifacts - the manifests, kubectl plugin and
of course the image itself - are now built on Cloud Build.
The image does still have to make a round-trip onto the builder's
workstation since the Cloud Build service account doesn't have
permission to push directly to the K8s staging GCR, but you can still
verify that the image built on Cloud Build is the same one on the
official GCR.
Tested: followed these instructions to create a new build and deployed
it.
=> Use Cloud Build for everything and update docs

incubator/virtualcluster/cmd/syncer/app/config/config.go, incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go, incubator/virtualcluster/pkg/syncer/metrics/metrics.go, incubator/virtualcluster/pkg/syncer/syncer.go
1. export metric endpoint to http server
2. add metric for pod operation counts, durations and errors
fixes #329 
```bash
curl 172.17.0.8/metrics
syncer_pod_operations_duration_seconds_count{operation_type="pod_delete"} 1
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.005"} 10
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.01"} 10
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.025"} 11
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.05"} 11
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.1"} 11
syncer_pod_operations_duration_seconds_bucket{operation_type="pod_update",le="0.25"} 11 …
```
=> [incubator][VC] setup prometheus metrics framework

incubator/virtualcluster/README.md, incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/cmd/vcctl/vcctl.go, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml, incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_loadbalancer.yaml, incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml, incubator/virtualcluster/config/setup/all_in_one_ack.yaml, incubator/virtualcluster/pkg/controller/util/net/util.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, tenant/config/manager/all_in_one_ack.yaml
1. allow Virtualcluster to be exposed through loadbalancer.
2. when vc is exposed by loadbalancer, the vcctl will replace vc url
in kubeconfig by external ip of the loadbalancer.
3. add ack specified yaml files that pulling container images from docker registry
hosts alibaba cloud. (ack users may have issues with downloading image
from docker hub).
=> Add ACK mode for VC

incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go, incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
This change mainly does the followings:
1) Move downward syncer logic to a separate dws.go for better code structure.
2) Move WaitForCacheSync to the right sync thread.
3) Add more comments.
This change touches configmap/events/namespace/event resources. There are no functional change.
=> [Incubator][VC] Clean up - Refactor resource controller - Part 1

incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go, incubator/virtualcluster/pkg/controller/controller.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
1. abstract Create/Delete Virtualcluster functions, and encapsulate
them into a new interface `MasterProvisioner`
2. adapt existing minikube implementation to `MasterProvisioner` interface
3. add template of `MasterProvisionerAliyun`
=> Allow user to choose different underlying platforms to provision tenant master

incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller_test.go, incubator/virtualcluster/pkg/syncer/resources/secret/controller.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
This change touches secret/serviceaccount resources. It mainly does the followings:
- Move downward syncer logic to a separate dws.go for better code structure.
- Add an serviceaccount informer Lister and add WaitForCacheSync for service account dws thread. This will avoid create duplicated resource without querying super master .
- Add more comments.
=> [Incubator][VC]Clean up - Refactor resource controller - Part 3

incubator/virtualcluster/pkg/controller/util/strings/util.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
1. fix creation timeout bug.    
After ASK creation is timeout, the reconciler will proceed based on ASK state,
* if in 'initial' state, reconciler will poll the ASK until it is turned in to 'running' state.
* if in 'running' state, reconciler will proceed post creation actions,
i.e. retrieving admin-kubeconfig, creating corresponding namespace.
2. handle Alibaba Cloud SDK error by checking the error code
=> fix creation timeout bug.

incubator/hnc/config/manager/manager.yaml
We noticed the HNC controller OOMing on 30Mi of memory, even on
relatively small hierarchies. Raising the request to 50Mi (from 20Mi)
and the limit to 100Mi (from 30Mi) should give us enough headroom in
most cases.
Tested: redeployed and observed that the requests/limits were as
expected.
=> Increase memory limits

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/syncer.go
We have a slight race window in syncer.go. Before calling runCluster() to start the cluster cache, the cluster has been available in all MCControllers. Therefore, when any uws thread tries to query tenant master, the tenant cache may be stale. 
In this change, a synced flag is added and if the flag is false, the MultiClusterController.GetCluster() method returns nil and the reconcile request will be requeued.
Also, the tenant cluster cache start is done in syncer.go. The duplicated logic in MultiClusterController.Start() can be removed.
=> [Incubator][VC]Fix cluster cache not ready race

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
We don't allow to use tenant PV for virtual cluster. Hence the PV capability is provided by super master only.  This change adds uws sync controller to back populate StorageClass objects from super master to every tenant master. Super master holds the source of truth for storage class.
All the races, and inconsistency will be handled by PeriodCheck thread which will be done later.  
Test:
Manually verify that the add and delete sc operation in super master is correctly populate to tenant master.
=> [incubator][VC]Add sync controller for StorageClass resource

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
This change uses DelegatingCache for tenant cluster read for watched objects. The synced check logic is moved out of GetCluster method since it is hard to distinguish between cluster is deleted and cluster cache is not synced. 
This change also avoids creating many new clientset client for accessing tenant apiserver.
After this change, we should use func (c *MultiClusterController) Get() method to read watched tenant apiserver object.
I will try to remove GetCache method from ClusterInterface in next change.
=> User DelegatingCache for tenant apiserver read and save clientset client pointer

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/node/util.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
This change attempts to achieve the following best practices for building syncer framework objects.
- Expose least amount of internal state
- Avoid exposing internal pointers 
As a consequence, with this change,
- Cluster and ClusterInterface does not export GetCache() method anymore. MultiClusterController adds List method to encapsulate the access to internal cluster cache.
- Cluster does not export GetMapper and GetScheme.
- MultiClusterController does not expose GetCluster method anymore. All needs to access cluster pointer are supported by specific public methods such as GetClusterClient and GetClusterDomain.
- Many related codes are changed due to above interface changes.
Bonus fixes:
- Avoid looping the entire cluster map when calling getCluster.
- Fix a small bug in …
=> [Incubator][VC]Refactor Cluster and MultiClusterController interface methods

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
Currently, VC does not support DaemonSet like workload. Since tenants do not have full control/knowledge about super master nodes, allowing them to specify node in Pod is impractical and may lead to confusion. 
With this change, syncer does not handle Pod with NodeName set in the spec and a NotSupport event will be generated in the tenant master to notify the user.
=> [Incubator][VC]Do not sync tenant Pod with NodeName set in the spec

incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml
Currently, syncer updates tenant master node status every minute. But the tenant master node controller uses a 40 seconds grace period to detect host health. As a consequence, node controller constantly marks node and the Pods in that node Not Ready. 
The solution is to increase the node controller monitor grace period to a larger value. This change sets it to 200 seconds. Increasing the syncer update frequency is not considered due to the potential overhead.
=> [Incubator][VC]Increase node status monitor grace period

incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
This change adds storageclass periodic checker to make sure tenant and super are consistent.
We don't implement a more aggressive consistency guarantee logic such that watching tenant sc delete events to reduce the overhead of using informer.  We may add it later if necessary. Note that for storageclass, the source of truth is super master. If tenant master happens to create a sc with the same name as one of the sc in super, the checker reports a warning if their specs are different for now.
Manual Test:
Delete sc from tenant master and within 60 seconds, the sc is recreated again in tenant.
=> [Incubator][VC] Add storageclass object periodic checker

incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go
transfer the 'default' namespace to the corresponding namespace on the
super master before making pod env variables for master services
=> fix the master service namespace bug

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/config/sampleswithspec/example_foo.yaml, incubator/virtualcluster/config/setup/sample_foo_controller.yaml, incubator/virtualcluster/pkg/syncer/apis/config/types.go, incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/resources/secret/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/pkg/syncer/utils/string.go
This change provide a way to access to pod's own master using a kubeconfig.
=> [incubator][VC] provide kubeconfig according to service account

incubator/hnc/README.md
Update comments by adding a wait time (5 mins) for cert-manager webhook. Also suggests against uninstalling the webhook if intend to use it again.
=> Update README comments for HNC

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/controllers/object_controller_new.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/stats/counter.go, incubator/hnc/pkg/stats/stats.go
Create counters for controller stats, e.g. number of reconciliation
attemps, or api calls. Generate logs with all the stats if the
enable-test-log flag is set.
Tested on GKE cluster and found the generated logs in Stackdriver. The
logs stopped when the controllers were idle and once I did actions like
creating namespace or setting parents, the logs started generating
again.
=> Generate controller stats logs

incubator/virtualcluster/Makefile, incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/hack/lib/docker-image.sh, incubator/virtualcluster/hack/make-rules/release-images.sh, incubator/virtualcluster/pkg/controller/pki/pki.go, incubator/virtualcluster/pkg/controller/util/kube/util.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go, incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
add clusterIP of the default/kubernetes service to apiservercertificate. To achieve this, we proceed following steps before deploying apiserver,
* create namespace corresponding to the default ns on super-cluster.
* create the kubernetes service in the corresponding namespace on the
super master and get its clusterIP.
* generate certificate that including the clusterIP got in the previous step
for the apiserver.
other minor changes are,
* change Makefile to allow building image for the specified target
* move kubernetes related functions to 'virtualcluster/controller/util/kube'
=> [Incubator][VC]Add clusterIP of the default/kubernetes service to apiserver's certificate

incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go, incubator/virtualcluster/pkg/syncer/resources/register.go
This change adds syncer for PVC resource. This is a standard resource that only needs dws and checker. The logic follows the routine of other similar type of resources.
=> [Incubator][VC]Add PVC syncer

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
This change implements removing orphan vNode in tenant master. Orphan vNode means no Pods in the tenant master are bound to it, which can happen when vPod is deleted or recreated and bound to another vNode.  vNode is created by Syncer only. 
Why do we need to do this?
- Less pressure on sending vNode heartbeats to tenant master. If we don't do vNode GC, there could accumulate a lot of orphan vNodes in tenant master overtime.
- Better user serverless experience - you see what you use.
Technical challenges 
- K8s does not provide multi-objects consistency semantic. Even though Pod and the bound node are associated, APIServer does not provide an atomic way to perform "delete a node if no pods are bound to it". 
- From syncer's perspective, the biggest race is that uws tries to bind a vPod to …
=> [Incubator][VC]Implement vNode Garbage Collection

incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/controller/util/kube/util.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
In `aliyun` mode, once a VC is up and running,  patch an annotation that holds the ask slb id to the VC CR
```json
{"metadata":{"annotations":{"tenancy.x-k8s.io/ask.slbID": "<slb-Id>"}}}
```
=> [Incubator][VC]annotate slb id to vc cr

incubator/hnc/cmd/manager/main.go, incubator/hnc/config/default/manager_auth_proxy_patch.yaml
Add command line flags for qps and burst limit for apiservers. Set the default qps to 50 and default burst to 75 respectively.
This is a fix for #369 which reports low HNC performance due to default limit of 5 QPS and 10 burst rate set by client-go library.
Test: Tested via debug logs to ensure the default values are set and the config values changes correctly based on the input from 
manager_autho_proxy_pathc.yaml 
/assign @adrianludwin
=> HNC: Make API server QPS throttle configurable with a default value. 

incubator/virtualcluster/hack/lib/docker-image.sh
set array as empty if not set.
=> make docker-image.sh compatible to bash 3.2.57

incubator/virtualcluster/cmd/syncer/app/server.go
The go pprof server can be used to:
- debug hang thread
- count the inflight go routine number
- check the heap allocation
This can be used to analyze syncer resource consumption.
Test:
curl 172.17.0.7:6060/debug/pprof/goroutine?debug=2
This will list all the go routines used by syncer.
=> [Incubator][VC]Add a go pprof server in syncer

incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml, incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
The default node healthy checking intervals of the node-controller is 40 secs. In the VC scenario,  each node needs to send heartbeats to all tenant masters every 40 secs, which may cause high overheads. To mitigate this issue, we need to extend the default interval, however, ACK doesn't allow the user to change this value. Therefore, we disable the node controller by deleting the node-controller service account.
=> [Incubator] [VC] delete node-controller serviceaccount to disable node periodic checkin in aliyun modeg

incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/utils/string.go
Try to resolve issue #330 
when comparing virtual object and the real object, syncer will ignore annotation
prefixes specified in env `STDLN_OBJ_ANNO_PREFXS`
=> [Incubator][VC] ignore annotations that have specific prefixes 

incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
endpoints will auto managed by super master endpoints controller.
Besides, kube-proxy works well with native endpoints generated by endpoints controller locate on super master.
=> [incubator][VC] remove endpoints syncer

incubator/hnc/scripts/performance/clean-up-topologies.sh, incubator/hnc/scripts/performance/load-topology-full.sh, incubator/hnc/scripts/performance/load-topology-skewer.sh, incubator/hnc/scripts/performance/load-topology-wide.sh, incubator/hnc/scripts/performance/start-controllers.sh, incubator/hnc/scripts/performance/test.sh
Add scripts to load different topologies of namespaces into the cluster.
Start/restart controllers and output completion time and number of api
reads/writes to see the performance.
Tested on GKE cluster.
=> Add performance tests on controller start/restart

incubator/hnc/pkg/stats/stats.go
Previously, the stats were only initialized to serve data for logging
activities when the "enable-test-log" flag is set. Since we are going to
use the stats data to export metrics, the stats are now set as default
without flags.
Tested on GKE cluster.
=> Set stats.Init() as default

incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go
This change adds a check to see if an Event has been synced to tenant master to avoid unnecessary err messages about object already exists.
=> [Incubator][VC]Check mccontroller cache before upward syncing Events

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/stats/metrics.go, incubator/hnc/pkg/stats/stats.go
Export hierconfig_reconcile_total and hierconfig_writes_total metrics to
Stackdriver using OpenCensus. The metrics come from stats counters.
Tested on GKE cluster. I can see the hnc metrics in Stackdriver and the
data changed when new namespaces were created or set parent.
=> Add OpenCencus metrics and export to Stackdriver

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/constants/constants.go
DefaultOpaqueMetaPrefix is the vc internal label to promise vc works
=> [incubator][VC] add default opaque prefix to vc spec

incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
This change adds checker for endpoints and serviceaccount checkers. The implementation mostly follows the routines. 
- The endpoints equality method is changed since the ep are handled by tenant/super ep controller separately, hence the target Ref cannot be the same.
- For serviceaccount, we don't compare the secrets since they are created by tenant/super sa controller separately.
=> [Incubator][VC]Add endpoints and serviceaccount periodic checker

incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/dws.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go
- For LB type Service, the status should be backpopulated to tenant master.
- This change also add DWS service update functionality.
- Make code restructure to follow routine.
=> [Incubator][VC]Add Service UWS and DWS update functionality

incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/conversion/helper_test.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go
- Make sure all super master namespace is queried consistently, and tenant namespace is obtained from object annotation.
- Fix a failed UT.
- Always call GetVirtualOwner if possible, which is cheaper than GetVirtualNamespace.
=> [Incubator][VC] Misc. Cleanups

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/syncer.go
We cannot assume vc.namespace + "-" + vc.Name is unique in supermaster. 
For example:
vc.namespace : tenant-a
vc.name: vc1
vs.
vc.namespace : tenant
vc.name: a-vc1
This change adds a hash string in between to avoid naming conflict in super master.
Local test result:
tenant1admin-c1fba-vc-sample-1                   Active   99s
tenant1admin-c1fba-vc-sample-1-default           Active   99s
tenant1admin-c1fba-vc-sample-1-kube-node-lease   Active   45s
tenant1admin-c1fba-vc-sample-1-kube-public       Active   45s
tenant1admin-c1fba-vc-sample-1-kube-system       Active   45s
vc-manager                                       Active   32d
=> [Incubator][VC]Avoid duplicated root namespace name for virtual cluster

incubator/hnc/config/samples/hnc_v1_config.yaml, incubator/hnc/pkg/controllers/config_controller.go, incubator/hnc/pkg/controllers/hierarchy_controller.go, incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/setup.go, incubator/hnc/pkg/forest/forest.go
This PR creates object reconciler(s) when new type(s) are added to the
HNCConfiguration and informs the hierarchy reconciler about the new
object reconciler(s).
Specifically, it does the following tasks:
- Dynamically creates an object reconciler when a new type is added
in HNCConfiguration.
- Informs the hierarchy reconciler about the newly added object
reconciler so the corresponding objects can be propagated correctly
when the hierarchy structure changes.
Test: Verified on a GKE cluster that
- When adding a new type in HNCConfiguration, corresponding object
reconciler is created successfully.
- When adding a new object of the same type to a node in the namespace
tree, the object is propagated correctly to the descendants of the
node.
- When the tree structure changes (e.g., add another …
=> Dynamically create object reconcilers for new types.

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/secret/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/syncer.go
The number uws/dws workers for each resource may differ based on the frequency of the event and the latency requirement of resource. 
In this change, we assign Pod the highest number of workers. Other resources will be assigned low number of workers. Node uws is given high number of workers as well due to the frequent heart beat updates.
=> [Incubator][VC]Set number of dws/uws workers differently for each resource

incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
Each cluster cache watches for all synced objects hence we can use it to satisfy all read requests for synced objects. 
In this change, accessing tenant master to Get/List node and pod resources is replaced by accessing cluster cache. To achieve this, mccontroller adds two APIs: GetByObjectType and ListByObjectType.
=> [Incubator][VC]Always read synced objects from cluster cache

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/helper_test.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
If a virtual cluster object is deleted, the inflight reconcile requests (both uws and dws) may keep failing. This change fixes the problem by doing the following :
- For dws controller, where the cluster who sends the request is known, the request is removed if the owner cluster does not exist. 
- For uws controller, where the destination cluster is not known when request is created, we introduce a timeout to avoid infinite retry. We have periodic checker as a backup hence a timeout mechanism should not cause permanent inconsistency. 
This change also fixes a failed UT.
=> [Incubator][VC]Avoid infinite retries if virtual cluster is removed

incubator/hnc/pkg/controllers/config_controller_test.go, incubator/hnc/pkg/controllers/hierarchy_controller_test.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/suite_test.go, incubator/hnc/pkg/controllers/test_helpers_test.go
Add a unit test for config_controller.go to test the case that when a new type is added to HNCConfiguration singleton, the corresponding object reconciler can be created correctly.
This PR also does the following refactoring: 
-  Moves shared helper functions from each controller test files to a common file: test_helpers_test.go
-  Switches the object type in object_controller_test.go from Secret to Role because:
-  The behaviors that are tested in the object_controller_test.go are irrelevant to the object type or the creation of a new object reconciler.
-  Since the test suite creates the object reconciler for Role by default, object_controller_test.go can use the existing Role object reconciler for the tests 
instead of creating a new object reconciler.
-  The tests inside …
=> Add a unit test for config_controller.go

incubator/hnc/pkg/controllers/config_controller_test.go, incubator/hnc/pkg/controllers/object_controller.go, incubator/hnc/pkg/controllers/object_controller_test.go, incubator/hnc/pkg/controllers/test_helpers_test.go
Currently an empty source object will not be propagated to descendants if the descendants do not have any copy of the object as reported in #441. The PR fixes this issue so that empty source object will be propagated to descendants if the descendants do not have the copy of the object.
Fixes #441
=> Propagate empty source object to descendants if the descendants do not have not copy of the object.

incubator/virtualcluster/pkg/syncer/conversion/mutate.go
we should act as the kubelet 
https://github.com/kubernetes/kubernetes/blob/v1.16.5/pkg/kubelet/network/dns/dns.go#L383
=> [incubator][VC] put the cluster nameserver in front of the pod spec one

incubator/virtualcluster/pkg/syncer/metrics/metrics.go, incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
This change adds metrics counters for resource checkers. The metrics include resource mismatch and checker remediations.
This change also allows syncing the tenant kubernetes ep which is not created by ep controller.
=> [Incubator][VC]Add checker metrics for resource mismatch counts and remediation counts

incubator/hnc/README.md, incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/hierarchy_config_test.go, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/reconcilers/object_test.go, incubator/hnc/pkg/reconcilers/setup.go, incubator/hnc/pkg/reconcilers/suite_test.go, incubator/hnc/pkg/reconcilers/test_helpers_test.go
Replace "controller" with "reconciler" in hnc/pkg/controllers directory. "Controllers" can refer to both reconcilers and admission controllers. Since the controllers we implemented under hnc/pkg/controllers are actually reconcilers, using "reconciler" instead of "controller" would be more precise.
=> Replace "controller" with "reconciler" in hnc/pkg/controllers directory

incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
1. change metric-address of the controller manager to ":0" to prevent port collision
2. change ask timeout to 600 seconds
3. encode admin-kubeconfig in base64 before adding it to the annotation
=> [Incubatore][VC]encode admin-kubeconfig in base64 before adding it to the annotation

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go, incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/syncer/resources/node/dws.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/dws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
We should rely more on the counters reported by metrics server instead of watching for INFO logs. This change downgrades many syncer INFO logs.
=> [Incubator][VC]Downgrade log level for INFO logs

incubator/hnc/api/v1alpha1/hierarchical_namespace.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchicalnamespaces.yaml, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/reconcilers/setup.go
Create the empty HierarchicalNamespaceReconciler to only generate a log
with the information of the object being reconciled and setup with
controller manager.
Add "forbidden" state to CRD status.
Rename HierarchyReconciler to HierarchyConfigReconciler.
Tested on GKE: I created a sample hns object and found the log of
reconciling that hns object in Stackdriver.
Part of #457
=> Create the empty HierarchicalNamespaceReconciler

incubator/hnc/api/v1alpha1/hierarchical_namespace.go, incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/kubectl/create2.go, incubator/hnc/pkg/kubectl/root.go
Add a new `kubectl hns create` command `create2` to only create hns
instances in the parent namespace when creating subnamespaces.
Currently, `create` creates the hc singleton in the parent namespace.
`create2` will replace the current `create` when the hns reconciler is
implemented. The hc singletons will then be created by the hc or the hns
reconciler.
Tested on GKE cluster. I created a subnamespace using "kubectl hns
create2 -n parent child". The "child" hns instance was created in the
"parent" namespace and no "hierarchy" singleton hc instance was created
by this command. Then I saw the hns reconciler log on the hns instance
in Stackdriver.
Part of #457
=> Add `kubectl hns create2` to only create hns in parent namespace

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/syncer/resources/node/dws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/dws.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
This change makes sure the request in DWS queue does not contain any mutable fields which can potentially cause parallel reconcile for the same object. 
Since event_type is removed, the DWS reconcile logic of figuring out whether it is Add or Update or Delete is changed by checking current tenant/super master informer cache.
We also add UID consistency check for Pod/Service/Namespace objects (other resources will be handled in future change) in order to avoid confusing update/create sync events when the object with the same name is frequently created and deleted.
=> [Incubator][VC]Make DWS request only contain immutable fields

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/setup.go, incubator/hnc/pkg/reconcilers/suite_test.go
Create a flag to enable/disable the HierarchicalNamespace Reconciler and
also toggle the behavior of HierarchyConfig Reconciler accordingly.
Changes to the HierarchyConfig Reconciler behaviour is not implemented
in this commit.
Tested on GKE cluster. The reconcilers were created successfully
with/without setting the flag. I saw the test logs with the correct
values set in Stackdriver.
Part of #467, #457
=> Create a flag to toggle HC and HNS Reconcilers

incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
fixes #466
1. applying the leaderelection feature of controller-runtime to
vc-manager
2. change the default number of replicas to 2
3. don't set ownerreference for cross-namespace objects
=> [Incubator][VC] apply leaderelection feature to vc-manager

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
We should avoid adding dynamic field in workqueue request to avoid parallel reconcile. This change mainly does the following:
1) Remove FirstFailureTime field from UWS request struct;
2) Use workqueue NumRequeues API to bound the number of failure retries;
3) Add requeue in checker in case uws consistency check fails;
=> [Incubator][VC]Use workqueue NumRequeues API to avoid infinite retry

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Since DWS logic is restructured, we cannot track vPod delete event from dws. This change ensures ClusterVNodePodMap is updated when vPod is successfully deleted from tenant master.
=> [Incubator][VC]Update ClusterVNodePodMap when vPod is deleted

incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go, incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
This change adds UID check for rest of resources that have DWS in order to avoid any mis-creating/updating super master objects in case syncer has been offlined for a while.
=> [Incubator][VC]Add UID check for configMap/EP/PVC/Secret/SA resources

incubator/hnc/Makefile, incubator/hnc/api/v1alpha1/hierarchical_namespace.go, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/hierarchy_config_test.go, incubator/hnc/pkg/reconcilers/setup.go
In the hns reconciler, update the forest and enqueue in-memory
hierarchyConfig instance for hierarchyConfig reconciler to reconcile.
The hierarchyConfig reconciler will create the namespace with Owner
annotation and create/update both the parent and child hierarchyConfig
instances. If the hns reconciler is enabled by the flag, the hc
reconciler will get all hns objects from the forest instead of using the
"RequiredChildren" field in the hc spec.
Add integration tests with flag "make test HNS=1".
Tested by integration tests and manually with "kubectl hns create2 -n
parent child". The "child" namespace was created with Owner annotation
set to "parent".
Part of #457 . Fixes #473 .
=> Enable hns reconciler to create namespace

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object.go
This PR adds the support for 'ignore' mode in ConfigReconciler. Specifically, it adds following features:
- If the mode of a type is set to 'ignore', the corresponding object reconciler will ignore all subsequent reconciliations (e.g., new or changed objects will not be propagated).
- If the mode of a type is changed from 'ignore' to 'propagate', reconciliations for all existing objects of the type in the cluster will be triggered.
- If a mode of a type is unrecognized, it will be treated as 'ignore'.
- If a mode of a type is unset, it will be treated as 'propagate'.
Tested: GKE cluster; unit tests.
Design doc: http://bit.ly/hnc-type-configuration
Issue: #411
=> Support 'ignore' mode in ConfigReconciler.

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/helper_test.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
SA and secret name can be as long as 253 characters but the Label value max length is limited to 63 characters. We should not use name in Labels to identify pSecret that represents tenant service account secret. 
In this change, we switch to use sa/secret UID to identify pSecret that represents tenant service account secret.
=> [Incubator][VC]Avoid using Secret/SA name in Labels

incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object_test.go, incubator/hnc/pkg/reconcilers/test_helpers_test.go
This PR removes duplicate code in reconcilers_test package. Specifically, the duplicate code in methods that make an object (e.g., `makeSecret`), check if an object exists (e.g, `hasSecret`), and get the namespace where an object is inherited from (e.g., `secretInheritedFrom`) are removed.
=> Remove duplicate code in reconcilers_test package

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/pkg/kubectl/set.go
Add `allowCascadingDelete` to HC.spec. Enable `kubectl hns set parent
--allowCascadingDelete=true/false` to set the spec.
Tested manually on GKE.
Fixes #480 . Part of #457
=> Add `allowCascadingDelete` to HC.spec and enable `kubectl`

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/hierarchy_config_test.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/reconcilers/setup.go
Update transient HNS states and report invalid states if bypassing the
admission controller. Add a channel in the HNS reconciler to enqueue
HNS for reconciliation. Add HNS reconciler and HC reconciler into each
other so that they can enqueue the other resource. Sync the HNS
instances in HNS reconciler, instead of syncing the
spec.requiredChildren in "syncChildren()" func in HC reconciler. Add
integration tests to test all different states.
Tested with integration tests ("make test" & "make test HNS=1") and
on GKE cluster. To test manually, I added the "enable-hns-reconciler"
flag and commented out the webhook "Prevent changing parent of a
required child" part, since it uses the "RequiredChildOf" field in the
forest. I tested deleting the subnamespace, changing the annotation,
change the …
=> Update transient & report invalid HNS states

incubator/hnc/pkg/reconcilers/object_test.go
The flaky error is that when an initial propagation is not done, the
test expects to get the propagated object with success and see if it's
modified from the source but it failed when getting the object.
Added 1 second sleep to fix the flaky test.
=> Fix a flaky object controller test

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
For service with selector being set, the ep controller will handle the ep lifecycle. Syncer ignore those eps to avoid any possible conflicts. With this change, for all other eps, syncer will sync them to super master.
This change also bumps up the retry number to tolerate long syncer restart time.
=> [Incubator][VC]Sync non-service eps

incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go
If a type is removed from the HNCConfiguration Spec, we will set the corresponding object reconciler to "ignore" mode. 
Ideally, we should shut down the corresponding object reconciler. Gracefully terminating an object reconciler is still under
development (https://github.com/kubernetes-sigs/controller-runtime/issues/764). Once the feature is released, we will see if we can shut down the object reconciler instead of setting it to "ignore" mode.
Tested: GKE, unit tests
Design doc: http://bit.ly/hnc-type-configuration
Issue: #411
=> Set an object reconciler to "ignore" mode if its corresponding type is removed from the HNCConfiguration Spec

incubator/hnc/pkg/reconcilers/setup.go
"kube-public" is a namespace that is currently used to make "cluster-info" configmap readable to all users (see details in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/bootstrap-discovery.md#new-kube-public-namespace). HNC shouldn't reconcile objects in "kube-public" namespace.
=> Exclude "kube-public" namespace in HNC

incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go
After upgrading sigs.k8s.io/controller-runtime version to v0.5.0, we can create reconciler successfully even when the resource does not exist in the cluster. Therefore, we explicitly check if the resource exists before creating the reconciler. See detailed discussion in: kubernetes-sigs/controller-runtime#840
Tested: unit tests, GKE cluster
part of: #488
=> Explicitly check if a GVK exists before creating corresponding object reconciler

incubator/virtualcluster/pkg/controller/util/kube/util.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go, incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/syncer/syncer.go
This change adds owner reference to all namespaces that are associated with a virtualcluster object. This greatly simplifies the tenant objects clean up. 
This change also removes reconciler.ClusterInfo struct which is not necessary.
=> [Incubator][VC]Add owner reference for all namespaces created by syncer and vcmanager

incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
Rename ns.Owner field so that it can be used in the cascading deletion
implementation.
Tested by 'make test' and 'make test HNS=1'
This commit fixes #469. Part of #457 .
=> Rename ns.RequiredChildOf to ns.Owner in forest

incubator/hnc/cmd/manager/main.go, incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hncconfig.go, incubator/hnc/pkg/validators/hncconfig_test.go
This PR implements a validation controller for hncconfigurations resource. 
Specifically, following requests will be denied by the controller:
- Missing RBAC configuration
- Non-default RBAC mode
- At least one type in the configuration does not exist in the cluster
- Invalid object name (the name should be config)
- Unrecognizable mode
- Multiple configurations for the same type
- Delete `config` object
Tested: unit tests, GKE cluster
Issue: #411
=> Implement a validation controller for hncconfigurations resource.

incubator/hnc/pkg/validators/hncconfig.go, incubator/hnc/pkg/validators/hncconfig_test.go
Unlike `StatusReasonForbidden`, `StatusReasonInvalid` does not show custom text in terminal when sending an invalid request to the apiserver (see details [here](https://github.com/kubernetes-sigs/multi-tenancy/pull/522#discussion_r395117111)). We will contact the controller-runtime team for trouble shooting. In the meantime, we will use `StatusReasonForbidden` so that users can see detailed reason of denying a request.
This PR also does the following refactoring to address comments in #522 :
-  Make `Exists` only return an error
- Change `if` statement to `switch` in the `validateType` method
Issue: #411
=> Change StatusReasonInvalid to StatusReasonForbidden in hncconfig.go

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/constants/constants.go
The default client-go qps and burst is 5 and 10, which is way too small for syncer. 
Since tenant master has its own rate limit control, we enlarge the syncer client qps and burst default to 1000 and 2000. Even if syncer client hits "too many requests" error, the failed reconciling will be retried later.
=> [Incubator][VC]Increase the QPS and burst for syncer clients

incubator/hnc/pkg/config/default_config.go, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/test_helpers_test.go
This PR handles missing or non-default specs for Role and RoleBinding in ConfigReconciler. 
Specifically, it implements the following two features:
- If the specs for Role and/or RoleBinding are missing, the ConfigReconciler will insert default configuration in the spec for each of them
- If the specs for Role and/or RoleBinding are non-default, the ConfigReconciler will modify the spec to the default configuration for each of them
Issue: #411
=> Handle missing or non-default specs for Role and RoleBinding in ConfigReconciler.

benchmarks/config.yaml, benchmarks/e2e/tests/e2e.go, benchmarks/e2e/tests/e2e_test.go
This PR fixes #445, the issue was due to the 1.13 go release, [notes](https://tip.golang.org/doc/go1.13#testing):
>Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.
=> #445 - flag.Parse causes issue in go 1.13

benchmarks/e2e/tests/block_multitenant_resources/README.md, benchmarks/e2e/tests/block_other_tenant_resources/README.md, benchmarks/e2e/tests/require_run_as_non_root/README.md
This pull request updates the readme to use the correct kubeconfig for the cluster administrator to avoid confusion.
=> Corrects the kubeconfig in Benchmarks Readme

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go
This PR handles multiple configurations of the same type in ConfigReconciler. If there are multiple configurations for the same type, only the first configuration will be followed, the rest will be ignored.
Tested:unit tests, GKE cluster
Issue: #411
=> Handle multiple configurations of the same type in ConfigReconciler

benchmarks/.gitignore
This test adds a .gitignore file to prevent adding the tests.test file that is generated when running the benchmark test
=> Adds .gitignore file

incubator/virtualcluster/README.md, incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/cmd/vn-agent/app/options/options.go, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml, incubator/virtualcluster/pkg/controller/util/kube/util.go, incubator/virtualcluster/pkg/vn-agent/config/config.go, incubator/virtualcluster/pkg/vn-agent/server/route.go, incubator/virtualcluster/pkg/vn-agent/server/server_test.go, incubator/virtualcluster/pkg/vn-agent/server/translate.go
1. translate the  url for super master
2. parse `URL.Rawquery` for streaming connection
3. create serviceaccount `vn-agent` to access pod and related subresources (log, exec, portforward) 
4. use the bearer token of the vn-agent's serviceaccount to connect to super master
=> [Incubator][VC] allow vn-agent to forward request to super master if kubelet-client-crt is not available

incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
panic
```
E0327 04:51:56.827375       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 550 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17d38a0, 0x2c67c40)
/Users/qinnzhuang/vmshare/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/qinnzhuang/vmshare/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17d38a0, 0x2c67c40)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/kubernetes-sigs/multi-tenancy/incubator/virtualcluster/pkg/syncer/resources/persistentvolume.(*control …
```
=> [incubator][VC] fix panic: when pPV not been bound, claimRef is nil

benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go, benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go, benchmarks/e2e/tests/e2e.go, benchmarks/go.mod
This pull request renames the go.mod to "sigs.k8s.io/multitenancy" and also updates the imports in different files
=> Renames github.com/realshuting to sigs.k8s.io for uniformity

benchmarks/documentation/run.md
This updates the Readme on how to run the test. It removes commands on how to compile the binary has that throws an error. See [comment](https://github.com/kubernetes-sigs/multi-tenancy/pull/545#issuecomment-605385781)
=> Updates the Readme

tenant/pkg/controller/tenant/tenant_controller_suite.go, tenant/pkg/controller/tenant/tenant_controller_test.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_helper.go
Changes
1. Roles and Rolebindings are assigned by controllers to the tenant admin
2. Only tenant admin is allowed to create tenantnamespace whereas other SA not.
Currently to test above changes, used exisiting cluster
Tested: manually caused some conditions and verified that they were
reported correctly.
=> Enable Tenant and Tenantnamespace reconcilers to check

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
Supermaster Pod might be deleted at arbitrary time by admin or node controller if node is down. 
If we keep vPod alive and only recreate pPod,  the pPod may be created in a different node. 
Since we cannot rebind vPod to a new node, this will lead to inconsistency of nodename between tenant master and super master. 
In this change, if vPod has been bound to a node but the pPod for some reason is deleted, we 
deleted the vPod as well. Typically, the workload controller in tenant master will create a new Pod.
Due to rare race, it is still possible that the pPod nodename is different from vPod's nodename.
The checker will detect such inconsistency and delete the vPod.
=> [Incubator][VC]Delete vPod if pPod is evicted

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
The default value is "false," so it's fine to leave it optional. This
also unbreaks the current HNS plugin.
TESTED: on a GKE cluster, couldn't call `k hns set --parent` without
this change, and call call it after this change.
=> Make allowCascadingDelete optional

incubator/hnc/pkg/kubectl/create.go, incubator/hnc/pkg/kubectl/root.go
Part of #457.
Tested on the GKE cluster.
=> Rename kubectl hns command 'create2' to 'create'

incubator/hnc/Makefile, incubator/hnc/README.md
Do not allow overwriting of an image and tag if it already exists in the
repository. This prevents us from being able to overwrite released
images. Pass in FORCE_RELEASE=true to override this behavior.
=> Address #333. Fail a release on duplicate image and tag

benchmarks/e2e/tests/block_host_pid/block_host_pid.go, benchmarks/e2e/tests/e2e.go
Fixes #407. It adds the test for [https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_host_pid/README.md](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_host_pid/README.md)
=> Adds block_host_pid test

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/pkg/reconcilers/hnc_config.go, incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object.go
One of the HNC config observability tests was failing because we didn't
wait for the HNC config reconciler to pick up a change before verifying
that it was working:
* We changed a sync mode from "propagate" to "ignore"
* We created a new object
* We verified that this object wasn't created
Occasionally (about 1/4 of the time), the object reconciler would run before
the HNC config reconciler had a chance to change it to "ignore." The fix
is to add a "Mode" to the HNC Config status, so we can tell when the
reconciler has actually picked it up. This is also useful for when the
spec doesn't include an explicit mode.
This change also includes a few other minor improvements:
* If there's an extra HNC Config object, and we can't write it back due
to an apiserver error, retry the failure …
=> Add better HNC Config observability and fix flaky test

incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/object.go
I had a hard time reading the logs with all the logspam from the
validators, which very rarely have anything useful to say IMO.
Tested: observed that the logs were easier to read
=> Reduce default verbosity of validators

incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/reconcilers/object_test.go, incubator/hnc/pkg/reconcilers/test_helpers_test.go
See #347. When an object is removed, we need to remove it from the
in-memory forest even when the object is in a namespace with a critical
condition, because when the condition is resolved, we'll use the forest
to re-sync all descendants of that namespace, and if the forest has
stale objects in it, the propagated copies won't be removed.
Added several other cleanups including:
* Made several names more unique so they can be more easily searched
(e.g. replaced `delete()` with `deleteObject()`)
* Factored out a new syncMissingObject() functionout of Reconcile()
* Some cosmetic renames plus a bunch of longer comments
TESTED: new integ test fails without the fix and works with it; also
tested manually on GKE.
=> Always sync objects to forest, even in namespaces with critical conditions

incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/validators/hierarchy.go
Since we only use subnamespace owner annotation as source of truth and
always set parent to the owner in HCR, ns.Owner string field is not
necessary and a ns.IsOwned bool field is enough.
Tested with 'make test' and manually tested the webhook of changing an
owned namespace's parent on GKE cluster.
Part of #457 
Fixes #552
=> Replace ns.Owner with ns.IsOwned in the forest

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/hack/test-issue-501.sh, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/setup.go
Add a finalizer to all HNS instances and remove it only when the
subnamespace is deleted and purged for a cascading deletion OR if it's a
single deletion (HNS_MISSING condition will be set on the subnamespace
then).
Add a finalizer to HC instances only if the namespace has HNS instances.
It will be removed when the HNS instances are all deleted and purged for
a cascading deletion OR if it's a single deletion (a new default HC
instance will be created by the next HC reconciliation).
Add allowCascadingDelete field to forest. This is updated by the
hc.Spec.AllowCascadingDelete field.
Add allowCascadingDelete() func to forest. It indicates if the namespace
can be cascading deleted.
Update and move onMissingNamespace() to the top of HCR when a namespace
doesn't exist.
Add a testing script …
=> Implement HNS cascading delete

incubator/hnc/pkg/kubectl/create.go, incubator/hnc/pkg/kubectl/describe.go, incubator/hnc/pkg/kubectl/set.go, incubator/hnc/pkg/kubectl/tree.go
The captilization helps align it better to kubectl help usage
documentation
=> Capitalize help usage and make more clear

incubator/hnc/pkg/forest/forest.go
Remove the link to the GitHub issue and give an explanation for the type
in the forst in-memory map
=> Address #281. Add comment to GVK object map in forest

incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/object.go
The object reconciler locks the forest twice: once when determining what
to do with an object (i.e. propagate or delete it), and once after the
propagation/deletion has been attempted so we can update the condition.
Prior to this change, we cleared all conditions associated with an
object during the first lock, and set them (if necessary) during the
second lock.
Unfortunately, in cases where objects failed to be propagated, this set
up neverending spin loop:
1. During the first lock, we'd clear the condition. Because the
conditions changed, we'd re-enqueue the HC reconciler.
2. If the HCR managed to run before the second lock was acquired (which
was usually the case), it would see that its conditions had changed and
update the HC.
3. During the second lock, we'd put the object condition …
=> Set object conditions atomically (#326)

incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
This change ensures that PV spec is updated to the correct PV in tenant by checking the uid.
Also checker will delete a vPV if its uid is not equal to the pPV uid even if their names are the same.
This change also fixes the rbac rules for storageclass resource.
=> [Incubator][VC]Add uid check for pv update and periodic check

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/api/v1alpha1/hnc_config.go
fixes #500 
Tested: I added lines like:
```go
fmt.Println(string(api.CritParentMissing))
```
in cmd/manager/main.go to check if the condition code is printed in initial-capitalized CameCase string.
=> HNC: Change condition codes to CamelCase strings.

incubator/hnc/pkg/validators/hierarchy.go
The decoded could possibly be empty, e.g. when the request operation is
DELETE, the decoded will be empty.
Tested by 'make test'.
=> Fix dereference of a possibly nil pointer

incubator/hnc/hack/test-issue-328.sh, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go
This changes ensures that any conditions on ancestor namespaces caused
by objects in their descendants are removed if a child namespace is
removed from its hierarchy. Without this change, no reconciler will ever
attempt to remove the CANNOT_PROPAGATE_OBJECT condition from an
ancestor, and it will incorrectly sit on the (old) ancestor namespace
until HNC is restarted.
I initially tried to fix this by having the object reconciler determine
from scratch whether it was needed, by searching the forest for all
possible copies of the source object and looking for conditions. But I
found that approach to be overly confusing and it still needed to be
triggered in a variety of ways.
I don't really love the fact that most of the code here is in
hierarchy_config.go; it would be more natural to put it …
=> Flush obsolete conditions when tree changes (#328)

incubator/hnc/Makefile, incubator/hnc/README.md, incubator/hnc/cloudbuild.yaml, incubator/hnc/hack/krew-hierarchical-namespaces.yaml
Issue #594.
TESTED: ran `make release` all the way to the point to publish to
k8s-staging-multitenancy, but I didn't have permissions to push there
=> Rename kubectl-hierarchical_namespaces to kubectl-hns

incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go
This change fixes a few checker bugs:
1) pPV can be nil, which can cause a crash. 
2) If Pod spec missmatches, the remediation should be requeuing in dws.
3) If service spec missmatches, the remediation should be requeuing in dws.
=> [Incubator][VC]Fix a few checker bugs.

incubator/hnc/pkg/kubectl/root.go
This PR changes the `Use` field of the root command of kubectl plugin from `kubectl hierarchical-namespaces` to `kubectl-hns` because:
- We switched from "kubectl-hierarchical_namespaces" to "kubectl-hns" in #609 
- Only the first word of the `Use` field will be displayed in the "Usage" section of a root command, we set it to "kubectl-hns" here so that both "kubectl" and "hns" will be shown in the "Usage" section.
Issue: #601
=> Change the Use field of the root command to "kubectl-hns" for kubectl plugin 

incubator/hnc/pkg/reconcilers/hnc_config_test.go, incubator/hnc/pkg/reconcilers/object_test.go, incubator/hnc/pkg/reconcilers/test_helpers_test.go
This addresses issue #586. This is to ensure that objects created in one
test case will not affect objects in another test case.
TESTED: Ran the tests through 10 times via go test ./pkg/reconcilers/...
=> Clean up created objects in tests

incubator/hnc/pkg/kubectl/config.go, incubator/hnc/pkg/kubectl/configdelete.go, incubator/hnc/pkg/kubectl/root.go
This PR adds a kubectl command to delete the HNC configuration of a specific type. 
Example usage: `kubectl hns config delete-type --apiVersion v1 --kind Secret `
Issue: #454
=> Add a kubectl command to delete the HNC configuration of a specific type

incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
This change restructures the mock test so that the RunDownwardSync method can be reused by
the mock tests of other resources.
To achieve this, this change makes a few abstractions in the controller creation codepath. 
Basically, the manager.Controller interface is used in the util.RunDownwardSync method instead of a specific controller implementation, making the mock test infra code reusable for all synced resources.
=> [Incubator][VC]Restructure syncer namespace mock test

incubator/hnc/Makefile, incubator/hnc/pkg/config/default_config.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/reconcilers/setup.go, incubator/hnc/pkg/validators/hierarchical_namespace.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go, incubator/hnc/pkg/validators/object.go, incubator/hnc/pkg/validators/object_test.go
Fixes #607. Parent namespaces in the excluded namespaces should be
denied. Objects in parent namespaces should be ignored.
=> Update validators to respect excluded namespaces

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go, tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
This change has fixed the problem that tenantnamespaces cannot be cleaned up in UTs.
The following have been done:
- Since tenantnamespace UT has tenant controller installed recently, we should remove creating tenant admin namespace step in old tests. 
- The request chan used in TestReconcile is a blocking channel, we have to make sure the request is read from the channel otherwise the following reconcile logic is blocked. Hence, in all tests, we make sure a reconcile request is received after deleting tenantnamespace CR and wait until the CR is removed before calling deleting tenant. This ensures that the finalizer of the tenantnamespace CR is removed.
- Fix a bug in tenantnamespace reconciler to handle a case that the clusterrole does not exist when the tenant does not have the tenant …
=> Fix tenantnamespace UTs

incubator/hnc/pkg/kubectl/config.go, incubator/hnc/pkg/kubectl/configset.go, incubator/hnc/pkg/validators/hierarchy.go
This PR adds a kubectl command to set the HNC configuration of a specific type. Specifically it implements the following features:
- If the type exists in the spec, it will update the configuration of the type. 
- If the type does not exist in the spec, it will add the configuration in the spec.
Example usage: `kubectl hns config --apiVersion v1 --kind Secret ignore`
Issue: #454
=> Add a kubectl command to set the HNC configuration of a specific type

incubator/hnc/hack/test-issue-605.sh
We suspect obsolete CannotUpdate condition will be cleared on the child
namespace who just changes its parent but not on its descendants.
Therefore, this new test case is added to verify that.
It turned out the condition was cleared eventually on the descendants.
However, the object reconciliation was triggered by controller-runtime,
not by HNC reconcilers. Thus this test is tailored to be able to tell if
the object enqueue is triggered by controller-runtime or our HNC
reconcilers. The difference is that controller-runtime has exponential
backoff. After issue 605 is fixed, we should see the obsolete conditions
in descendants are gone immediately instead of waiting for the
controller-runtime exponential backoff retry.
Tested by running this script and could see around first 9 out of 10 …
=> Test if obsolete CannotUpdate condition gets cleared in descendants

incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/object.go
As described in issue 605, obsolete CannotUpdate condition was not
cleared on the descendants namespaces of a namespace who just changes
its parent. This commit changes the key of a CannotUpdate condition from
the local object to the source object if it exists. Therefore, we can
flush obsolete conditions on descendants by clearing the conditions by
ancestor namespaces, the same way as how we flush obsolete conditions on
ancestors.
Tested with "make test" and running the test script
"hack/test-issue-605.sh' seeing the CannotUpdate condition was gone
immediately in all 10 attempts. See [results](https://gist.github.com/yiqigao217/a99afd57f5a5e3084d90b56fad31c99d) and [logs](https://gist.github.com/yiqigao217/424eafae7ac4900753b432e7768543e0).
Fixes #605
=> Flush obsolete conditions on descendants

incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/uws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/secret/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
This change refactors the manager.Controller interface by doing this followings:
- Rename the interface from Controller to ResourceSyncer since there are too many "Controller" terms in VC project and they often look confusing.
- Add BackPopulate method to the interface, which is needed for UWS mock test (in the future)
- Change the input of the BackPopulate method of storageclass controller to a string in order to meet the interface requirement.
In next change, I will extract the UW controller code to a common structure. This will help for both
removing duplicated code and supporting UWS mock tests.
=> [Incubator][VC] Refactor manager.Controller interface

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
This change ensures ClusterVNodePodMap is consistent when scanning all tenant Pods in periodic check. 
With this change, it is almost impossible for vNode gc routine to wrongly remove a vNode if it 
has been bound with a vPod since the DefaultvNodeGCGracePeriod is 120 seconds (larger than the default  periodic check interval of 60 seconds).
=> [Incubator][VC] Ensure ClusterVNodePodMap is consistent in Pod checker.

incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go, incubator/virtualcluster/pkg/syncer/util/test/runUWS.go, incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
This change builds the framework for running uws mock tests. 
- uitl/test/runUWS.go is created. The RunUpwardSync method is provided to orchestrate the mock test workflow.
- Introduce ResourceSyncerOptions struct to combine the controller options of mccontroller and uwcontroller. `IsFake` field is moved from mccontroller.Options to manager.ResourceSyncerOptions.
- Remove reconciler.UwsRequest. All uws controllers push object key string in their workerqueues. 
- Add pod/uws_test.go to use the new uws test framework. A few example tests are included.
=> [Incubator][VC]Add Pod UWS mock tests

incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/syncer/patrol/patroller.go, incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go, incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go, incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go, incubator/virtualcluster/pkg/syncer/resources/event/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/node/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker.go, incubator/virtualcluster/pkg/syncer/resources/secret/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go, incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
This change introduces Patroller struct to abstract the current periodic checker mechanism used by all resource syncers. This is the prerequisite for implementing checker mock tests. 
A new method PatrollerDo is added to manager.Controller interface and the StartPeriodChecker method is renamed to StartPatrol.
=> [Incubator][VC]Introduce Patroller to abstract periodic checker

incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go, incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
This change add mock test for Pod periodic checker. With these tests, the checker.go code coverage reaches 63.8%.
This change also fixes a bug found during the mock test. The `checkContainersImageEquality` method sure not directly modify the input pObj since the change will be saved in the informer cache.
=> [Incubator][VC]Add Pod patrol mock tests

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
TODO: vPod unscheduled case. pod binding event causes fakeClient panic. pod action is overwrote by pod binding action in fakeClient tracker.
test coverage 33.3% -> 65.6%
=> [incubator][VC] add more pod uws test case

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go, incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go, incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
This change has the done the following to enable vNode GC mock tests:
- Instead of using another go routine, the periodic gc checker is moved to Pod PatrollerDo method. 
- Introduce `vNodeGCGracePeriod` field in Pod controller so that we can manipulate the value.
- Change RunPatrol to allow calling external function to manipulate the controller state. 
The checker code coverage increases from 62% to 80% with the added tests.
=> [Incubator][VC]Add vNode GC mock tests

incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/go.mod, incubator/virtualcluster/pkg/controller/util/logr/util.go
1. generate logr.Logger based on zap.Logger
2. allow zap.Logger to output the log to a user-specified file
3. if the user does not specify any log file, log to stderr only
=> [Incubator][VC] allow user to specify a log file for vc-manager

incubator/virtualcluster/cmd/syncer/app/config/config.go, incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/pkg/controller/util/kube/util.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go, incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/cluster/fake_cluster.go, incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go, incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
We were adding owner reference to all the super master namespace which points to VC CR. We expect when VC CR is removed, the gc controller will automatically remove super master namespace. This mechanism has a flaw such that vc object is namespace scoped object. Namespace object's owner has to be a cluster scope object otherwise the gc controller may not find the owner and delete the namespace unexpectedly. 
This change resolves the problem by applying lazy gc relying on the namespace periodic checker. 
Once a VC CR is removed, the checker will identify those orphan namespaces and remove them. 
New mocker tests are added. Since the namespace controller now needs the vc client/informer, I choose to duplicate some mock test framework code in this change. More clean up can be done in future …
=> [Incubator][VC]Implement super master namespace GC

benchmarks/documentation/run.md, benchmarks/e2e/config/config.go, benchmarks/e2e/config/utils.go, benchmarks/e2e/tests/e2e_test.go
This pull request allows for the config file to be passed in as a flag with an appropriate default value when the flag isn't provided.
This makes testing easier as the config.yaml in the repo doesn't need to be replaced or rewritten
=> Enables the path to the config to be passed in as a flag

incubator/hnc/Dockerfile, incubator/hnc/Makefile, incubator/hnc/cmd/manager/main.go, incubator/hnc/config/default/kustomization.yaml, incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/config/internalcert/kustomization.yaml, incubator/hnc/config/internalcert/manifests.yaml, incubator/hnc/go.mod, incubator/hnc/go.sum, incubator/hnc/pkg/validators/setup.go, incubator/hnc/third_party/open-policy-agent/gatekeeper/LICENSE, incubator/hnc/third_party/open-policy-agent/gatekeeper/README.md, incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go, incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs_test.go
Fork the cert management from open-policy-agent/gatekeeper repo to serve
as the default internal cert management for HNC.
Add an "enable-internal-cert-management" flag to switch between using
the internal cert (integrated Gatekeeper cert) or the external cert
"cert-manager".
Update main.go to start the controller manager with internal certs first
and once the cert files are ready, add other controllers and webhooks if
webhook is enabled and internal certs are used.
Refactor the cert generation and validator startup into
pkg/validators/setup.go.
To use external cert-manager, update config/default/kustomization.yaml
and manager_auth_proxy_patch.yaml as instructed. Run 'make deploy-cm'
before 'make deploy'.
Tested on a GKE cluster. The manager restarts 0 times and the webhooks
are working as …
=> Integrate GK cert as the default internal cert

incubator/hnc/cmd/manager/main.go, incubator/hnc/pkg/stats/metrics.go, incubator/hnc/pkg/stats/stats.go
We got a few comments internally that we shouldn't be putting too many
tags on our metrics by default. I also doubt that detailed stats would
be that useful unless we're doing performance testing, so I made the
GroupKind object tags flag-enabled and disabled them by default
Tested: running HNC on StackDriver, I observed that by default,
GroupKind tags are not displayed on our metrics, but restarting HNC with
--suppress-object-tags=false brought them back.
=> Reduce default cardinality of metrics

incubator/hnc/Dockerfile, incubator/hnc/cmd/manager/main.go, incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/config/default/manager_webhook_patch.yaml, incubator/hnc/config/webhook/service.yaml
Make the HNC container image run as non root. Add securityContext in the
HNC pod to make containers in it run as non root.
Add a port flag that defaults to 443 in the code. Since the container is
run as non root, it's not able to use ports below 1024 reserved for root
only. Therefore, in the pod manifest, set port flag to 9443 and have the
webhook service map the 443 port to targetPort 9443 in the conainer.
Tested on a GKE cluster with PSP of notrunasroot is enabled.
=> Make HNC container run as non root

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/pkg/kubectl/create.go, incubator/hnc/pkg/kubectl/set.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go
The documentation now uses the term "subnamespaces" so all internal and
external code should use that as well.
Tested: none
Addresses #667
=> Remove the term "self-serve (sub)namespace"

benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go, benchmarks/e2e/tests/e2e.go
This PR fixes #408. It adds the test for[https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_host_ipc/README.md](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_host_ipc/README.md)
=> Adds block_host_ipc test

incubator/hnc/api/v1alpha1/hierarchical_namespace.go, incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/hack/test-issue-501.sh, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace.go, incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/validators/hierarchical_namespace_test.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/namespace.go, incubator/hnc/pkg/validators/namespace_test.go
Part of #667. The term "owned" namespace has been changed throughout to
"subnamespace"; the annotation changed from `ownerReference` to
`subnamespaceOf`; the term "owner namespace" has usually been changed to
simply "parent."
Tested: ran hack/test-issue-501.sh; everything works as well as expected
given that the new webhooks prevent us from doing the wrong thing. Also
ran the HNC demo script.
Fixes #667
=> Change "owned" namespaces to subnamespaces

incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/object.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
Now that we have subnamespaces, we can't have missing namespaces in the
middle of a tree, only at the root. Simplify the authz checks to reflect
this, and better handle the two reasons why the namespace might be
missing (HNC is starting up vs the namespace is truly orphaned).
Tested: manually confirmed that we can fix namespaces with the
CritParentMissing condition, either by making it a root or recreating
the missing parent. Also manually confirmed that we can't change the
properties of a namespace with a critical ancestor. Added logs and
verified that we're checking authz on the correct namespaces in multiple
cases. Also added new tests to confirm all of this automatically.
=> More robust server checks

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/pkg/forest/forest.go, incubator/hnc/pkg/forest/forest_test.go, incubator/hnc/pkg/foresttest/foresttest.go, incubator/hnc/pkg/kubectl/tree.go, incubator/hnc/pkg/reconcilers/hierarchy_config.go, incubator/hnc/pkg/reconcilers/hierarchy_config_test.go, incubator/hnc/pkg/validators/hierarchy.go, incubator/hnc/pkg/validators/hierarchy_test.go
If a user bypasses the admission controller, they can create namespace
ancestry cycles, but these have never been correctly represented
in-memory in HNC, and therefore were not correctly reported. For
example, only _one_ namespace in a cycle would have the
CritInvalidParent condition, as described in #666.
This commit includes several tightly-coupled changes to fix this:
* The Forest no longer prevents you from creating cycles. Instead,
Namespace.CycleNames() returns a non-nil list of a namespace is in a
cycle, and other methods like AncestryNames() and DescendantNames() are
now cycle-safe.
* The kubectl-hns plugin correctly handles cycles
* The HC reconciler ensures that other cycle members are enqueued when a
cycle is created or broken, and uses the new CritCycle condition on all …
=> Better handle namespace cycles

incubator/virtualcluster/pkg/vn-agent/server/server_test.go, incubator/virtualcluster/pkg/vn-agent/server/translate.go
This add the `container=name` query string to the logs request like it is done for other kubelet proxied requests.
Fixes #707
=> [VC]: Adding container name in the logs vn-agent passthrough

incubator/hnc/docs/user-guide/concepts.md, incubator/hnc/docs/user-guide/how-to.md
Suggestion from an internal reviewer - don't use "K8s" in documentation, just use "Kubernetes."
=> Stop using the contraction 'K8s'

incubator/virtualcluster/hack/lib/docker-image.sh
This switches the container used to build the VC components to `distroless` to follow  https://github.com/kubernetes/enhancements/blob/8fd69422d913706c0badb30b78ac07698c9aaecd/keps/sig-release/1729-rebase-images-to-distroless/README.md KEP. This shaved about 30mb per container.
=> [VC]: Switch to distroless image

incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/pkg/validators/namespace.go
This validator was previously called `vnamespace.k8s.io`, unlike all
other HNC validators which had names like
`hierarchyconfiguration.hnc.x-k8s.io`. When the validator rejected
changes, this ambiguous name made it hard to tell where the rejection
was coming from ("what's a vnamespace?" and "which controller is
that?"). The new name - `namespaces.hnc.x-k8s.io` - clearly identifies
the origin (HNC) and cause (namespaces) of the error.
Tested: deployed to my cluster, verified the errors make sense both with
and without the backing service running.
=> Fix the namespace validating admission name

incubator/hnc/internal/forest/forest.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/setup.go
Rather than going through the forest, keep an in-memory singleton and
let anyone ask for the HNC Config to be re-reconciled (in preparation
for work on #736).
Tested: unit tests; verified that this worked properly with the fix to
issue #736.
/assign @sophieliu15 
/cc @yiqigao217
=> Simpler HNCConfig reconciler triggers

incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/metrics/metrics.go
Enable prometheus metrics for uws queue, mccontroller queue and syncer queue.
These metrics is helpful for location problem that sync slowly or create virtual cluster slowly.
=> enable workqueue prometheus metrics

incubator/hnc/internal/forest/namespaceconditions.go
Minor typo was ensuring that it looks like there were lists of affected
objects even though in reality, there were none other than the namespace
itself.
Tested: redeployed HNC and verified that the empty list disappeared both
in YAML and when viewed via `kubectl hns describe`.
Fixes #746 
=> Don't add empty AffectedObject entries

incubator/virtualcluster/pkg/syncer/resources/node/controller.go
PR #745 introduces a bug such that the nodeNameToCluster map is mistakenly removed. This change fixes it.
=> [VC] Fix a nulltpr crash

incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go
Without this change, if a subnamespace is missing its anchor, the
condition can never be resolved. This change allows an admin to fix the
problem without disabling the validating webhook.
Tested: new unit test; verified by hand that I can recreate missing
anchors but only with the correct parent.
=> Allow recreation of missing subns anchors

incubator/hnc/hack/test-delete-anchor-crd.sh, incubator/hnc/hack/test-issue-501.sh, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/hnc_config_test.go
A reasonable admin action is to call `kubectl delete -f manifests.yaml`,
but this will delete the CRDs and hence the subnamespace anchors. If any
namespace have cascading deletion enabled, this will delete the
namespaces themselves, which is surprising and destructive. This change
disables cascading deletion if the Anchor CRD itself is being deleted,
as opposed to any one anchor CR.
Tested: Added hack/test-delete-anchor-crd.sh and confirmed that it fails
on HEAD and passes with this fix. Also verified that log messages looked
good. Tried deleting some subnamespaces with and without setting
allowCascadingDelete and everything worked properly. Also reran
test-issue-501.sh, which _mostly_ worked although it looks like the
webhooks now prevent us from getting a SubnamespaceAnchorMissing …
=> Don't delete subnses with the Anchor CRD

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hierarchy_config_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
Part of #763 
Add `forest.Namespace.ExternalTreeLabels` field to store external
hierarchy in memory. Add `syncExternalNamespace()` func in
`HierarchyConfigReconciler` to update the external tree labels in the
forest. Enqueue descedants if the namespace is converted from external
to internal or vice versa so that the external tree labels can be
removed or propagated to the descendant namespaces.
Skip `syncSubnamespaceParent()`, `syncParent()`, `syncLabel()` for external
namespaces. In `syncLabel()`, for an internal namespace, if the root
ancestor is an external namespace, propagate all the external tree
labels too.
Tested by "make test" with three new integration test cases.
=> Reconcile external namespaces and update tree labels

incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/config/manager/manager.yaml
We only have one pod in our deployment, so leader election does nothing
but add about 10s of delay when HNC starts up. Let's get rid of it for
now.
Tested: measured ~11s of startup delay with and without leader election.
I've been running without it for a few days and everything seems to work
fine.
=> Disable leader election

incubator/hnc/config/rbac/role.yaml, incubator/hnc/hack/test-issue-772.sh, incubator/hnc/internal/reconcilers/object.go
I _think_ HNC used to be able to propagate the `admin` role, but there
were several permission (deletecollection, impersonate) that don't
appear to be working in 1.15. I've now added these permissions to the
HNC service account so it can grant them.
Tested: new hack/test-issue-772.sh verifies that HNC can propagate the
`admin` builtin; it fails without this change and passes with it. The
existing hack/test-issue-771.sh, which uses `cluster-admin`, continues
to be unpropagateable as expected.
Fixes #772 
=> Let HNC propagate builtin admin rolebindings

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/hack/test-issue-771.sh, incubator/hnc/internal/reconcilers/object.go
See issue #771. The CannotUpdate condition wasn't being cleared, since
conditions are indexed on the source object, but if the source object is
deleted and the propagated object (and its inheritedFrom label) was
never saved to the apiserver, we have no way to look up the condition by
the source object. This change simply looks through *all* conditions on
the same namespace as the missing object and removes the appropriate
ones; see the comments for more details.
This change also improves the logging for objects so that every action
(create, update or delete) is logged, as are the reasons for enqueuing
other objects or HCs for reconciliation. This should make postmortems
easier.
Tested: new testing script (hack/test-issue-771.sh) fails without this
fix and passes with it. Existing test …
=> Removes CannotUpdate when source object deleted

incubator/hnc/hack/test-delete-hc-crd.sh, incubator/hnc/internal/reconcilers/hierarchy_config.go
This change ensures that if the HierarchyConfig CRD is deleted before
the HNC pod, it will not delete the propagated objects. This reduces the
surprises when uninstalling HNC.
Tested: verified by hand that I can still delete the HC and this has the
effect of resetting the parent, and that cascading deletion still works.
Wrote a new test that verifies that the objects are not deleted after
five seconds, and verified that this test fails on HEAD but passes with
this patch.
=> Don't unpropagate objects after CRDs are deleted

incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hierarchy_test.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go
Part of #763 
Add additional restrictions in admission controllers to deny:
1. Create namespace with existing name in external hierarchy;
2. Update namespace to add "managedBy: other" annotation on namespace
with parent;
3. Make any changes to HierarchyConfiguration in external namespace.
Tested manually on a GKE cluster and by "make test" with new test cases.
=> Update admission controllers for external hierarchy

incubator/hnc/cmd/manager/main.go
The Stackdriver exporter shouldn't block HNC from starting; log any
error but ignore it and keep going. Also, ensure that we can display
startup logs that are generated before the manager starts.
Tested: HNC now works in Kind again, but is still exporting metrics to
SD on GKE. Startup logs are now showing up throughout the startup
process.
Fixes #770 
Fixes #777
=> [HNC v0.4] Make Stackdriver optional and fix startup logs

incubator/hnc/cmd/manager/main.go
The Stackdriver exporter shouldn't block HNC from starting; log any
error but ignore it and keep going. Also, ensure that we can display
startup logs that are generated before the manager starts.
Tested: HNC now works in Kind again, but is still exporting metrics to
SD on GKE. Startup logs are now showing up throughout the startup
process.
=> Make Stackdriver optional and fix startup logs

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/validators/anchor_test.go
Update the AllowsCascadingDelete() function in the forest to allow it if
any ancestor allows instead of looking up until the first full
namespace.
Tested by a new test case in anchor validator. It failed before the
change in the forest and passed afterwards.
Fixes #730
=> Allow cascadingDelete if any ancestor allows

incubator/hnc/hack/test-issue-716-full.sh, incubator/hnc/hack/test-issue-716-leafsub.sh, incubator/hnc/hack/test-issue-716-nonleafsub.sh, incubator/hnc/internal/forest/namespacestructure.go, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go
Update anchor reconciler and webhook to allow deleting leaf subnamespace
even when allowCascadingDelete is not set.
Tested by three test-issue-716.sh files and new test cases in anchor
validator that the test only passed after the change.
Fixes #716
=> Make leaf subnamespace deletion easier

incubator/virtualcluster/pkg/syncer/cluster/cluster.go, incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/controller.go, incubator/virtualcluster/pkg/syncer/resources/service/uws.go
In vc, the tenant service and super master service have different cluster ips since the cluster ip allocations are done by separate service controllers in tenant master and super master individually. The Pods can use super master cluster ip to access service or other Pod without any problem. But tenant dns cannot translate service dnsname to super master cluster ip since it can only see  the tenant master cluster ip. 
This change is the first step towards resolving the problem. The syncer now will populate the super master service cluster ip in the annotation of the tenant service object. Other components now can get the super master cluster IP from tenant perspective if it is needed.
=> [VC] Back populate super master clusterIP to tenant service object

incubator/virtualcluster/README.md, incubator/virtualcluster/config/sampleswithspec/coredns.yaml, incubator/virtualcluster/doc/tenant-dns.md, incubator/virtualcluster/pkg/syncer/conversion/mutate.go
This change adds document to explain how to customize coredns to provide super master cluster IP translation for tenant service domain name.
=> [VC] Add document for tenant dns support

incubator/virtualcluster/cmd/syncer/app/config/config.go, incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml, incubator/virtualcluster/pkg/syncer/metrics/metrics.go, incubator/virtualcluster/pkg/syncer/syncer.go
```
[root@vm virtualcluster]# k describe vc -n tenant1admin   vc-sample-1
Name:         vc-sample-1
Namespace:    tenant1admin
Labels:       controller-tools.k8s.io=1.0
Annotations:  <none>
API Version:  tenancy.x-k8s.io/v1alpha1
Kind:         VirtualCluster
Metadata:
Creation Timestamp:  2020-06-02T03:25:27Z
Finalizers:
virtualcluster.finalizer.native
Generation:        4
Resource Version:  2301078
Self Link:         /apis/tenancy.x-k8s.io/v1alpha1/namespaces/tenant1admin/virtualclusters/vc-sample-1
UID:               b43b5578-a480-11ea-8ccc-525400c042d5
Spec:
Cluster Domain:        cluster.local
Cluster Version Name:  cv-sample-np
Opaque Meta Prefixes:
tenancy.x-k8s.io
a.b
Pki Expire Days:  365
Transparent Meta Prefixes:
k8s.net.status
Status:
Conditions:
Last Transition Time: …
```
=> [VC] vc health checker, output in metric and event

benchmarks/kubectl-mtb/Makefile, benchmarks/kubectl-mtb/docs/main.go, benchmarks/kubectl-mtb/go.mod, benchmarks/kubectl-mtb/go.sum, benchmarks/kubectl-mtb/pkg/benchmark/benchmark.go, benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md, benchmarks/kubectl-mtb/test/constants.go, benchmarks/kubectl-mtb/test/util/util.go
=> Added README generator

incubator/hnc/hack/test-issue-797-leaf.sh, incubator/hnc/hack/test-issue-797-non-leaf.sh, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go
Allow removing bad subns anchor if the subnamespace already exists and
the parent doesn't match. The race condition could happen when two
parents both create the same subns the same time and the webhook is
bypassed because the forest is not updated after the first change. We
would always allow resolving a bad state.
Most importantly, make sure the subnamespace is not deleted with the
deletion of a bad anchor. Before this change, the subnamespace created
from a good anchor will also be deleted when deleting a bad anchor.
Tested by test-issue-797-leaf.sh and test-issue-797-non-leaf.sh, where
they disable the webhook first to generate the race condition in both a
leaf and non-leaf subnamespace and enable the webhook to test the
change. One unit test case is added to the anchor validator too. …
=> Enable removing bad subns anchors safely 

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/metrics/metrics.go, incubator/virtualcluster/pkg/syncer/resources/node/uws.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go, incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go
```
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="ConfigMap"} 3
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Endpoints"} 3
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Namespace"} 3
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Node"} 3
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Pod"} 4
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Secret"} 3
syncer_dws_operations_total{cluster="tenant1admin-e1e3e5-vc-sample-1",code="Error",resource="Service"} 3 …
```
=> [VC] add generic metric for syncer operations

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
apiVersion and kind fields in hncconfig.spec.types should never be
empty. It was a mistake to leave them omitempty. The current validating
webhook ensures the type generated from these two fields are valid,
therefore, empty fields are not allowed. Still we need to fix it in the
CRD.
Tested with the webhook disabled and it was still not allowed.
=> Set apiVersion and kind as required fields in hncconfig.spec.types

incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_loadbalancer.yaml, incubator/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml, incubator/virtualcluster/doc/demo.md
While the tenant controller is really useful it's an additional component that isn't technically necessary for using `virtualcluster`. This PR removes the steps to setup the `tenant1admin` namespace from the demo doc making it easier to get up and running.
=> [VC] Remove tenant-controller from the demo, and use default NS

incubator/virtualcluster/Makefile
As user may not set $GOBIN, `make manifests` may fail. This PR replaces $GOBIN with $GOPATH/bin in the Makefile.
=> [VC] replace GOBIN with GOPATH/bin

incubator/virtualcluster/config/crds/tenancy.x-k8s.io_virtualclusters.yaml, incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go, incubator/virtualcluster/pkg/controller/util/kube/util.go
Currently, to get the namespace for the control plane components you need to load all ns and either grep for the right one, pull this from the logs or load the conversion package and run the same code, this make VC's code base a dependency of any controller using the VC object.
This PR adds a typed `.status.clusterNamespace` to get the namespace where control planes are deployed into.
=> [VC]: Adding ClusterNamespace to VC.Status

incubator/hnc/e2e/tests/namespace_test.go
The prefix on test namespace was missing so the test was failing.
Tested by running:
make kind-reset
make kind-deploy
k delete validatingwebhookconfigurations.admissionregistration.k8s.io hnc-validating-webhook-configuration
go test ./e2e/...
All the e2e test passed now. 
Part of #785
=> Fix the error in e2e test due to the prefix change

incubator/hnc/config/default/manager_auth_proxy_patch.yaml, incubator/hnc/config/manager/manager.yaml
The auth proxy patch used to add the address for the metrics server,
which meant that the patch used to have to include _all_ the args
(kustomize can't modify a single item in a list, it can only replace the
entire list). However, it doesn't hurt us to pass the metrics address in
the base config for the manager (we're passing in the default value
anyway) and it makes the configs much nicer to _only_ have the auth
proxy config in the auth proxy patch.
Also added a variety of comments.
Tested: verified that other than reordering a few lines, the generated
hnc-manager.yaml manifest file is identical before and after this
change.
=> Move manager args to config/manager

incubator/hnc/config/manager/manager.yaml, incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
See #765. If a mounted secret changes _after_ a pod is started, it can
take a fairly long time (~60s) for the kubelet to notice the change and
project the new secret to the pod. Since our internal cert manager
writes a secret but then needs to wait for it to become available as a
file, this leads to a poor onboarding experience with HNC.
This change introduces a flag that exits the process as soon as the
internal cert manager changes a secret, which should only occur on
initial installation of HNC or every ten years (!). The restart time
takes <5s so this is overall a much better experience.
Tested: without changing the flags in the default manifest, observed no
change when HNC is installed for the first time (i.e. from the first log
message to when the HNCConfiguration is first …
=> Restart the pod if certs change

incubator/hnc/api/v1alpha1/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/hack/test-delete-hc-and-anchor-crd.sh, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/setup.go
See #824. When the CRDs are being deleted, we need to continue
reconciling the CRs until they're gone in order to ensure that any
finalizers on the CRs are removed.
Tested: new test script usually fails without this fix, but reliably
passes with it. Observed the new log messages working as expected while
running the script. For subnamespace anchors, tried removing the
CRD-checking code entirely and verified that
hack/test-delete-anchor-crd.sh failed, and then replaced it with the
current code (the shared isDeletingCRD function) and verified that it
passed again.
Fixes #824
=> Allow finalizers to be removed when deleting CRDs

incubator/hnc/docs/user-guide/how-to.md
Documented the new behaviour of subnamespace deletion, and added docs
about how to safely uninstall HNC starting with the CRDs.
=> Document changes in HNC v0.5

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/kustomization.yaml, incubator/hnc/config/crd/patches/singleton_validation_hierarchyconfiguration.yaml, incubator/hnc/config/crd/patches/singleton_validation_hncconfiguration.yaml, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/hnc_config_test.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go
Add CRD validation kustomization patchs to HierarchyConfiguration and
HNCConfiguration CRDs to validate the metadata.name to be the singleton.
Remove the "CritSingletonNameInvalid" condition and remove the
validating and condition setting code in the HNCConfig reconciler.
HNCConfig reconiler only reconciles the 'config' singleton. The
validation here is only to set the condition so it's safe to remove.
Remove the validating webhook on HNCConfig resource name too. There's no
need to keep the validating webhook as a second layer of protection
because the server-side validation is more reliable than webhooks since
webhooks can be disabled or bypassed if not running.
This change is also backward compatible since the old bad HNCConfig
resource will still have the obsolete condition on it. …
=> Use CRD validation to enforce singletons

incubator/hnc/README.md, incubator/hnc/docs/user-guide/README.md, incubator/hnc/docs/user-guide/how-to.md
Also update some minor out-of-date information in the README.
The updates are staged here:
* [README](https://github.com/adrianludwin/multi-tenancy/blob/docs-v0.5/incubator/hnc/README.md)
* [User guide front page](https://github.com/adrianludwin/multi-tenancy/blob/docs-v0.5/incubator/hnc/docs/user-guide/README.md)
* [User guide howto](https://github.com/adrianludwin/multi-tenancy/blob/docs-v0.5/incubator/hnc/docs/user-guide/how-to.md)
=> Update docs to refer to HNC v0.5

incubator/hnc/Makefile
Add a timer between deploy and go test to give webhook server enough
time to get ready. This change also invalidates the cached test results
before running the e2e test. Without 'go clean -testcache' it will always 
output the cached test result instead of the real one.
Tested:
On a real cluster, run:
kubectl delete -f manifests/hnc-manager.yaml
make e2e-test
On kind, run:
make kind-reset
make local-e2e-test
Fix #825
=> Add timer for webhook server to get ready before test

incubator/hnc/Makefile
The user should be responsible to have the test cluster ready before
running the E2E test. It could be either a kind cluster or a real k8s
cluster.
Tested:
on a real cluster: make e2e-test
on a kind cluster: make local-e2e-test
=> Remove deploy before E2E test

incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
Restructures the object validation controller to prevent deletions. Also
simplifiest the logic by explicitly checking the operation
(create/update/delete) that we're trying to validated.
Tested: new unit tests; tried a variety of legal and illegal
modifications on GKE 1.16 and confirmed that everything passed or failed
as expected in included namespaces, and that every change (including
illegal ones) pass in the excluded namespace `kube-system`. Confirmed
log messages are always printed out on failure while successes are never
printed.
Fixes #854
=> Prevent deletion of propagated objects

incubator/hnc/hack/test-issue-797-leaf.sh, incubator/hnc/hack/test-issue-797-non-leaf.sh
Remove the `kubectl apply -f manifests/hnc-manager.yaml` in the e2e
test as a way to restore webhook. Instead, output the webhook manifest
into a file and later apply this file to restore the webhook. This makes
sure the webhook is the one used in the current deployment when the e2e
test is run.
Tested by running the script and the generated yaml file is deleted
after each test.
Fixes #846
=> Restore webhook in e2e test from the current manifest

incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Noticed that we have some spelling misspelled functions for mutating `etcd`, `apiserver` and `controllermanager`.
=> [VC] Fixing "complement" spelling funcs

incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go
Split handle() and checkForest() into smaller functions.
Tested manually and by `make test`.
Part of #847
=> Restructure handle() in the namespace validator

incubator/virtualcluster/cmd/vcctl/subcmd/create.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Use ClusterIP in the kubeconfig if it exists
Allow ClusterIP service type in vcctl
Create the apiserver-svc ahead of time to add ClusterIP to PKI.
=> Support using ClusterIP for the API Server service

incubator/virtualcluster/config/setup/all_in_one.yaml
Without adding nodes/proxy, vn-agent cannot get/create proxy requets to the kubelet:
Error from server (Forbidden): Forbidden (user=vn-agent, verb=get, resource=nodes, subresource=proxy) ( pods/log net-tools)
=> Add nodes/proxy to vn-agent RBAC

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go
Since we allow changes to the subnamespaceOf annotation on subnamespace
as an escape hatch and there's a scenario of recovering from CRD
deletion, this commit makes it easier to delete a subnamespace, but only
when the parent or the anchor is missing. If the anchor is ok (state),
we still don't allow direct deletion of a subnamespace and only allows
deletion from the anchor.
Tested with new unit test cases and manually before and after.
Fixes #847
=> Allow subnamespace deletion if parent/anchor is missing

incubator/virtualcluster/go.mod, incubator/virtualcluster/go.sum, incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/test/e2e/e2e.go, incubator/virtualcluster/test/e2e/e2e_test.go, incubator/virtualcluster/test/e2e/framework/cleanup.go, incubator/virtualcluster/test/e2e/framework/clusterversion/create.go, incubator/virtualcluster/test/e2e/framework/clusterversion/delete.go, incubator/virtualcluster/test/e2e/framework/framework.go, incubator/virtualcluster/test/e2e/framework/text_context.go, incubator/virtualcluster/test/e2e/framework/util.go, incubator/virtualcluster/test/e2e/framework/vc.go, incubator/virtualcluster/test/e2e/framework/virtualcluster/wait.go, incubator/virtualcluster/test/e2e/multi-tenancy/framework.go, incubator/virtualcluster/test/e2e/multi-tenancy/virtual_cluster.go
1. setup e2e testing framework
2. e2e test case: create and remove vc
how to run 
```
[root@vm virtualcluster]# KUBECONFIG=/root/.kube/config  go test ./test/e2e/ -timeout 60m -v
=== RUN   TestE2E
I0713 06:36:30.133191   20074 e2e.go:59] Starting e2e run "8d1e8f15-f4e8-40c7-8b38-d63bfc6e41e8" on Ginkgo node 1
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1594622190 - Will randomize all specs
Will run 1 of 1 specs
[sig-multi-tenancy] VirtualCluster [virtualcluster] VirtualCluster LifeCycle
should be created and removed
/root/go/src/sigs.k8s.io/multi-tenancy/incubator/virtualcluster/test/e2e/multi-tenancy/virtual_cluster.go:55
[BeforeEach] [sig-multi-tenancy] VirtualCluster …
```
=> [VC] setup e2e testing framework

incubator/hnc/e2e/tests/delete_crd_test.go
If HNC is broken and cannot be repaired, log loud warnings to the user that any test after this could fail because of broken hnc.
Tested: 'make e2e-test' with invalid HNC_REPAIR path
Fix #881
=> Warn the testers if HNC cannot be repaired

incubator/hnc/e2e/tests/delete_crd_test.go
Translate test-delete-hc-crd.sh to delete_crd_test.go. Move hnc path
check to BeforeEach() to avoid repeated checks in each It block.
Tested: 'make e2e-test' with and without HNC_REPAIR
=> Add delete-hc-crd test to e2e test suite

incubator/hnc/Makefile
If you have any subnamespaces, simply saying `kubectl delete -f
manifests/hnc-manager.yaml` will not work, since the deployment will be
deleted before the subnamespace finalizers are removed. This change
addes a new `make undeploy` target that removes the CRDs _first_, and
only later deletes the rest of HNC. It's a bit hacky and produces a few
spurious error messages (since we try to delete the CRDs twice), but it
works.
Also removes the unused `deploy-cm` target that used to install
cert-manager, but this is no longer a dependency of HNC.
Tested: tested locally with and without subnamespaces; this robustly
deletes HNC.
=> Make it easier to uninstall HNC

incubator/hnc/internal/validators/object.go
See #688 and #889 - validators need to be able to handle that OldObject
might not be populated in K8s 1.14
Tested: can delete an empty (!) subnamespace in 1.14 with this change,
while it hangs forever and prints out error messages from the object
validators without this change. See #889 for more information.
Fixes #889
=> Unbreak object validator on 1.14

incubator/hnc/Makefile
The current HNC image name is hnc/controller, which is kind of silly
because the "c" in "HNC" already stands for "controller," and also
because some image registries (e.g. Docker) don't allow paths within
image names. This change modifies the default (and official) image name
to be hnc-manager, which aligns with the existing manifest file name of
hnc-manager.yaml. The change should be invisible to almost all users.
Note that if you modify the default via HNC_IMG while calling `make`,
the manifest file will also change. I think this is a feature, not a bug
- the manifest file with a given name will always refer to the image of
the same name.
Tested: deployed locally
=> Change HNC image name to hnc-manager

incubator/hnc/e2e/tests/delete_crd_test.go, incubator/hnc/e2e/tests/namespace_test.go, incubator/hnc/e2e/tests/subnamespace_test.go
Clean namespaces in BeforeEach() so that if any previous test failed to
clean up, current test will not be affected
=> Fix BeforeEach()

incubator/hnc/config/crd/patches/singleton_validation_hierarchyconfiguration.yaml, incubator/hnc/config/crd/patches/singleton_validation_hncconfiguration.yaml
As suggested by API reviewers, the enum validation produces a nicer
error message than patterns.
Tested by applying wrong names and got nicer message:
Unsupported value: "wconfig": supported values: "hierarchy"
Part of #868
=> Replace pattern with enum to enforce singleton

incubator/hnc/api/v1alpha1/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go
Add schema validation and remove the mode validation in HNCConfig
validator.
Tested with an obsolete existing HNCConfig resource with unknown modes
in the spec. Changes to the config is not allowed until the unknown
modes are fixed.
The validator test was failed before removing the test case.
Fix #899 
Part of #868
=> Use enum schema validation for HNCConfig spec modes

incubator/hnc/internal/validators/hncconfig.go
Currently, the hncconfig validator validate types by making a Get() call
using the controller-runtime client to see if the type exists from the
error types returned. This is indirect and error-prone when the error
types returned fron controller-runtime change.
This commit uses the client-go discovery client to look for a matching
type.
Tested manually that the cannot set-type issue is fixed and requests
with incorrect GVK are still denied.
Fixes #904
=> Use discovery to validate types in hncconfig

incubator/hnc/e2e/tests/issues_test.go
CritParentMissing condition should appear when the parent namespace is
deleted, and we should be able to delete a namespace with CritParent
Missing condition.
=>  Add test for CritParentMissing condition

incubator/hnc/e2e/tests/issues_test.go
A parent namespace without allowCascadingDelete should not be deleted. A
leaf namespace without allowCascadingDelete should be able to be
deleted.
=> Add test for deleting leaf namespace

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/conversion/helper_test.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
It is still possible that volumeMount name is duplicated with a secretName in the Volume while the Volume.Name does not match. This may happen if the Pod volume mount yaml is manually created. For example, 
```
volumeMounts:
- mountPath: /var/run/secrets/kubernetes.io/serviceaccount
name: token-B
- mountPath: /var/run/foo
name: token-A 
volumes:
- name: token-B
secret:
defaultMode: 420
secretName: token-A
- name: token-A
hostPath: /
```
This change makes sure the Pod volumeMount name is changed only when the corresponding volume is a secret volume whose name needs to be changed.
This change also removes the LabelServiceAccountUID constant which is not used any more.
=> [VC] Make sure VolumeMount is a secret volume before mutation

incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/e2e_test.go, incubator/hnc/test/e2e/issues_test.go, incubator/hnc/test/e2e/namespace_test.go, incubator/hnc/test/e2e/subnamespace_test.go
Rename the package name from 'test' to 'e2e' for better naming convention
=> Rename the package name from 'test' to 'e2e' 

benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
=> [MTB] changed flag name -t to --as

incubator/hnc/test/e2e/e2e_test.go, incubator/hnc/test/e2e/issues_test.go
Change the mustNotRun() function to use Eventually() so that we get
stable test result. Add sleep time after create subnamespace so that the
anchor is ready before test. Change the default wait time in mustRun()
and mustNotRun() to 5 seconds because deleting a subnamespace takes a
while.
Fix #950
=> Fix the flaky test for #716

incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/service/dws.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
Nowadays, syncer will add tenancy.x-k8s.io/cluster to object annotations to distinguish which vc this object belongs to. But the annotation is not convenient in real product because the cluster id is generated by vc-manager. The cluster id's format is ${namespace}-${uuid}-${vc-name}, where user can't get uuid without access k8s super master. 
In real product system, there are always many modules and not all modules need to access k8s. For example, module A deals with users order and pass a vcname to the k8s; module B collects pods information and module C get order information from module A and pods information from module B. Without vcname in pod metadata, module C can't match module A's information with module B unless module C get the vcname and cluster id mapping from super k8s.
In …
=> add vcname to metadata

incubator/hnc/pkg/testutils/testutils.go
When using this package in an internal (non-OSS) test, I discovered that
some commands I was calling required args with spaces - e.g., args that
would typically be surrounded by double-quotes in a bash shell. This
change solved my problem by allowing me to add double-quotes around an
arg to RunCommand (or any of the other Run functions) which disables
string splitting.
Tested: all HNC e2e tests still pass; my internal test can call commands
with spaces in the args.
=> Support args with spaces in them

incubator/hnc/internal/reconcilers/hierarchy_config_test.go
This bug is a warning of converting integer to a string of rune instead
of digits. This warning is introduced in Go 1.15. See https://blog.golang.org/go1.15-proposals
and specifically golang/go#32479.
Tested by make test and make deploy.
Fix #975
=> Make it work with Go 1.15

incubator/virtualcluster/pkg/syncer/resources/node/uws.go
```
WARNING: DATA RACE
Write at 0x00c0003c1b00 by goroutine 71:
runtime.mapdelete_faststr()
/usr/local/go/src/runtime/map_faststr.go:297 +0x0
sigs.k8s.io/multi-tenancy/incubator/virtualcluster/pkg/syncer/resources/node.(*controller).updateClusterNodeStatus()
/Users/qinnzhuang/vmshare/go/src/sigs.k8s.io/multi-tenancy/incubator/virtualcluster/pkg/syncer/resources/node/uws.go:91 +0x73a
Previous read at 0x00c0003c1b00 by goroutine 69:
runtime.mapiternext()
/usr/local/go/src/runtime/map.go:853 +0x0
sigs.k8s.io/multi-tenancy/incubator/virtualcluster/pkg/syncer/resources/node.(*controller).BackPopulate()
/Users/qinnzhuang/vmshare/go/src/sigs.k8s.io/multi-tenancy/incubator/virtualcluster/pkg/syncer/resources/node/uws.go:64 +0x40e …
```
=> [VC] fix map data race in node uws

incubator/virtualcluster/cmd/manager/main.go, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml, incubator/virtualcluster/config/setup/all_in_one.yaml, incubator/virtualcluster/go.sum, incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_webhook.go, incubator/virtualcluster/pkg/controller/constants/constants.go, incubator/virtualcluster/pkg/webhook/add_virtualcluster.go, incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go, incubator/virtualcluster/pkg/webhook/webhook.go
1. add the webhook framework for virtualcluster based on the
controller-runtime webhook library
2. implement the functionality of automatically generating the webhook
service/validatingwebhookconfiguration
3. implement the functionality of automatically generating webhook serving
certificate through the CSR
4. implement the validateUpdate function that forbids virtualcluster.status.phase to be set o empty
5. other minor changes:
a. fix the clusterversion_v1_nodeport.yaml to adapt the new
clusterversion crd generated by controller-runtime @v0.4.0
b. to enable webhook server, add new rabc rules and env to all_in_one.yaml
=> [VC] Feature: implement the webhook framework for VC

incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go
after submitting webhook csr request, will wait 2 seconds for it to be signed
=> [VC] Bug: add timeout for apiserver to sign the vc webhook CSR

incubator/hnc/cmd/manager/main.go, incubator/hnc/internal/reconcilers/crd_removeversion.go, incubator/hnc/internal/reconcilers/setup.go, incubator/hnc/internal/reconcilers/suite_test.go
Add a reconciler to watch for HNC CRDs to remove v1alpha1 from CRD
status.storedVersions. Start this reconciler with other reconcilers in
main.go but exclude it in integration tests.
Tested manually by installing HNC v0.5, applying v1alpha1 resources in
config/sample/v1alpha1_anchor.yaml and then deploy the change. The
v1alpah1 was removed from the CRD status.storedVersions.
Next PR will automate this into an e2e test for the API conversion.
Fixes #954 
Part of #868
=> Remove v1alpha1 from CRD status.storedVersions

incubator/virtualcluster/OWNERS
As discussed with @Fei-Guo today this PR add @christopherhein to the reviewers for virtualcluster.
=> Adding christopherhein to virtualcluster OWNERS/reviewers

incubator/hnc/Makefile, incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/conversion/conversion_test.go
The test installs HNC v1alpha1 first and creates v1alpha1 resources
both directly and by kubectl-hns plugin. Verify the CRD versions,
kubectl plugin and HNC behaviors are as expected in v1alpha1.
Then upgrade HNC and kubectl plugin to v1alpha2. Verify everything
mentioned above also works fine in v1alpha2.
Before and after the test, the namespaces and HNC deployment or
resources are all cleaned up.
Change some `TryRunQuietly()` function in testutils package to
`TryRun()` so that if there's a failed test, we can see the output.
Tested by `make conversion-test`. The verification of v1alpha1 to be
gone in the CRD status.storedVersions failed in the current HEAD but
passed on top of the change to remove v1alpha1 from storedVersions at
https://github.com/kubernetes-sigs/multi-tenancy/pull/988. …
=> Add e2e test suite for API conversion

README.md, RELEASE.md, docs/links.md
Changes:
* Provide up-front links to our biweekly meetings (was missing before)
* Highlight the four active projects
* Clean up docs/links.md to highlight more recent content
* Removed redundant "releases" doc
=> Reworked landing and docs pages

incubator/hnc/README.md
Change HNC from "alpha" to "pre-GA," clarify the roadmap, be a bit more
positive about getting involved and add vendor installation links.
=> Soften pre-GA warnings

incubator/hnc/Makefile, incubator/hnc/cloudbuild.yaml
The makefile recently changed the name of the released image, but we
didn't update Cloud Build to match; this commit fixes that. It also
allows CB to pull from a different repo to make testing release changes
easier.
Tested: created a fake release and built from
gihub.com/adrianludwin/multi-tenancy using the new override.
=> Line up Cloud Build with makefile

incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
There is no **k8s.io/api/priority/v1** in v0.18.6 or master。
=> fix(test): no priotiry/v1 in k8s.io/api

incubator/hnc/cloudbuild.yaml
Related issue: https://github.com/kubernetes-sigs/multi-tenancy/issues/1029
This PR adds support for building and uploading the plugin for the darwin (Mac) environment. I just follow the current way which is done by Linux build. This changes binary name of release so we need to update the guide as well. If the current way is ok then let me update the guide as well.
=> HNC: Add support for plugin build for darwin amd64

incubator/hnc/api/v1alpha2/subnamespace_anchor.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml, incubator/hnc/test/conversion/conversion_test.go
Tested by 'make test-conversion'. It failed before and passed after
changing the v1alpha2 status check from 'ok' to 'Ok'.
Part of #868
=> Update v1alpah2 SubnamespaceAnchor status to camel case

incubator/hnc/config/webhook/kustomization.yaml, incubator/hnc/config/webhook/webhook_patch.yaml
Context: https://github.com/kubernetes-sigs/multi-tenancy/issues/1023
Add `timeoutSeconds` patch for webhook configuration. 
Currently, `controller-tools` does not support `timetouSeconds` marker ([I'm sending patches for it](https://github.com/kubernetes-sigs/controller-tools/pull/473)). So just add kustomize patches for it. 
Executing the following command (which is executed in `cloudbuild.yaml`) on my local PC, 
```
cd multi-tenancy/incubator/hnc
mkdir out
cd out
touch kustomization.yaml
kustomize edit add resource ../config/default
kustomize build . -o ./hnc-manager.yaml
```
[This](https://gist.github.com/tcnksm/1bfb91d412c7635315559b3f318806fb) is the output of `hnc-manager.yaml`. You can see `timeoutSecond` is added.
=> Add timeoutSeconds patch for webhook configuration

incubator/hnc/internal/reconcilers/hierarchy_config_test.go
This is a cherrypick of #976 . Tested by `make test`. Original description follows.
---
This bug is a warning of converting integer to a string of rune instead
of digits. This warning is introduced in Go 1.15. See https://blog.golang.org/go1.15-proposals
and specifically https://github.com/golang/go/issues/32479.
Tested by make test and make deploy.
=> Cherrypick: Make it work with Go 1.15

incubator/hnc/Makefile, incubator/hnc/cloudbuild.yaml, incubator/hnc/internal/kubectl/root.go, incubator/hnc/internal/kubectl/version.go, incubator/hnc/internal/version/version.go
Related: https://github.com/kubernetes-sigs/multi-tenancy/issues/861
Add `cobra.Command.Version`. This enables the plugin to have `--version` option flag to show its version. I'm not sure the way to embed the version string is what you expect.  
I've build it on local and tried its output,
```bash
$ go build -ldflags="-X sigs.k8s.io/multi-tenancy/incubator/hnc/internal/version.Version=v0.5.2" -o kubectl-hns  cmd/kubectl/main.go
```
```bash
$ ./kubectl-hns version
kubectl-hns version v0.5.2
```
=> Support --version option for hnc plugin

incubator/hnc/config/webhook/webhook_patch.yaml
See issue #1027. To support server-side dry-run, all admission webhooks
must state that they do not have any side effects. Our version of
controller-gen doesn't include the sideEffects marker so I added them as
a kustomization patch.
I'll port this to the master branch after this change.
Tested: server-side dry-run fails on a pod creation in Kind 1.18 without
this fix and passes with it. GKE doesn't have 1.18 yet so I couldn't
test it there, but I also tested it on GKE 1.15 (the oldest currently
supported version) to ensure that it had no ill effects, and all e2e
tests work fine on both Kind 1.18 and GKE 1.15.
=> Support server-side dry run

incubator/hnc/internal/kubectl/tree.go, incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/demo_test.go, incubator/hnc/test/e2e/issues_test.go
I've noticed that a bunch of e2e tests are failing on master. This
change makes a few improvements:
* Fix a functional bug in the plugin that confused the text displayed
_about_ a namespace with the actual namespace name.
* testutils.TryRun now prints out more informative log messages and
returns a more informative error.
* Increased the default timeout from 1s to 2s in issues_test
* Update demo_test to include the now-expected output about
subnamespaces in `kubectl hns tree`.
Tested: fewer tests fail now than before.
=> Improve e2e test pass rate and infra

incubator/hnc/api/v1alpha2/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/test/conversion/conversion_test.go, incubator/hnc/test/e2e/demo_test.go
Update v1alpha2 HNCConfig sync modes to camel case, e.g. 'propagate' to
'Propagate'.
In addition, add e2e test case to make sure v1alpha2 HNCConfig
reconciler is working as expected. Verify v1alpha1 'propagate' is not
treated as unknown and converted to v1alpha2 'Ignore'. Verify object
propagation is still working after conversion. Verify all modes are
converted correctly.
Update 2 HNC e2e test cases in demo_test to use the new camel-case
modes.
Tested by 'make test-conversion'. When the old cached image was used,
v1alpha1 'propagate' was converted to v1alpha2 'Ignore'. After the image
was re-pulled, it was converted to v1alpha2 'Propagate' correctly.
Also passed the focused tests on the 2 HNC e2e test cases.
See #1025 about the cached image issue.
Part of #868
=> Update v1alpha2 HNCConfig modes to camel case

incubator/hnc/Makefile, incubator/hnc/cloudbuild.yaml, incubator/hnc/docs/releasing.md, incubator/hnc/hack/README.md, incubator/hnc/hack/ci-test.sh
This commit makes two significant changes:
* Includes the kustomize tool so that we don't need to either fetch it
from the internet or rely on one being installed locally.
* Replaces portions of the Cloud Build process with the equivalent steps
from the Makefile so they can't get out of sync.
As a side effect, this required a bit of refactoring in the makefile,
and I've moved some lines around to be more closely located with the
relevant recipes.
I tried removing `kubebuilder` (I thought we just needed controller-gen)
but it contains elements required by Ginkgo. Since it's rather large
(>50MB) and doesn't affect the correctness of the binaries as they're
built (only tested), I decided not to check it in. I did upgrade the
version we use from a 2.0 alpha to the latest release (as of Aug …
=> More hermetic, unified builds

incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/demo_test.go, incubator/hnc/test/e2e/e2e_test.go, incubator/hnc/test/e2e/issues_test.go
Extend the timeout limit for some operations to make them more stable.
Checks that the previous operation finishes before proceeding to the
next one, otherwise some of them will be flaky. Warns the user that the
network policy has to be enabled for the test to pass.
=> Fix some flaky testes

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/apis/config/types.go
The purpose of this PR is to make the syncer framework more generic so it can be reused by users that need to support their own CRDs. This change passes rest config of super master in SyncerConfiguration struct. So users can construct/handle their CRD client to perform the DWS/UWS sync.
=> add rest config into SyncerConfiguration

incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go
For source objects with a conflicting source in the ancestors, treat
them as propagated objects and overwrite them with the source in the
ancestor. See http://bit.ly/hnc-propagation-conflict
Tested by `make test` with a new integration test case.
Part of #1076
=> Update object reconciler to overwrite conflicting source

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/syncer/resources/ingress/checker.go, incubator/virtualcluster/pkg/syncer/resources/ingress/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go, incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go, incubator/virtualcluster/pkg/syncer/resources/ingress/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/ingress/uws.go, incubator/virtualcluster/pkg/syncer/resources/ingress/uws_test.go, incubator/virtualcluster/pkg/syncer/resources/register.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
This loosely implements uws and dws syncing for `ingress` resources within the sync controller. While it's not mutating the ingress now I've implemented this so that it could easily be added.
Let me know if you think this should be considered under the additional syncer resources.
Closes: #1062
=> vc: adding ingress resource syncing

incubator/hnc/internal/reconcilers/object_test.go
Update the 5-millisecond sleep to 500-millisecond before detecting
object overwriting for object reconciler test.
This should fix the flaky test on Prow presubmit.
Tested by 'make test'. It was not flaky before and after the change
locally but may help for Prow.
=> Fix a flaky test for Prow specifically

incubator/virtualcluster/pkg/syncer/conversion/helper.go
Resource creation time is used by performance monitoring module in k8s to present end to end resource creation latency. In virtual cluster case, resource creation time should be counted when tenant initiate the resource creation request in virtual cluster. Performing reset during super cluster syncing destroys useful metrics.
=> Remove resource creation time rest.

incubator/hnc/go.mod, incubator/hnc/go.sum, incubator/hnc/vendor/modules.txt, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/conv.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/internal/yaml/convert.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/internal/yaml/nested.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go, incubator/hnc/vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Upgrade controller-tools to v0.2.8 where kubebuilder:unservedversion
marker is landed. See https://github.com/kubernetes-sigs/controller-tools/issues/462
Tested by make test.
Part of #1035
=> Upgrade controller-tools to enable unservedversion

incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
Update object webhook to deny creating an object if an object with the
same name and type already exits in the descendants, and the type has
'Propagate' syncMode. Add new a new test case.
Tested manually on GKE cluster and by 'make test'.
The webhook output is like this:
```
Error from server (Conflict): admission webhook "objects.hnc.x-k8s.io" denied the request: Cannot create /v1, Kind=Secret 'my-creds' in namespace 'acme-org' because it would overwrite objects in the following descendant namespace(s): [team-a team-b]. Choose a different name for the object, or remove the conflicting objects from these namespaces.
```
Fixes #1079 
Part of #1076
=> Update object webhook to deny creating conflict object

incubator/hnc/Makefile
Make target `kind-deploy` failing due to empty PROJECT_ID set for kind deployment.
This change skips the PROJECT_ID value if it is not set
Fixes #1084
=> Fix make target kind-deploy for KIND environment

incubator/virtualcluster/Makefile
Very small change! I was trying to do some local development, and noticed in the build script we can set the `VC_DOCKER_REGISTRY` variable when building the images.
I added this functionality to the Makefile as well to make pushing to a custom repo and testing very easy. It still defaults to `virtual cluster`
=> VC: Use optional env var for Docker registry in Makefile

incubator/hnc/internal/reconcilers/object.go, incubator/hnc/test/e2e/rolebinding_test.go
RoleBindings can't have their Roles changed after they're created. If an RB was quickly delete and re-created in an ancestor namespace - fast enough that by the time that HNC notices, the new RB exists - HNC could see it as an update (not a delete + create) and attempt to update the RBs in all descendant namespaces, and this will fail. In order to handle this case, we try to delete and re-create the rolebinding instead.
Fix #798
=> Fix the Rolebinding update logic

incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
This test is expected to fail now, and pass when the exception is
implemented. We ignore this test for now with `PIt` block.
=> Add test for propagating object to selected namespaces

incubator/hnc/internal/forest/namespaceobjects.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hierarchy_test.go, incubator/hnc/internal/validators/object.go
Add an additional rule to make sure there's no potential object
overwriting in hierarchy changes. Format the webhook message to:
```
Cannot update hierarchy because it would overwrite the following object(s):
* Namespace "team-b": my-creds (/v1, Kind=Secret)
* Namespace "team-b": my-creds2 (/v1, Kind=Secret)
To fix this, please rename or remove the conflicting objects first.
```
Format the object webhook message to:
```
Cannot create "my-creds2" (/v1, Kind=Secret) in namespace "acme-org" because it would overwrite objects in the following descendant namespace(s):
* team-a
* team-b
To fix this, choose a different name for the object, or remove the conflicting objects from the above namespaces.
```
Tested manually on GKE cluster and by 'make test' with new test
cases.
Part of #1076
=> Update hc validator to check object conflicts

incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hierarchy_test.go
The bug was found when running e2e tests that the webhook got
INTERNAL_ERROR when setting a namespace as root. Fix it by checking if
the new parent is nil. If yes, early exit since it's impossible to
introduce new naming conflicts.
Add a new unit test case for it. The test failed before and passed after
the change.
Tested by make test and manually.
=> Fix a nil pointer issue in HC webhook when setting as root

incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go
This change incorporates
https://github.com/open-policy-agent/gatekeeper/pull/813 and
https://github.com/open-policy-agent/gatekeeper/pull/811 to allow HNC's
internal cert generator to work on K8s 1.19, which uses Go 1.15.
Tested: HNC cannot be installed on KIND 1.19 without this change, and
can successfully be installed and have all e2e test run with it.
=> Fix certs in K8s 1.19

incubator/hnc/cmd/manager/main.go, incubator/hnc/go.mod, incubator/hnc/go.sum, incubator/hnc/vendor/modules.txt, incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go, incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go, incubator/hnc/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
This essentially reverts #1087, which breaks HNC on new clusters that
haven't previously had HNC installed. It fixes the nondeterministic
crashing problem by patching in
https://github.com/kubernetes-sigs/controller-runtime/pull/1155, which
has been applied to controller-runtime 0.6.3 in @adrianludwin's repo.
This is a temporary hack and will be removed when controller-runtime
releases its own fix - likely 0.6.4.
Tested: with the reversion of #1087 (main.go), HNC can be installed on a
fresh cluster again but fails to start up ~50% of the time. With the fix
to controller-runtime, it passes on 20/20 startup attempts. Ran e2e
tests and got the same result as without this change (four failures).
=> Fix HNC startup issues

incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/test/e2e/issues_test.go
See issue #1130. The HNC object validator was preventing the K8s
namespace controller from cleaning out a namespace to allow it to be
deleted. This change lets HNC understand that when a namespace is being
deleted, we should ignore the subnamespaceOf annotation. This allows the
HierarchyConfiguration object to be reset to its initial state (like a
full namespace would when it's being deleted), orphaning the namespace
and allowing all its propagated objects to be removed.
Tested: added new tests and ran them multiple times while watching the
logs. The subnamespace test failed without this change and passed every
time with it, with the logs showing the expected behaviour.
Fixes #1130
=> Let subns with propagated objects be deleted

incubator/hnc/internal/forest/forest.go, incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/forest/namespaceobjects.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go, incubator/hnc/internal/validators/setup.go
Update forest field `sourceObjects` to store all the names of user-created
objects by GVK as long as there's an object reconciler for that GVK.
Change object reonciler behaviors dependent on the previous forest field
`originalObjects`, which only stores source objects for 'Propagate' types.
Add test cases for corner cases.
Add new hncconfig webhook rules and new test cases. Check if changing
type mode(s) to `Propagate` would cause overwriting source by looking
up the `objectNames` data. Deny the request and output all the conflicts
if it would cause overwriting.
Tested by "make test" and manually on a GKE cluster with multiple
objects with the same name in the same tree or different trees. Passed
all e2e tests too.
The webhook message would look like this:
```
Cannot update configuration …
```
=> Update hncconfig webhook to handle object overwriting and refactor forest `sourceObjects` field

incubator/hnc/internal/forest/namespaceobjects.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hierarchy_test.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
See issue at #1076 
The fix should include 4 changes, but we only include the first 2 fixes in this cherry-pick into HNC v0.5.
1. Object webhook (see #1079)
2. HierarchyConfiguration wehbook
3. Hncconfig webhook (too complicated to do a cherry-pick, see #1102)
4. HNC exceptions (not yet implemented, so irrelevant to v0.5)
Tested by `make test`
=> Cherrypick: Handle source object overwriting conflict

incubator/hnc/Makefile, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml
The Makefile wasn't correctly regenerating controller-gen when the
version in go.mod (and hence vendor/) was updated. This led to me
mistakenly submitting #1124. This change _always_ rebuilds
controller-gen from scratch to ensure that leftover tool binaries won't
cause more problems.
Tested: before this change, ran `make manifests` and observed that the
version of controller-gen (as seen by `--version`) didn't match the
version in go.mod. After this change, observed that the reported version
now matched that in go.mod and the CRD YAMLs were rebuilt. Installed
HNC and verified that it started up ok.
=> Ensure controller-gen is rebuilt properly

incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/test/e2e/issues_test.go
See issue #1149. This affects the ability to turn a subnamespace into a
full namespace. If you remove the subnamespaceOf annotation, move the
namespace to a new parent, and *then* clean up the anchor, everything's
ok. But if you delete the anchor _before_ moving the namespace, the
namespace gets deleted, which is clearly wrong.
This change is the minimal safe change needed to fix this in v0.5. In
v0.6, we should restructure these functions to be more heavily based on
the explicit state of the anchor, not the implied state.
Tested: new e2e test fails (hangs, actually) without this change and
passes with it. All e2e tests pass on GKE 1.17.
=> Don't delete subns if anchor has conflict

incubator/hnc/internal/reconcilers/object_test.go
This flaky test cannot be reproduced when `make test` for 10+ times.
Update the `Expect` to `Eventually` to make it less likely to fail.
Tested by 'make test'.
See failed Prow [log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_multi-tenancy/1144/pull-hnc-test/1309517615571406848).
=> Fix a very rare flaky test on Prow

incubator/virtualcluster/cmd/manager/main.go
Move healthz http server block before vc manager starts
=> Fix vc manager http server healthz can't start

incubator/hnc/api/v1alpha1/hierarchy_types_conversion.go, incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml, incubator/hnc/docs/user-guide/how-to.md, incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/kubectl/set.go, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/anchor_test.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go, incubator/hnc/test/conversion/conversion_test.go, incubator/hnc/test/e2e/issues_test.go
Use `allowCascadingDeletion` instead of `allowCascadingDelete` in
v1alpha2 HC schema. Update conversion test, integration test and e2e
tests.
Add a skipped (`PIt`) test case for #1155 . This test failed on both
master branch and this change, so it's not caused by this change. Added
the test so that the later fix can use `allowCascadingDeletion` directly.
Tested by `make test-conversion`, `make test` and `make test-e2e` (with
`FIt` on related tests only).
Fixes #1035 
Part of #868
=> Update v1alpha2 HC schema with allowCascadingDeletion

incubator/hnc/api/v1alpha1/hierarchy_types_conversion.go, incubator/hnc/api/v1alpha1/hnc_config_conversion.go, incubator/hnc/api/v1alpha1/subnamespace_anchor_conversion.go
While investigating another issue, I looked at the logs from the K8s
apiserver and observed that we were seeing tons of errors as the
apiserver asked HNC to convert the v1a2 objects back to v1a1 -
specifically, that their names has changed. I have no idea why K8s is
asking for these objects to be backconverted, but after glancing at the
K8s source code, I guessed that copying the object metadata would work
to fix the issue, and it did.
Tested: observed no more logspam from the apiserver
=> Create minimial v1a2 to v1a1 converters

incubator/hnc/README.md, incubator/hnc/docs/user-guide/how-to.md
Update all references to v0.5.3 and document the user-facing changes.
Staged at:
* https://github.com/adrianludwin/multi-tenancy/blob/docs-053/incubator/hnc/README.md
* https://github.com/adrianludwin/multi-tenancy/blob/docs-053/incubator/hnc/docs/user-guide/how-to.md
=> Update docs for v0.5.3

incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/test/e2e/issues_test.go
This PR includes two commits:
1. The master cherrypick of #1150
2. Addresse the TODOs that I didn't want to fix in v0.5.
Fixes #1149.
Tested: all e2e tests when run with #1160, #1162, #1163 and #1164.
=> Don't delete subns if anchor has conflict (master)

incubator/hnc/api/v1alpha2/subnamespace_anchor.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hierarchy_config_test.go, incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/conversion/conversion_test.go
Update the sub-namespace annotation into `subnamespace-of` from
`subnamespaceOf` in v1alpha2. Update the namespace annotation in the
hierarchyConfiguration reconciler.
Add documentation that `Ok` is the only good state of anchor.
Update conversion tests.
Update util funcs CleanupNamespace() and RecoverHNC() to report failure
in cleanup.
Tested by `make test-conversion`, `make test` and manually.
Part of #868
=> Update "subnamespace-of" sub-namespace annotation

incubator/hnc/internal/kubectl/configset.go, incubator/hnc/test/e2e/kubectl_test.go
If the user switch the propagation mode directly from 'Ignore' to
'Propagate', it will fail with an error message telling the user that a
'--force' flag is needed. '-f' is also supported as a shorthand.
=> Add '--force' flag when switching from 'Ignore' to 'Propagate' mode

incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/issues_test.go, incubator/hnc/test/e2e/subnamespace_test.go
Prior to this change, the failure messages from our current e2e and
conversion webhooks were very poor - they don't identify the line number
from the _test_ that causes a failure, since most of the failures are
hidden several levels deep in the testutils package. In addition, almost
no information is printed out about the command that caused the failure
\- you need to dig through the logs. Finally, many failures are printed
in unnecessarily verbose ways.
This change fixes all three problems, by using Gomega's WithOffset
functions to get the test line from the stack trace, using a custom
Gomega matcher to print out nicer information, and printint out the
failing command on failure. Take together, these three changes change
an error like this:
```
Expected success, but got an error: …
```
=> Improve test failure messages; fix some tests

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/api/v1alpha2/subnamespace_anchor.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/conversion/conversion_test.go
This change updates HNC to recognize the managed-by annotation, and
convert any existing managedBy annotation from v1alpha1 to the new name.
It also adds some minor cleanups to the conversion tests and makes the
CleanupNamespaces function a bit more robust to account for some errors
I saw before the new tests were working.
Tested: new conversion test; all existing conversion tests pass.
=> Switch to managed-by annotation

incubator/hnc/internal/reconcilers/hierarchy_config_test.go, incubator/hnc/internal/reconcilers/hnc_config_test.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/reconcilers/suite_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
The HNC Config tests were flaky when run in a loaded environment, such
as on Prow, and produced hard-to-reproduce errors. I was able to
reproduce them about 20% of the time using the `stress` utility to load
up my workstation.
The concrete proble I found was that the tests were not always waiting
for changes to the HNC config to be picked up - see my comments in #1170
for details. I've addressed this by adding a setTypeConfig function that
always waits for config changes to appear in the status before the test
can proceed.
I also added or fixed ...WithOffset() Gomega assertions now that I
actually understand how they work, and focused on never having any
_nested_ assertions since they make it impossible to get the correct
originating line number. I also changed some functions' names to …
=> Improve HNC Config test diagnosis/stability

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
When user set `{"propagate.hnc.x-k8s.io/treeSelect": "!baz"}`, HNC
should not propagate this object to `baz` namespace. This annotation
also supports multiple namespace select, which means if user set `{"propagate.hnc.x-k8s.io/treeSelect": "!baz, !bar"}`, HNC should not propagate this object to neither `baz` nor `bar`. These two cases are included in `object_test.go`.
When both `treeSelect` and `select` present, HNC will only propagate to
the namespace that matches both of the two selectors.
The test cases covers the following situations:
- select/treeSelect to one single namespace AND multiple namespaces
- when select AND treeSelect both exists
- when select/treeSelect is updated
I believe these cover all of the selector test cases
=> Implement selector when using treeSelect annotation

incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go, incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/demo_test.go
While running the e2e tests, the CleanupNamespace command was hanging
because we weren't allowing deletion of anchors in the Conflict state;
we were just checking whether the would-be subnamespace had the correct
parent, but not whether the subnamespace anchor was actually in the 'ok'
state. This was resulting in HNC blocking the deletion of a bad anchor,
which we should always allow (this should have been done as a part of
PR #1151).
I also made three minor fixes to the e2e tests themselves:
1. Turn propagation on for new types with the --force option
2. Skip the network policy demo if we detect that network policies
aren't enabled on the cluster.
3. Delete the webhook configs when HNC might be in a bad state so that
they don't try to block cleanup of namespaces.
Tested: the e2e tests …
=> Delete bad anchors and fix e2e tests

incubator/virtualcluster/cmd/kubectl-vc/create.go, incubator/virtualcluster/cmd/kubectl-vc/exec.go, incubator/virtualcluster/cmd/kubectl-vc/root.go, incubator/virtualcluster/cmd/kubectl-vc/util.go, incubator/virtualcluster/go.mod, incubator/virtualcluster/go.sum
```bash
[root@vm virtualcluster]# kubectl vc
VirtualCluster Command tool
Usage:
kubectl-vc [flags]
kubectl-vc [command]
Available Commands:
create      Create a new VirtualCluster
exec        Switch to virtualcluster workspace
help        Help about any command
Flags:
-h, --help      help for kubectl-vc
--version   version for kubectl-vc
Use "kubectl-vc [command] --help" for more information about a command.
[root@vm virtualcluster]# kubectl vc exec -h
Switch to virtualcluster workspace
Usage:
kubectl-vc exec VC_NAME [flags]
Examples:
kubectl vc exec -n foo bar
kubectl vc exec foo/bar
kubectl vc exec --kube-file-dir /path/to/file foo/bar
Flags:
-h, --help                   help for exec
--kube-file-dir string   The directory to place the kubeconfig of specific vc (default …
```
=> VC:  kubectl vc exec: switch workspace among virtualclusters

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go
If the noneSelector is set to true, the object should not br propagated
to any child namspaces regardless of other selectors
The test cases test the noneSelector by itself, noneSelector combined
with other selectors, and setting then resetting the noneSelector
=> Implement noneSelector and add test cases

incubator/hnc/api/v1alpha1/hnc_config_conversion.go, incubator/hnc/api/v1alpha2/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/internal/config/default_config.go, incubator/hnc/internal/kubectl/configdelete.go, incubator/hnc/internal/kubectl/configdescribe.go, incubator/hnc/internal/kubectl/configset.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/hnc_config_test.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/test/conversion/conversion_test.go, incubator/hnc/test/e2e/demo_test.go, incubator/hnc/test/e2e/kubectl_test.go
In v1alpha2, we will replace the `apiVersion` and `kind` fields in the
hncconfig spec with `group` and `resource` to use restmapper lookup to
see if the type exists and remove version in the spec.
Still keep the object reconcilers and in-memory forest to use GVK. In
HNCConfig reconciler and validator, always get the mapping from GR to
GVK first so it can check forest or create object reconcilers with GVK.
Add `version` field in the HNCConfig status to show users which version
is picked. Add `TypeNotFound` condition for HNCConfig when the type is
not found, which was previously reported with
`ObjectReconcilerCreationFailed`. `ObjectReconcilerCreationFailed` will
only be for errors happened when creating the reconciler.
Hack the CRD conversion with string manipulation from `apiVersion` to …
=> Update HNCConfig API with GR for restmapper lookup

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/internal/reconcilers/test_helpers_test.go, incubator/hnc/test/conversion/conversion_test.go, incubator/hnc/test/e2e/demo_test.go
Update the inheritedFrom label added to all propagated objects by HNC.
The object reconcilers don't need to update the label on each
propagated objects because they will be treated as conflicting source
and get overwritten.
Add conversion tests and some corner cases. Refactor some applying of
manifests.
Tested by 'make test', focused 'make test-e2e' and 'make
test-conversion' on the label change. Tested manually that after
upgrading, all the labels got overwritten with the new label.
Part of #868
=> Update "inheritedFrom" label to "inherited-from"

incubator/hnc/internal/pkg/selectors/selectors.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/validators/object.go
If the user input value for "propagate.hnc.x-k8s.io/select" can not be
parsed as a valid labelSelector, we will deny this operation.
Also moved all selector related functions into a package.
Tested:
```
$ k delete role test -n a;
k create role test -n a --verb=update --resource=deployments;
k annotate role test -n a "propagate.hnc.x-k8s.io/select"="cqoornttdrkjacuiqagaqottaprzpjzfjudvlqziugeywbzgbdfvcxcimwiecodcpehldykmrikoxixv"
role.rbac.authorization.k8s.io "test" deleted
role.rbac.authorization.k8s.io/test created
The request is invalid: : Invalid "propagate.hnc.x-k8s.io/select" value: cqoornttdrkjacuiqagaqottaprzpjzfjudvlqziugeywbzgbdfvcxcimwiecodcpehldykmrikoxixv, which can not be parsed as a labelSelector
$ k delete role test -n a;
k create role test -n a --verb=update …
```
=> Add validator check for 'select' annotation

incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/demo_test.go, incubator/hnc/test/e2e/issues_test.go
kubectl-hns was changed in #1184 but the e2e tests were still expecting
the old output; this change updates the e2e tests. In addition, #1171
moved object conditions to events, and those events included names from
an old ancestor, confusing the demo test that was expecting the old
ancestor to _not_ appear; this change fixes that too.
Tested: e2e tests failed but now pass
=> Fix e2e tests after conditions updates

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/test/e2e/issues_test.go
I wasn't able to get the original problem to reproduce itself, but I
added a log message and improve the test so that we can catch #1155 if
it ever reoccurs.
Tested: the newly enabled test passes with HNC as-is; if I break HNC to
manually re-enable allowCascadingDeletion, then the test fails as
expected. I also manually verified that the new log message is displayed
as expected.
Fixed #1155
=> Reenable test for #1155

incubator/hnc/api/v1alpha1/hnc_config_conversion.go, incubator/hnc/api/v1alpha2/hnc_config.go, incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml, incubator/hnc/internal/config/default_config.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/hnc_config_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/test/conversion/conversion_test.go
Removed the roles and rolebindings resources from the HNCConfig spec,
and only show them in the status.
Remove the RBAC validation in the validator and the default RBAC
configurtion in the HNCConfig reconciler.
Update validator unit tests, reconciler integration tests and conversion
tests.
Tested manually on GKE and by 'make test' and 'make test-conversion'.
Fixes #1213 
Part of #868
=> Omit enforced RBAC resources in the HNCConfig spec

incubator/hnc/internal/pkg/selectors/selectors.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
We check if the raw string input from user is a valid DNS label. If this
is a valid DNS label but couldn't be parsed as a selector for some
reason, we will show user that it's an internal error, so that user can
reach us for help. In theory this should never happen.
Tested:
```
$k delete role test -n a
k create role test -n a --verb=update --resource=deployments
k annotate role test -n a "propagate.hnc.x-k8s.io/treeSelect"="1234567890123456789012345678901234567890123456789012345678901234567890"
role.rbac.authorization.k8s.io "test" deleted
role.rbac.authorization.k8s.io/test created
Error from server (BadRequest): admission webhook "objects.hnc.x-k8s.io" denied the request: Invalid HNC "propagate.hnc.x-k8s.io/treeSelect" value: 12345678901234567890123456789012345678901234567890123456789012 …
```
=> Add validator check for `treeSelect`

incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/crd_removeversion.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/hnc_config_test.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/object.go, incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/demo_test.go
This change comes largely out of watching the TGIK HNC episode where the
user used the log messages to understand what HNC was doing, and I
realized the messages were spammy, unhelpful or misleading in many
cases. So this change tries to fix all those problems.
I closely watched the log messages while running the e2e tests and
either hid or fixed any messages that wouldn't appear to be at least
somewhat useful to an end user.
I also added a unique 64-bit reconcile ID to all log messages from all
reconcilers (except HNC Config, which is being modified in another PR so
we can come back to that). We previously did this only for the hierarchy
config reconciler; now we can track IDs for anchors and objects as well.
Finally, addressed #1220.
Tested: watched the logs as the e2e tests ran and was …
=> Improve log messages

incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/stats/metrics.go, incubator/hnc/internal/stats/stats.go
Signed-off-by: frbimo <fr.bimo@gmail.com>
fixes: #1158
This change adds an `overwritten_object` metric. 
Metrics will shows the total number of overwritten object on Propagate mode. 
Tested: 
directly inspected the /metrics endpoint on the HNC pod via curl. Double checked the metrics on prometheus stack using `serviceMonitor` by accessing prometheus UI. 
NB: scraping through prometheus with `annotation` was not working at the time author testing. prometheus `serviceMonitor` works fine.
=> add metric numbers of overwritten object

incubator/virtualcluster/cmd/kubectl-vc/exec.go
fixes: #1232 
solution: https://superuser.com/questions/333564/reverse-history-search-in-bash-followed-by-arrow-keys-causes-cursor-to-display-a
=> kubectl: enclose non-printing escape sequences with '\[' '\]'

incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go, incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
Ipv4 and ipv6 URL domain name is different in format. Make vc-manager compatible with ipv6 only cluster
=> correct ipv6 domain name format

incubator/hnc/docs/user-guide/README.md, incubator/hnc/docs/user-guide/how-to.md, incubator/hnc/docs/user-guide/quickstart.md, incubator/hnc/test/e2e/quickstart_test.go
As we prepare to release HNC v0.6, get rid of all references to HNC v0.4
and convert the HNC demos to a "quickstart" format (thanks to Serge
Hartmann for the initial Markdown conversion).
Tested: staged at
https://github.com/adrianludwin/multi-tenancy/tree/quickstart/incubator/hnc/docs/user-guide.
Tested all links and did a quick visual inspection.
=> Add quickstart to docs and remove HNC v0.4

incubator/hnc/docs/user-guide/how-to.md
Update how-to.md to reflect both `kubectl hns config set-type` and `kubectl hns config set-resource` before and after HNC v0.6,
and schema/field changes.
Fixes #1207
=> Update how-to.md for HNCConfig schema change

incubator/hnc/internal/kubectl/tree.go
Without this change, the subnamespace footnote looks like a slightly
misformatted part of the tree:
```
default
└── [s] sub
[s] indicates subnamespaces.
```
By adding a newline, there's a nice visual separation from the tree
while also emphasizing the footnote:
```
default
└── [s] sub
[s] indicates subnamespaces
```
I also removed the period since this isn't a full sentence. If there are
any conditions, a blank line will be printed between the subnamespace
and condition footnote.
Tested: ran `kubectl hns tree` as shown above.
=> Add newline before subns footnote

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/validators/object.go, incubator/hnc/test/e2e/issues_test.go
See issue #1214. Our e2e tests were occasionally dying when a namespace
got messed up while propagated objects were in it; I *think* this is
because they got into an ActivityHalted state (so propagated objects
weren't cleaned up) but then the object validator would block deletion.
This caused the tests to hang indefinitely, and the objects couldn't
(easily) be removed without disbling the validator.
This change lets the validators know when the namespace is being
deleted, and unblocks deletion of all propagated objects.
Tested: a new e2e test hangs indefinitely without the fix and completes
successfully with it.
Fixes #1214
=> Don't block object deletion in dying namespaces

incubator/hnc/internal/pkg/selectors/selectors.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
Tested: go test -v ./internal/validator
```
=== RUN   TestUserChanges/Deny_creation_of_object_with_invalid_noneSelect_annotation
object_test.go:387: Got code 400, reason "BadRequest", message "invalid propagate.hnc.x-k8s.io/none value, strconv.ParseBool: parsing \"foo\": invalid syntax"
=== RUN   TestUserChanges/Allow_creation_of_object_with_valid_noneSelect_annotation
object_test.go:387: Got code 0, reason "", message "source object"
```
=> Add validator for none selector

incubator/hnc/internal/reconcilers/object.go
See issue #1154. In some cases, objects cannot be propagated due to
conflicts with other objects - in the case of a rolebinding, because its
role doesn't already exist. By default, controller-runtime will retry
errors in such circumstances with an exponential backoff with a 1000s
cap, which could lead users to believe that HNC is broken and will never
propagate their objects even after the problem is fixed.
This change caps the backoff at 10s, which is probably high enough that
it won't flood HNC with retries and low enough that the problem will
likely be fixed within the next one or two checks.
Tested: create a rolebinding without a role and watched the logs.
Without this change, observed that the time between attempts doubled
continuously (I saw it get to about a minute) before I …
=> Cap the backoff for the object reconciler to 10s

incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/quickstart_test.go
The test was failing incorrectly; it now passes if netpols are enabled
and is skipped if they're not.
Tested: on GKE with netpol enabled and on Kind with them disabled.
=> Fix netpol e2e test

incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/quickstart_test.go
The test was failing incorrectly; it now passes if netpols are enabled
and is skipped if they're not.
Tested: on GKE with netpol enabled and on Kind with them disabled.
=> Fix netpol e2e test (cherry-pick to master)

incubator/hnc/docs/releasing.md, incubator/hnc/hack/krew-kubectl-hns.yaml
Some release instructions were out-of-date for v0.6. The Krew template
file was also out-of-sync with what's currently in the Krew index; this
change lines them up (more or less).
=> Update release and Krew instructions

incubator/hnc/internal/pkg/selectors/selectors.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
If we have an object `A` already existing in child namespace `c1`, and
we are creating a new object also called `A` in the parent namespace,
and only _select_ it to propogate to another child namespace `c2`, we
should allow this operation, because `A` is not propagating to `c1` and
will not cause any conflict.
Test cases are also added in 'object_test.go'
Tested:
```
$ cat << EOF >> test.yaml
> apiVersion: v1
kind: Secret
metadata:
annotations:
propagate.hnc.x-k8s.io/treeSelect: c
name: my-creds
namespace: a
EOF
$ k delete secret my-creds -n a
$ k create -f test.yaml
```
=> Check conflict with the selectors

incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/hncconfig_test.go, incubator/hnc/internal/validators/object.go
Tested:
```
k hns config set-resource secrets --mode Remove
k delete secret my-creds -n a
k -n a create secret generic my-creds --from-literal=password=empty
k annotate secret my-creds -n a "propagate.hnc.x-k8s.io/treeSelect"="c"
k hns config set-resource secrets --mode Propagate
```
=> Add check for exceptions when checking conflicting objects on mode change

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/apis/config/types.go, incubator/virtualcluster/pkg/syncer/resources/node/util.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
This adds a flag to the syncer to allow you to set a "non-standard" vn-agent port with the syncer. You could previously supply a custom port to the vn-agent but it wouldn't work with how it was hardcoded when syncing.
=> [vc] adding support for custom vn-agent ports

incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go
The 'allowCascadingDelete' flag has to be set if the namespace to be 
deleted has any child namespace. If the namespace to be deleted has 
no child namespace, then no flag is required.
Fix #876
=> Update namespace deletion validator

incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go, incubator/virtualcluster/pkg/syncer/handler/enqueue_object_test.go, incubator/virtualcluster/pkg/syncer/resources/register.go
The object added to mccontroller fairqueue cannot be a pointer. Otherwise, the dws will break. 
This change also removes ingress from default registry list.
=> [VC] Fix an enqueobject bug

incubator/hnc/Makefile, incubator/hnc/README.md
- Kustomize binary path will be infered based on the OS
with default set to the binary in hack dir
- Kubectl target works
- Updated docs on how to install configure sed on OSX
Testing:
Issue: [#1262 ](https://github.com/kubernetes-sigs/multi-tenancy/issues/1262)
=> Fixed issues with local development on OSX

incubator/hnc/internal/kubectl/configset.go
This normalize synchronize mode string format to match with current supported mode: Propagate, Ignore, Remove,
allows synchronize mode input to be case-insensitive.
Tested:
- exec `kubectl` command and set any mode
Closes:  #1238
=> HNC: kubectl supports case-insensitive mode

incubator/hnc/cmd/manager/main.go, incubator/hnc/go.mod, incubator/hnc/vendor/modules.txt
This change reduces the differences between regular and debug logging
(it simply changes the logging level, as opposed to also the format) and
also gets rid of the (largely useless) stack traces that are printed out
during an error.
Tested: observed the better logging behaviour with the new switches.
=> Better debug and error logging

incubator/virtualcluster/config/sampleswithspec/tenancy.x-k8s.io_clusterversions.yaml, incubator/virtualcluster/doc/demo.md
This PR introduces 3 major updates for VirtualCluster:
1. Fix the CRD as the generated one for `clusterversions` doesn't work
2. Add `kind` support, together with existing `minikube`
3. Review the demo flow with more comments for users to better understand VirtualCluster through the process
=> [VirtualCluster] Fix `clusterversions` CRD, add `kind` support and review the demo flow

incubator/hnc/internal/validators/namespace.go, incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/issues_test.go
When deleting a parent namespace, we should allow it if none of its
children are sub-namespace.
In the E2E test, I moved the webhook deletion out of AfterEach, so that
if the user doesn't have HNC_REPAIR path set, it won't delete the
webhook.
Since we changed the deletion validator, one of the tests for issue #716
does not apply anymore. I deleted it in this PR.
Fix #1269
=> Fix E2E tests and namespace deletion validation

incubator/virtualcluster/Makefile, incubator/virtualcluster/config/crds/tenancy.x-k8s.io_clusterversions.yaml, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml, incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml, incubator/virtualcluster/doc/demo.md
Two major fixes:
1. Patch in `Makefile` to correct the CRDs generated by the `controller-gen` tool.
2. Use the generated CRDs, instead of temporary ones, in the demo doc.
=> [VirtualCluster] patch to correct the CRDs generated by controller-gen and use them in demo

incubator/hnc/pkg/testutils/testutils.go, incubator/hnc/test/conversion/conversion_test.go, incubator/hnc/test/e2e/delete_crd_test.go, incubator/hnc/test/e2e/issues_test.go, incubator/hnc/test/e2e/namespace_test.go, incubator/hnc/test/e2e/quickstart_test.go, incubator/hnc/test/e2e/rolebinding_test.go, incubator/hnc/test/e2e/subnamespace_test.go
See issue #1043. Added functions Createnamespace,Createsubnamespace,
CreateNamespaceWithLabels,CleanupTestNamespaces. The create functions
mark all the namespaces with a test label. Refactored all e2e test
cases to utilize the new functions. Preserved the older CleanupNamespace
function if it is useful for specific namespace deletion use case
Tested: Ran the e2e tests on k3d with k8s version v1.17.12. All tests passed
except the network policies test which was skipped.
=> CleanupNamespaces shouldn't require an explicit list of namespaces

incubator/hnc/internal/pkg/selectors/selectors.go, incubator/hnc/internal/validators/object_test.go
If multiple non-negated namespaces are set for treeSelect, this object
will not be propagated to anywhere, in which case the user should use
none selector instead.
=> Validate only one non-negated namespace for treeSelect

incubator/hnc/pkg/testutils/testutils.go
Replace `Eventually()` with `Expect()` in `MustNotRun()` so that commands like
`kubectl create` won't pass for the first time and then eventually fail
without throwing any errors.
Tested by `make test-e2e` (22/32 passed, 10/32 skipped).
=> Fix MustNotRun() can pass without error bug

incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/conversion/equality_test.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
In most cases, the source of truth is super pod status, because super master actually
own the physical resources, status is reported by **real** kubelet.
Besides, kubernetes allows user-defined conditions, such as pod readiness gate, it will
report readiness state to pod conditions. In other words, the source of truth for user-defined
pod conditions should be tenant side controller, only the condition reported by kubelet should
keep consistent with super.
It is not recommended that webhook in super append other readiness gate to pod. we left them unchanged
in super, don't sync them upward to tenant side.
=> [VC] syncer: support readiness gate condition

incubator/hnc/internal/config/default_config.go
We shouldn't allow subnamespaces or nontrivial hierarchies in
kube-node-lease, just like it's not allowed in kube-system and a few
others.
Tested: without this change, can create a subns in kube-node-lease; with
this change, I get the appropriate error message. Not adding an
automated test for this since it would just duplicate the contents of
the default_config.go file. All existing e2e tests pass.
Fixes #1229
=> Exclude kube-node-lease from HNC

incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/test/conversion/conversion_test.go
Prior to this change, HNC removes the v1a1 managedBy annotation, but if
it's being set by an external manager (which, after all, is the only
reason it exists), this will create a war between the manager and HNC.
Ironically, that's exactly what this annotation is trying to prevent.
This change simply removes the code to "clean up" the old annotation.
It should be the responsibility of the external tool to stop setting it.
This change will *not* be cherrypicked into the master branch since
we're removing all the v1a1 conversion code anyway.
Tested: I had to make this change in order to include HNC v0.6.0 in the
latest version of Hierarchy Controller (the GKE product that includes
HNC); this change simply upstreams that fix. Without this change, I
verified that as part of …
=> Don't delete the managedBy annotation

incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hncconfig.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/object.go
Add the username and operation for all logs.
Tested: deployed with verbose logging and ensured the username and op
were visible for all operations.
Fixes #1138
=> Ensure consistent logging for all validators

incubator/virtualcluster/pkg/vn-agent/server/route.go, incubator/virtualcluster/pkg/vn-agent/server/server.go
don't renew transport object in each handler, reuse it
or it may keep a live connection.
related to https://github.com/golang/go/issues/24719
=> [VC] fix: vn-agent socket fd leak

incubator/hnc/config/manager/manager.yaml, incubator/hnc/docs/user-guide/faq.md
Increase memory limits to 300M and requests to 150M since we store more
info, e.g. source objects, in the forest now. About 700 namespaces with
10 propagatable objects in each namespace would use about 200M memory
from performance tests.
Add memory usage in user-guide faq docs.
=> Increase memory limits and requests and update docs

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/internal/reconcilers/object.go
If the reconciler cannot parse the selector annotation to a valid
selector, we record an event so that the user will get notified.
Tested:
```
$ k create ns a
$ k hns create a1 -n a
$ k delete validatingwebhookconfigurations.admissionregistration.k8s.io hnc-validating-webhook-configuration
$ k create role test -n a --verb=update --resource=deployments
$ k annotate role test -n a "propagate.hnc.x-k8s.io/none"="**foo"
$ k get event -n a
LAST SEEN   TYPE      REASON                OBJECT      MESSAGE
41s         Warning   CannotParseSelector   role/test   invalid propagate.hnc.x-k8s.io/none value: strconv.ParseBool: parsing "**foo": invalid syntax
```
Fix #1165
=> Generate event for exceptions

incubator/hnc/cmd/manager/main.go, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hnc_config.go, incubator/hnc/internal/reconcilers/setup.go, incubator/hnc/internal/reconcilers/suite_test.go
The default client uses cache, and therefore, it might fail to notice if
a CR is deleted. We instead use our own client who doesn't use the
cache.
Fix #1285
=> Create client for checking CRD deletion

incubator/hnc/Makefile
The makefile calls kustomize twice in the manifests directory, and
leaves the last kustomization.yaml file there when it finishes. This
change swaps the order so that the more useful file (the one that
generates hnc-manager.yaml) is the one that's left so that developers
can play with it if necessary.
Tested: both yaml files are still created and the expected
kustomization.yaml file is left behind.
=> Generate full manifest last

incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
As of right now, the only prefix we allow before `hnc.x-k8s.io` is
`propagate`, and the only suffix after this combination should be
`select`, `treeSelect` or `none`. Any other prefix should or other 
selector suffix be rejected.
Tested: make test; make test-e2e
Fix #1206
=> Validate HNC selector annotation

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/pkg/syncer/apis/config/types.go, incubator/virtualcluster/pkg/syncer/util/feature.go
We will enhance syncer to support various new features such as enabling a super cluster pool to serve multiple tenants. 
This change adds feature-gate command line support to the syncer.
=> [VC] Add featuregates cmdline support in syncer

incubator/virtualcluster/experiment/.gitignore, incubator/virtualcluster/experiment/Makefile, incubator/virtualcluster/experiment/OWNERS, incubator/virtualcluster/experiment/cmd/scheduler/app/config/config.go, incubator/virtualcluster/experiment/cmd/scheduler/app/options/options.go, incubator/virtualcluster/experiment/cmd/scheduler/app/server.go, incubator/virtualcluster/experiment/cmd/scheduler/main.go, incubator/virtualcluster/experiment/hack/lib/build.sh, incubator/virtualcluster/experiment/hack/lib/docker-image.sh, incubator/virtualcluster/experiment/hack/lib/init.sh, incubator/virtualcluster/experiment/hack/lib/util.sh, incubator/virtualcluster/experiment/hack/make-rules/build.sh, incubator/virtualcluster/experiment/hack/make-rules/release-images.sh, incubator/virtualcluster/experiment/pkg/scheduler/apis/config/types.go, incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go
This change creates an experiment fold in VC repo. It contains the implementation of a VC scheduler which supports the experimental feature  - superclusterpooling.
When there are multiple super clusters, this scheduler will decide which super cluster should sync the tenant objects (namespace, pod, etc) that are created in the tenant master.
This change adds necessary build scripts so that the scheduler development can be decoupled with main vc repo.
=> [VC] Add framework code for an experimental vc scheduler

incubator/virtualcluster/cmd/syncer/app/config/config.go, incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/app/server.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/pkg/syncer/util/feature.go
When supporting multiple super masters, the syncer needs to identify the super cluster it is serving for to decide if an object marked with super cluster owner in the tenant master should be synced or not. 
Since K8s does not provide a reliable UUID for a cluster, we leverage a configmap created by the super cluster administrator to identify the super cluster. The configmap is stored in kube-system namespace and uses the predefined name (we can make it configurable later if needed). The syncer will not verify the ID and relies on the administrator to guarantee its uniqueness. 
This change also renames the feature name for better readability.
=> [VC] Identify supercluster via configmap

incubator/virtualcluster/experiment/cmd/scheduler/app/config/config.go, incubator/virtualcluster/experiment/cmd/scheduler/app/options/options.go, incubator/virtualcluster/experiment/cmd/scheduler/app/server.go, incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go, incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go, incubator/virtualcluster/experiment/pkg/scheduler/watcher/virtualcluster/register.go
This change adds basic data structure for the vc scheduler. Like VC syncer, the scheduler also needs to 
manage multiple tenant clusters by watching the VC crd. Unlike VC syncer, the scheduler only needs to watch the tenant object states for scheduling, hence many interfaces are simpler. 
We leverage the multicluster controller framework in VC syncer to allow the scheduler to watch multiple tenant apiservers. This change adds the framework code.
=> [VC] Add scheduler resource watcher framework

incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/patrol/differ/differ.go, incubator/virtualcluster/pkg/syncer/patrol/differ/differ_test.go, incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go, incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
1. refactor: using differ in configmap checker
2. add differ for patroller in better performance
- compare tenant and super object in O(N+M)
- reduce temporary memory copy from lister
=> VC: introduce differ to optimize patroller algorithm

benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go, benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md, benchmarks/kubectl-mtb/test/utils/resources/deployment/deployment.go
Created custom deployment object fun as it in previous test deployments the image pull policy was not `always`, thats why this benchmark was failing due to the kyverno image pull policy
=> MTB: added custom deployment func

incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/register.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
This change adds supercluster reconciling loop. The implementation is very similar to that of virtualcluster reconciling loop.
We probably can avoid some duplicated code by introducing interfaces but the gain is moderate since we only have two types of cluster for now. 
In next change, I will refactor the cluster interface so that it can support both VirtualCluster and Cluster CRDs.
=> [VC] Add supercluster reconciling loop

incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/pod.go
This change introduces basic structures in scheduler cache. They are Pod, Namespace and Cluster.
The basic model is that a namespace quota is divided into multiple slices based on the quota slice size. The slices are assigned to different clusters. A Pod is assigned to a cluster based on the quota slices distribution of the corresponding namespace.  The cluster object will track the overall slice allocation.
All objects will be protected by a cache lock which will be introduced in future change hence we don't have per object lock.
=> [VC] Introduce basic structures (Pod, Namespace, Cluster) for scheduler cache

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
This change adds basic SchedulerCache structure and the common Cache interface. The current interface methods are implemented and more will be added later. 
The add/remove namespace operations are "atomic" when more than one cluster can be involved. This means all changes
are applied or none of them is applied in case any error happens. They will be hooked to controller event handler later.
Among all management operations, the cache updates will be the most tricky ones. More specific update methods will be added in future changes.
=> [VC] Introduce SchedulerCache

incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go, incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go, incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go, incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
This change fixes two UT problems:
1) Now the default VC namespace is added to the super cluster object labels/annotations. We need to update the test accordingly;
2) The DefaultFeatureGate variable needs to be initialized, otherwise the UT will crash.
=> [VC] Fix UT breakage

incubator/virtualcluster/experiment/cmd/scheduler/app/server.go, incubator/virtualcluster/experiment/config/crd/cluster.x-k8s.io_clusters.yaml, incubator/virtualcluster/experiment/config/setup/all_in_one.yaml, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/pkg/util/constants/constants.go
This change adds the logic to retrieve the kubeconfig of the super cluster so that the scheduler is able to access the super cluster. We assume the kubeconfig is saved in a secret in the super cluster CR's namespace using the CR's name. This is not exactly matching the CAPI recommendation but is consistent with how VC handles the kubeconfig. We may refactor this part later to follow CAPI's convention.
This change also adds the yaml file to deploy the scheduler in vc-manager namespace using a deployment.
=> [VC] Finish reconciling super cluster CR in scheduler

incubator/virtualcluster/pkg/syncer/syncer.go, incubator/virtualcluster/pkg/syncer/util/test/runDWS.go, incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go, incubator/virtualcluster/pkg/syncer/util/test/runUWS.go, incubator/virtualcluster/pkg/util/cluster/cluster.go, incubator/virtualcluster/pkg/util/cluster/fake_cluster.go, incubator/virtualcluster/pkg/util/listener/adapter.go, incubator/virtualcluster/pkg/util/listener/listener.go, incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
for now, we add the event handler before cluster cache synced done. event go through mccontroller will be dropped
```
E0126 04:36:02.339414       1 mccontroller.go:473] kube-system/pod-garbage-collector dws request reconcile failed: The client cache has not been synced yet.
E0126 04:36:02.341958       1 mccontroller.go:473] kube-system/horizontal-pod-autoscaler-token-n87mg dws request reconcile failed: The client cache has not been synced yet.
E0126 04:36:02.342283       1 mccontroller.go:473] kube-system/node-controller-token-nzfb8 dws request reconcile failed: The client cache has not been synced yet.
E0126 04:36:02.342377       1 mccontroller.go:473] kube-system/pod-garbage-collector-token-2vqsn dws request reconcile failed: The client cache has not been synced yet.
E0126 …
```
=> VC: syncer: start watch cluster event after cache sync

benchmarks/kubectl-mtb/go.sum, benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go, benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/block_use_of_nodeport_services.go
`kubectl-mtb run -n test1,test --as nody,bob`
Right now hardcoded for 2 tenants but can be made dynamic, will do when we will get that requirement as it will lead to a major change in generic way of writing code of a benchmark.
=> MTB: changed flag input format

incubator/virtualcluster/experiment/pkg/scheduler/manager/manager.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
This change follows up previous refactor changes and uses the new listener interface in the scheduler. The listener startup workflow in the scheduler thus is consistent with that in the vc syncer.
=> [VC] Use new listener interface in Scheduler

incubator/hnc/hack/prow-e2e/Dockerfile, incubator/hnc/hack/prow-e2e/Makefile, incubator/hnc/hack/prow-e2e/README.md, incubator/hnc/hack/prow-e2e/run-e2e.sh
This change will allow Prow to run all HNC e2e tests as postsubmits or
periodic tests. Prow configs will be submitted in a followup commit in
the appropriate repo.
Tested: 'make run' successfully runs all HNC e2e tests (excluding the
NetworkPolicy test, which is expected) in a Kind cluster triggered from
the container image that will run in Prow.
=> Create e2e test image for Prow

incubator/virtualcluster/experiment/cmd/scheduler/app/server.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper_test.go, incubator/virtualcluster/pkg/util/constants/constants.go
This change adds the major workflow for initializing the scheduler cache when the scheduler starts/restarts. The idea is that we need to recovery the entire scheduler cache states as much as possible before serving any scheduling requests.
The biggest challenge is how to deal with the failures when retrieving the states. To unblock the scheduler, we will mark the failed superclusters or virtualclusters dirty and send them to corresponding workqueue to retry initialization. The dirty clusters are in quiescence state until they are successfully synchronized with the scheduler cache (in future change).
Many sophisticated handlings are needed during state synchronization which are marked as TODOs in this PR.
=> [VC] Initialize scheduler cache

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/validators/object.go, incubator/hnc/internal/validators/object_test.go
This PR changes detect namespace deletion that was done in reconciler 
into object validator by utilizing controller-runtime's client
fixes #1241 
supersede PR #1284 
test:
make test
=> Changes detect namespace deletion  into object validator

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change adds retry logic in vc and super cluster reconcilers when scheduler cache has not been synchronized for the 
corresponding cluster. This change also allow existing objects to be updated using Add interfaces.  
To avoid an offline super cluster to block entire scheduler cache synchronization, we introduce a shadow cluster with infinite capacity. The shadow cluster will not participate in scheduling until the correct capacity is updated when the super cluster becomes online again. The namespace placements are still accounted in the shadow cluster so that the virtualcluster state synchronization can proceed even if the placed supercluster is offline.
=> [VC] Retry synchronizing cluster state and allow updating existing objects

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change adds two new fields in the Cluster state which represents the observed namespace placement results in the
super masters. They are going to be used in the scheduling algorithm to deal with the scheduler cache inconsistency in case of vc or super cluster failures. 
The super cluster cache synchronization is changed accordingly. This change also refactors several places to avoid
dup code.
=> [VC] Add provision results in scheduler cluster state

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/constants/constants.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go, incubator/virtualcluster/pkg/util/cluster/cluster.go
This change adds the reconciler for supercluster namespace. The goal is to update the cluster provision namespace information in the scheduler cache.
This change also adjusts the clustername used in the mccontroller. Using id as the clustername instead of the CR full name simplifies the reconciling logic. Otherwise, we have to fetch the configmap in the super cluster during the reconciling.
=> [VC] Add supercluster namespace reconciler

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go
This change adds dumping cache functionality, mainly used for debugging. For now, the cache state will be dumped every minute, which is subject to change in the future. 
New dump structures are introduced which are the same as internal cache objects except that all fields are exported. 
Then we can leverage json marshal capability to make "pretty print" for the cache content.
=> [VC] Add cache dump functionality

incubator/virtualcluster/experiment/cmd/scheduler/app/server.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/health.go, incubator/virtualcluster/experiment/pkg/scheduler/metrics/metrics.go, incubator/virtualcluster/experiment/pkg/scheduler/scheduler.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change adds health check for the virtual clusters and super clusters. Some basic metrics are added to the scheduler.
We leverage the super cluster health check to update the super cluster capacity in case the capacity changes due to adding/removing nodes or node errors. We may tune this later if a single node failure needs to be notified to the scheduler immediately.
=> [VC] Add health check and update super cluster capacity periodically

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/conversion/helper_test.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
This adds a new featuregate - `featuregate.SuperClusterServiceNetwork` which when turned on will use the superclusters tenant control plane service `ClusterIP` for configuring the `KUBERNETES_SERVICE_HOST` environment variable. This allows controllers deployed into virtualclusters to route to the correct control plane without needing the forked CoreDNS.
Ref #1394 
=> [VC] Adding super cluster networking feature

incubator/virtualcluster/experiment/pkg/scheduler/algorithm/types.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go, incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go, incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine_test.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change has refactored the interfaces in SchedulerEngine to satisfy the tenant namespace reconciler. It seems that we don't need the rollback mechanism if the scheduling result is failed to be updated to tenant namespace. Instead, we can retry later while keeping the placement in the scheduler cache. 
This change also implements the major workflows in the SchedulerEngine interfaces. The only missing part is to call the scheduling algorithm. The ScheduleNamespace interface covers the following scenarios: 
- Schedule for a new namespace (with quota)
- Schedule extra slices if a namespace's quota is increased.
- Determine the new placement if a namespace's quota is reduced.
- Reschedule if the placement result is modified (e.g., remove the stale schedule to a cluster that is unhealthy)
=> [VC] Implement major workflows in SchedulerEngine

incubator/hnc/hack/prow-e2e/Dockerfile, incubator/hnc/hack/prow-e2e/Makefile, incubator/hnc/hack/prow-e2e/README.md, incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
This change uses the krte (KIND RunTime Environment) image as a base,
since it knows how to run Docker-in-Docker even when the Prow node
doesn't have Docker installed on it already (e.g. because it uses
containerd, I think).
Also sets the HNC_REGISTRY env var explicitly so it doesn't pick up the
default from gcloud in the image.
Tested: Without this change, HNC periodics are failing; with this
change, everything passes.
=> Fix Docker-in-Docker and image name

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cache_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change handles the cache updates when VC or Cluster CRs are added or removed. 
Since we have shadow cluster objects to handle super cluster offline, the shadow cluster may exist even after the super cluster CR is removed. A periodic checker is added to clean up old shadow clusters.
=> [VC] Update SchedulerCache when vc or cluster CRs are added/removed

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot_test.go, incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
This change adds snapshot support for namespace scheduling. The snapshot is one of the inputs to the algorithm. Only the cluster capacity and the total allocations are needed in the snapshot.
=> [VC] Snapshot schedulercache for namespace scheduling

incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot_test.go
The UT was developing in a separate branch without the latest change, causing the problem.
=> [VC] Fix a broken UT

incubator/hnc/hack/prow-e2e/Dockerfile, incubator/hnc/hack/prow-e2e/Makefile, incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
Our first run of the HNC postsubmits failed, most likely because the
workdir is modified by Prow (based on the messages I'm seeing). This
change updates the Dockerfile and test script to _not_ assume a specific
workdir, and also allows Prow to set up the repo when appropriate.
Tested: script runs locally but there's no good way for me to test on
Prow. As soon as this is merged, the postsubmits themselves will tell me
if I got this right or not.
=> Attempt to fix HNC postsubmits

incubator/hnc/hack/prow-e2e/Dockerfile, incubator/hnc/hack/prow-e2e/run-e2e-tests.sh
The postsubmits are now failing because Kind isn't in the path. Print
out all the env vars so we can figure out why.
Tested: image runs locally and prints out env. Image has already been
pushed to the registry.
=> [HNC] Add envvar printout for debugging

incubator/hnc/hack/prow-e2e/README.md
I made a small mistake pushing the docker image before my last change; this is mainly just to trigger another postsubmit.
=> Get rid of now-mostly-wrong readme

incubator/virtualcluster/experiment/pkg/scheduler/resource/supercluster/namespace/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/resourcequota/controller.go, incubator/virtualcluster/pkg/syncer/manager/manager.go, incubator/virtualcluster/pkg/util/handler/enqueue_object.go, incubator/virtualcluster/pkg/util/handler/enqueue_object_test.go, incubator/virtualcluster/pkg/util/listener/adapter.go, incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go
In Syncer, the UID has to be put in the reconcile request to make the objects in super cluster and tenant control plane consistent. But in scheduler, adding UID in reconcile request may lead to parallel scheduling for Pods with the same name but different UIDs (think of a case where a Pod is created/deleted/created).
In this change, the scheduler reconcile request will exclude the Pod UID.
=> [VC] Make UID in reconcile request optional

incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go, incubator/virtualcluster/experiment/pkg/scheduler/cache/pod.go, incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/pod/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go
This change removes Pod UID from scheduler cache since it is not used anyway. The unused GetPod method is also removed from the Engine interface.
=> [VC] Clean up: Remove UID from Pod in scheduler cache

incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go, incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go, incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/resources/service/checker.go, incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
if the cluster cache is not loaded, vSet is missing them,
but pSet object is exists, differ will delete the pObj.
left the redundant object gc by ns checker.
=> [VC] fix: only check known cluster in differ

incubator/virtualcluster/pkg/vn-agent/server/translate.go
support running `--tails=<num-lines>` command line options for `kubectl logs`
=> [VC] support command options `--tail` for `kubectl logs`

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/cmd/syncer/builtins_extra.go, incubator/virtualcluster/cmd/vn-agent/app/options/options.go
This adds support for the vn-agent to support getting `featuregates` in later PRs I'll have a new feature added into the vn-agent for customized native vnode objects. 
=> [VC] Adding support for vn-agent to have featuregates via flags

incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go, incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/pod/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go, incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go, incubator/virtualcluster/pkg/util/record/event.go
This change uses client-go EventCorrelator to filter/throttle the same/similar events sent to the tenant control plane.
This change does not use the client-go EventBroadcaster since it uses a heavy weight event dispatch mechanism and it has to be created for each tenant control plane, which means the event cache (a fixed size LRU cache) has to be duplicated for every tenant control plane.
In this implementation, one event cache is used by all tenant control planes with a default 4K entries. Later, we can make the cache size configurable if there are too many virtual clusters.
The scheduler uses the event sinker to notify the tenant control plane about the scheduling result. For example:
```
kubectl get event -A --kubeconfig=vc-sample-1.kubeconfig
NAMESPACE   LAST SEEN   TYPE     REASON …
```
=> [VC] Use event sinker in mccontroller

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/apis/config/types.go, incubator/virtualcluster/pkg/syncer/resources/node/controller.go, incubator/virtualcluster/pkg/syncer/resources/pod/controller.go, incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go, incubator/virtualcluster/pkg/syncer/vnode/provider/provider.go, incubator/virtualcluster/pkg/syncer/vnode/service/provider.go, incubator/virtualcluster/pkg/syncer/vnode/service/provider_test.go, incubator/virtualcluster/pkg/syncer/vnode/vnode.go
These changes make it so that you can use the vn-agent as a Kubernetes deployment when not using the direct to Kubelet proxy mechanism. All you need to do is deploy the vn-agent as a `Deployment`, then you create a new `ClusterIP` Service (this could potentially also be a LoadBalancer later to support the experimental scheduler with a couple tweaks) once that is setup you deploy the syncer with the flags `--vn-agent-namespace` and `--vn-agent-service-name` and it will fetch the service clusterIP at node creation to register with the virtual node resource.
=> [VC] Adding vn-agent deployment feature

incubator/hnc/Makefile, incubator/hnc/README.md
Fixes #1371
If you have older version of kubebuilder installed locally on your
computer, the envtest would load older version of etcd and
kube-apiserver from your /usr/local/kubebuilder/bin for tests. Since we
just migrated from v1beta1 to v1 for CRDs, K8s < v1.16 would not know
v1/CRD. Thus the tests would all fail.
Add reinstall kubebuilder info in `make test` and README for developers.
Failed tests look like this - https://gist.github.com/yiqigao217/9394c2aadaa515e82184684a005187af
Passed tests look like this - https://gist.github.com/yiqigao217/d8d097c99df54997915c57fda17f96bb
=> Add reinstall kubebuilder info in test and README

incubator/virtualcluster/cmd/syncer/app/options/options.go, incubator/virtualcluster/pkg/syncer/apis/config/types.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
if set to true, it will disable service links for all of
the pPods to avoid massive env injections from syncer
which replace the kubelet generated envs
=> syncer: add option to disable service links

incubator/virtualcluster/experiment/config/setup/setup-supercluster-minikube.sh, incubator/virtualcluster/experiment/config/setup/syncer.yaml.sed, incubator/virtualcluster/experiment/pkg/scheduler/reconciler.go
This change fixes a problem such that the scheduler cache is not updated when creating new VC or Cluster CR. 
The solution is simple but not ideal since the cache will be updated twice when scheduler restarts. We may fix it later if this is really a concern for performance.
The change also fixes a few script problem.
=> [VC] Sync cache when new Cluster or VC CR is created

incubator/virtualcluster/pkg/syncer/resources/crd/controller.go
Looks like we might have use `annotations` where all other shared resources use `labels` see - https://github.com/kubernetes-sigs/multi-tenancy/search?q=PublicObjectKey
=> [VC] Using labels for super.public crds

incubator/virtualcluster/pkg/syncer/resources/crd/checker.go, incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
This removes a couple overly verbose loggers in the crs and priority class syncers.
=> [vc] cleaning logging in extra syncers

incubator/virtualcluster/pkg/syncer/constants/constants.go, incubator/virtualcluster/pkg/syncer/resources/pod/checker.go, incubator/virtualcluster/pkg/syncer/vnode/vnode.go
This change fixes two problems when enabling SuperClusterPooling feature.
1) The Pod checker needs to exclude vPod that is not scheduled to the syncer's cluster;
2) The vNodeGC module should not check the vNode that does not belong to the syncer's cluster;
The checkers of other resources should be fixed as well, which will be done later.
=> [VC] Fix vNodeGC and Pod checker bugs when enabling SuperClusterPooling feature

incubator/virtualcluster/pkg/syncer/resources/crd/controller.go, incubator/virtualcluster/pkg/syncer/resources/crd/uws.go
This removes a couple more of the debugging logs from the CRD resource syncer since there is more global ways these events are logged we don't need them duplicated.
=> [vc] Remove more logs from CRD Syncer

incubator/virtualcluster/experiment/doc/demo.md, incubator/virtualcluster/pkg/syncer/conversion/equality.go, incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go, incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go, incubator/virtualcluster/pkg/util/constants/constants.go
We need to update the placement results to super cluster namespace so that the scheduler cache can be updated correctly. 
This change handles the tenant namespace update event to populate metadata to the super cluster. In addition, the syncer disallows to populate label/annotation keys that have keyword "k8s.io", hence we need to rename the constant keys used in the scheduler.
=> [VC] Add Namespace update synchronization for scheduling placement

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/cmd/manager/main.go, incubator/hnc/config/manager/manager.yaml, incubator/hnc/config/webhook/manifests.yaml, incubator/hnc/config/webhook/webhook_patch.yaml, incubator/hnc/docs/user-guide/concepts.md, incubator/hnc/internal/config/default_config.go, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/anchor_test.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hierarchy_config_test.go, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/internal/validators/anchor.go, incubator/hnc/internal/validators/anchor_test.go, incubator/hnc/internal/validators/hierarchy.go, incubator/hnc/internal/validators/hierarchy_test.go, incubator/hnc/internal/validators/namespace.go, incubator/hnc/internal/validators/namespace_test.go, incubator/hnc/internal/validators/object.go, incubator/hnc/test/e2e/issues_test.go, incubator/hnc/test/e2e/rolebinding_test.go
Fixes #374, #1023.
Part of #1443.
See design https://bit.ly/hnc-excluded-namespaces.
Add `excluded-namespace` container args in the
config/manager/manager.yaml to allow user defined excluded namespaces.
The default excluded namespaces are kube-system, kube-public, hnc-system
and kube-node-lease. Add excluded-namespace label to hnc-system by
default to avoid deadlock (between cert-rotator writing secret vs object
webhook failing CLOSE) when installing HNC. Let users to add
excluded-namespaces to other namespaces.
Replace the hard-coded `EX` excluded namespaces.
Add webhook patch only to the object validator with namespaceSelector to
filter excluded namespaces. Add comments on why not patching other
validators. Make object validator fail CLOSE now.
Patch object webhook to only apply on …
=> Make excluded namespace configurable

incubator/virtualcluster/pkg/syncer/conversion/helper.go, incubator/virtualcluster/pkg/syncer/conversion/mutate.go, incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
As explained in the change comments, in case of super cluster pooling, it is possible that the tenant default namespace is not synced to current super cluster. We need to query the tenant apiserver to get the services in tenant default namespace. 
With this change, the Pods created in namespaces other than the default namespace can be synchronized to super cluster successfully. 
```
kubectl get pod -A --kubeconfig=vc-sample-1.kubeconfig
NAMESPACE   NAME                     READY   STATUS    RESTARTS   AGE
test        golang-fcffb8587-c7sxg   1/1     Running   0          17s
test        golang-fcffb8587-jf4sn   1/1     Running   0          17s
test        golang-fcffb8587-kbrwc   1/1     Running   0          17s
test        golang-fcffb8587-kcngn   1/1     Running   0          17s
```
=> [VC] Get services of default namespace from tenant when enabling SuperClusterPooling

incubator/hnc/internal/reconcilers/anchor.go
Fixes #1339
Currently in the anchor reconciler, when the new subnamespace has error
being created, anchor instance is not updated to set the 'Missing'
state.
This commit calls the `writeInstance()` (anchor instance) before
returning the creating namespace error to retry.
The other two alternatives to fix this problem considered are:
1) Update the `kubectl hns create` plugin to add 'Missing' as default
state in the created anchor object. The concern is that users may apply
manifests to create anchors instead of using `kubectl hns` plugin.
2) Update the anchor CRD not to omitempty the `status.state` field and
default to `Missing`. Since this is an API change and the fix in anchor
reconciler is simple, I didn't go with this approach.
Tested manually without any changes in the integration …
=> Ensure setting 'Missing' anchor state when ns cannot create

incubator/hnc/Makefile, incubator/hnc/README.md
Part of #1480 
Force adding excluded-namespace labels to excluded namespaces before
running the e2e test so that it won't break the cluster. E.g. HNC object
webhook denies any object changes in namespaces without this label, it
could break `kube-system` namespace if the label is missing.
Add `test-e2e-batch` target and factor out the messages before e2e
tests for regular `test-e2e` and `test-e2e-batch`. Add link to
excluded-namespace concept.
Tested by `make test-e2e` and `make test-e2e-batch N=3`.
Prow config is unchanged because in `hack/prow-run-e2e.sh` for
postsubmit and periodic e2e tests, it's already using `test-e2e` target.
The output for `make test-e2e-batch N=10` looks like [this](https://gist.github.com/yiqigao217/d4b04bfe70afadae0fa31460e54752c5).
=> Ensure excluded-namespaces are properly configured before e2e tests

incubator/hnc/Makefile
Fixes #1480
Exclude system namespaces `kube-system`, `kube-public`,
`kube-node-lease`before deploying HNC in `deploy` target in Makefile.
Tested by running `./incubator/hnc/hack/prow-run-e2e.sh`.
=> Exclude namespaces before deploying HNC

incubator/hnc/api/v1alpha2/hierarchy_types.go, incubator/hnc/internal/kubectl/describe.go, incubator/hnc/internal/kubectl/root.go, incubator/hnc/internal/reconcilers/anchor.go, incubator/hnc/internal/reconcilers/anchor_test.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/hierarchy_config_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
Fixes #1443
Remove any HNC CRs (hierarchyconfiguration and anchor) from the excluded
namespaces if they are successfully created bypassing the webhook.
Set `ActivitiesHalted: IllegalParent` condition if a namespace sets an
excluded namespace as a parent, e.g.
```
$ kubectl hns describe a
Hierarchy configuration for namespace a
Parent: kube-system
Children:
- d (subnamespace)
Conditions:
- ActivitiesHalted (IllegalParent): Parent "kube-system" is an excluded namespace
```
Subnamespace anchor using an excluded namespace name would get
`Forbidden` state. Update the `kubectl hns describe` to show:
```
$ kubectl hns describe parent
Hierarchy configuration for namespace parent
No parent
Children:
- d (Conflict subnamespace)
- e (subnamespace)
- f
- kube-system (Forbidden subnamespace)
No …
```
=> Handle bypassed webhook rules on excluded namespaces

incubator/hnc/config/rbac/hnc_admin.yaml, incubator/hnc/config/rbac/kustomization.yaml
The builtin 'admin' clusterrole doesn't include custom resources by
default. This change allows 'admin' to modify any HNC resource. If
granted at the cluster level, it will allow the user to administer HNC
itself (via the HNCConfiguration object); otherwise, it will allow a
user to administer the HierarchyConfiguration singleton in the namespace
(and its descendants) as well as SubnamespaceAnchors. Note that this
will *not* allow that user to change the _parent_ of that namespace
without permissions in the root of its tree (see user guide for more
details).
Tested: before this change, I gave the 'admin' role to the default
service account in 'foo' and ran the following command:
```
k hns create bar -n foo --as system:serviceaccount:foo:default
```
Result:
```
Could not create subnamespace …
```
=> Allow builtin 'admin' role to manage HNC objects

incubator/hnc/Makefile, incubator/hnc/config/rbac/role.yaml, incubator/hnc/docs/user-guide/faq.md, incubator/hnc/docs/user-guide/how-to.md, incubator/hnc/internal/reconcilers/object.go, incubator/hnc/test/e2e/issues_test.go
Rather than continuing to play whack-a-mole with the list of verbs HNC
can propagate, this change allows it to perform all verbs on all
resources. This is equivalent to `cluster-admin` so I've updated the
docs accordingly (see also issue #1311).
I also noticed that the docs referred to K8s v1.15, which is no longer
supported, so I updated them to v1.16.
Finally, this change adds the `HNC_FOCUS` makefile var, allowing you to
say something like:
```
HNC_FOCUS=772 make test
```
which only runs the e2e tests with "772" in the title.
Tested: All quickstart e2e tests pass. Updated the test for issue #772
and verified that it failed without the other changes in this commit,
and passed with them.
Fixes #1311
=> Support cluster-admin propagation and update docs

incubator/hnc/test/e2e/issues_test.go
This test assumed that HNC was not able to propagate cluster-admin
rolebindings, but this just changed so the test is now failing.
Issue #1492 tracks re-enabling this, but for now we'll disable.
=> Disable broken test

incubator/hnc/internal/forest/namespace.go, incubator/hnc/internal/reconcilers/hierarchy_config.go, incubator/hnc/internal/reconcilers/object_test.go, incubator/hnc/internal/reconcilers/test_helpers_test.go
Detect namespace label changes. If the labels are updated, ensure
syncing all the objects (including non-existing yet but possible
propagated objects) in the namespace, so that we will not miss any
propagation label changes that should trigger propagation or
unpropagation.
Add integration tests in reconciler/object_test.go.
Tested manually that labeling and unlabeling a child with the propagate
label won't do anything before the fix, but triggers propagation and
unpropagation accordingly after the fix. Also tested with `make test`,
passed after the fix ant failed before the fix.
=> Sync object propagation on newly labeled namespaces

incubator/hnc/docs/user-guide/README.md, incubator/hnc/docs/user-guide/concepts.md, incubator/hnc/docs/user-guide/how-to.md, incubator/hnc/docs/user-guide/quickstart.md
Add documentation for excluded namespaces and remove references to HNC
v0.6.
Fixes #1466 
Interesting modified files include:
* [Installation instructions](https://github.com/adrianludwin/multi-tenancy/blob/docs-v08/incubator/hnc/docs/user-guide/how-to.md#prerequisite)
* [Excluded namespaces howto](https://github.com/adrianludwin/multi-tenancy/blob/docs-v08/incubator/hnc/docs/user-guide/how-to.md#admin-excluded-namespaces)
* [CLI howto](https://github.com/adrianludwin/multi-tenancy/blob/docs-v08/incubator/hnc/docs/user-guide/how-to.md#admin-cli-args)
* [Labels concepts](https://github.com/adrianludwin/multi-tenancy/blob/docs-v08/incubator/hnc/docs/user-guide/concepts.md#hncx-k8sioexcluded-namespace-label-on-namespaces)
=> Update docs for upcoming v0.8

incubator/hnc/Makefile
Apparently the default limit is 10m and we've now gone over that (we
were averaging around 7m, I wonder if GCB now uses a slower machine
since little has changed on our side). Anyway, 30m should be enough for
the foreseeable future.
=> Increase HNC release timeout to 30m (HNC v0.8 branch)

incubator/hnc/Makefile
Apparently the default limit is 10m and we've now gone over that (we
were averaging around 7m, I wonder if GCB now uses a slower machine
since little has changed on our side). Anyway, 30m should be enough for
the foreseeable future.
=> Increase HNC release timeout to 30m (master branch)

incubator/hnc/README.md, incubator/hnc/docs/user-guide/how-to.md
Note that v0.8.0 isn't release yet but this will ensure that when it is, it shows that the commits are up-to-date. I'll port this to the master when it's actually released.
=> Update all docs to point to HNC v0.8.0

README.md, incubator/hnc/README.md, incubator/hnc/docs/user-guide/README.md, incubator/hnc/docs/user-guide/best-practices.md, incubator/hnc/docs/user-guide/concepts.md, incubator/hnc/docs/user-guide/faq.md, incubator/hnc/docs/user-guide/how-to.md, incubator/hnc/docs/user-guide/quickstart.md
Update all links, and mark the Tenant Operator as being deprecated now
that it's not used by VC or being developed anymore.
=> Move HNC to its own repo

benchmarks/kubectl-mtb/README.md, benchmarks/kubectl-mtb/test/benchmarks/block_other_tenant_resources/README.md, benchmarks/kubectl-mtb/test/benchmarks/block_other_tenant_resources/config.yaml, benchmarks/kubectl-mtb/test/benchmarks/block_role_privilege_escalation/README.md, benchmarks/kubectl-mtb/test/benchmarks/block_role_privilege_escalation/block_role_privilege_escalation.go, benchmarks/kubectl-mtb/test/benchmarks/block_role_privilege_escalation/block_role_privilege_escalation_test.go, benchmarks/kubectl-mtb/test/benchmarks/block_role_privilege_escalation/config.yaml
See #1518 for full details.
In short, it's very easy for administrators to accidentally grant users the undocumented ["escalate" verb](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping) on tenant Roles, which lets tenants bypass many other benchmarks, like by deleting ResourceQuotas/LimitRanges. Since it's such a pain to obtain the "true" full list of verbs when writing Roles, administrators are likely to read the "Allow self-service management of Roles" benchmark and create a role like the following:
```yaml
- apiGroups: ['rbac.authorization.k8s.io']
resources: ['*']
verbs: ['*']
```
When instead they should enumerate all of the verbs, leaving out the "escalate" verb:
```yaml
- apiGroups: ['rbac.authorization.k8s.io'] …
```
=> Add block_role_privilege_escalation benchmark

benchmarks/kubectl-mtb/README.md, benchmarks/kubectl-mtb/internal/kubectl-mtb/get.go, benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go, benchmarks/kubectl-mtb/internal/kubectl-mtb/util.go
Fixes #1520 
* I had a hard time understanding what a "resource" is, since really it just has to be the word "benchmark(s)", which is optional. So I made the "usage" more explicit, and used the not-very-official POSIX specification for the args: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html 
-  Seems like needing to specify "benchmark" may have been leftover from some plan for kubectl-mtb to run things other than benchmarks.  Should we just remove that arg all together since it's optional anyway?
* Made `filterBenchmarks` return an error if the user specified an ID that didn't exist. Without this check, you get a nil element in the variable `benchmark` which causes segfaults elsewhere in the code.
=> Improve 'usage' and fix error handling for unknown IDs

benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go, benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md, benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/config.yaml, benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image.go
Fixes #1516 
This PR checks the kube-apiserver pod Command to determine if the [AlwaysPullImages admission plugin](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) is enabled. If it is, that is sufficient to satisfy the require_always_pull_image benchmark.
The Admission plugin works by allowing users to create pods with whatever imagePullPolicy they want, but it just modifies the value to "Always" before the pod starts up. As a result, without this PR, the benchmark fails unless you have some other validatingwebhook like gatekeeper enforcing the policy.
=> Allow the AlwaysPullImages admission plugin to satisfy benchmark
