poc/tenant-controller/cmd/tenant-ctl/main.go
poc/tenant-controller/data/manifests/sample-tenant.yaml
poc/tenant-controller/pkg/controllers/tenants/controller.go
tools/lib/devtk/cmd-setup.sh

controller and in the cluster  (basically works but further cleanup and
functionality to be added in subsequent commits/ PRs)

Initial commit of code for creating tenant and namespaces state in the

---

OWNERS

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

Add Ryan to owners

---

README.md

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

Update README with how to join this repo

---

OWNERS

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>

Move David & Yisui to emeritus

---

OWNERS

Easier to contribute to main project and incubator project.

Request to be owner and reviewer

---

incubator/virtualcluster/OWNERS

The incubator project has different owners.

[incubator] Add virtualcluster project owners

---

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go

This change adds support to import existing namespace to tenant management system by adding proper ownerReference. 
Notes: I didn't check the RequireNamespacePrefix flag in this change because I think the logic is going to be messy if I did it. The below shows how RequireNamespacePrefix flag affects the reconcile result.
Case A:
Tenant: RequireNamespacePrefix == false
TenantNamespace: Name == t1
Namespace: t1
RESULT: t1 is imported by adding ownerReference to tenantNamespace object.
Case B:
Tenant: RequireNamespacePrefix == true
TenantNamespace: Name = t1
Namespace: t1
RESULT: t1 is not imported and a new namespace tenant-t1 is created
Case C:
Tenant: RequireNamespacePrefix == true
TenantNamespace: Name = t1
Namespace: tenant-t1
RESULT: tenant-t1 is going to be imported by adding …

Import existing namespace by adding OwnerReference

---

incubator/virtualcluster/pkg/vn-agent/server/server_test.go
incubator/virtualcluster/pkg/vn-agent/testcerts/certs.go
incubator/virtualcluster/pkg/vn-agent/testcerts/gencerts.sh

the principle job is to test the naming translation of each api.

vc: vn-agent: test for /containerLogs, /run api proxy

---

incubator/hnc/controllers/hierarchy_controller.go
incubator/hnc/controllers/hierarchy_controller_test.go

Per [1], the validating webhook will occasionally allow hierarchies with
missing parents. This change removes the behaviour from the reconciller
to explicitly break hierarchy pointers to missing parents.
Tested: integ tests only
[1] https://docs.google.com/document/d/10MZfFfbQMm33CBboMq2bfrEtXkJQQT4-UH4DDXZRrKY/edit#heading=h.jwiouvmonz1r

Allow missing parents (with a condition warning)

---

tenant/Makefile
tenant/README.md
tenant/config/manager/all_in_one.yaml
tenant/config/manager/manager.yaml
tenant/config/samples/tenancy_v1alpha1_tenantnamespace.yaml

Add a basic README.md for people to try the tenant controllers.

Add README.md for Tenant Operator

---

tenant/README.md

Fix the wrong urls to pull yaml files from github.

Fix wrong links

---

tenant/config/manager/all_in_one.yaml

Fix wrong namespace for clusterRoleBinding

---

OWNERS

Adding so I can approve changes to the HNC.

Add adrianludwin as owner/reviewer

---

incubator/hnc/pkg/kubectl/tree.go

Show conditions in tree subcmd

---

incubator/hnc/pkg/controllers/hierarchy_controller.go

Passes the namespace object to the `reconcile` function to allow it to
be modified at the same time as the singleton. This will enable more
sophisticated reconciliations including self-service namespace creation
and adding labels to the namespace to indicate ancestry.
Tested: existing integ tests; manual with subsequent commits.
_See https://github.com/adrianludwin/multi-tenancy/commits/self-serve for the full context of this PR_

Reconcile namespace and singleton in tandem

---

incubator/hnc/pkg/controllers/hierarchy_controller.go

Rather than collecting a list of namespaces to mark for enqueueing after
`syncWithForest` is complete, this change allows them to be enqueued
inline, which simplifies the control flow.
This also means that it's possible for the same namespace to be
reconciled twice at the same time (it was *probably* possible before as
well). While syncWithForest is guarded by the forest-wide mutex, there
is a chance that the results could be committed to the apiserver
out-of-order. I don't *believe* I ever observed this (a bug I was
chasing turned out to be a more mundane logic error) but in order to fix
this potential problem, this change introduces a per-namespace lock that
is only released after the namespace has been _fully_ committed.
This allows multiple namespaces to be reconciled in parallel …

Restructure NS enqueuing; improve thread safety

---

incubator/hnc/pkg/controllers/setup.go

This commit adds five Kinds to be inherited via their GVK
values.
Test: manually via make manifests then make test.

Passes new kinds to be inherited

---

incubator/hnc/Makefile
incubator/hnc/hack/ci-test.sh

Hey there delilah,
Here we create a bash script to run the tests and do some prechecking, like `make kubectl`. This script will be called on the Prow config file.

Create bash script for CI

---

incubator/hnc/pkg/controllers/hierarchy_controller.go

Refactor hierarchy controller

---

tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go

This change adds validation webhook for tenant object creation and update. It ensures:
1) TenantAdminNamespaceName and RequireNamespacePrefix fields in tenant Spec cannot be changed after initial creation;
2) The TenantAdminNamespaceName in the Spec is a valid namespace name;

Add admission webhook for tenant CR

---

incubator/hnc/pkg/controllers/hierarchy_controller.go
incubator/hnc/pkg/controllers/hierarchy_controller_test.go
incubator/hnc/pkg/forest/forest.go

Add CRIT_ANCESTOR condition to hier controller

---

incubator/virtualcluster/Dockerfile

[incubator][vc] fix dockerfile after using go module

---

incubator/hnc/pkg/controllers/hierarchy_controller_test.go

This commit cleans up CritAncestor tests with the factored out hasCondition() func.

Clean up CritAncestor tests with hasCondition()

---

incubator/virtualcluster/config/crds/tenancy_v1alpha1_clusterversion.yaml
incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
incubator/virtualcluster/config/rbac/auth_proxy_service.yaml
incubator/virtualcluster/config/rbac/rbac_role.yaml
incubator/virtualcluster/config/sampleswithspec/clusterversion_v1.yaml
incubator/virtualcluster/config/sampleswithspec/virtualcluster.yaml
incubator/virtualcluster/go.mod
incubator/virtualcluster/go.sum
incubator/virtualcluster/hack/remove-vc
incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion.go
incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/clusterversion_types.go
incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
incubator/virtualcluster/pkg/controller/add_clusterversion.go
incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
incubator/virtualcluster/pkg/controller/kubeconfig/kubeconfig.go
incubator/virtualcluster/pkg/controller/pki/pki.go
incubator/virtualcluster/pkg/controller/secret/secret.go
incubator/virtualcluster/pkg/controller/util/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

1. implement the functionality for constructing the PKI
2. create sample yaml for the ClusterVersion

implement the functionality for constructing the PKI for virtual cluster

---

incubator/hnc/pkg/controllers/object_controller.go

This is the 1st step of https://github.com/kubernetes-sigs/multi-tenancy/issues/76#issuecomment-541188994

Restructure update() to consolidate calls with forest lock

---

incubator/hnc/pkg/controllers/object_controller.go

Remove very verbose log message

---

incubator/hnc/Makefile
incubator/hnc/README.md
incubator/hnc/devenv

Also fixes a bug that `deploy` doesn't delete the old deployment first.

Make HNC easily deployable onto non-Kind clusters

---

incubator/hnc/pkg/controllers/object_controller.go

Supposedly-identical objects were being marked as "modified," I think
because the HNC annotations themselves were out-of-sync. This could also
affect objects (like ResourceQuota) whose status is automatically
updated.
To fix this, copyObject() is renamed to canonical() and it now clears
any non-canonical fields, including the Status and all labels and
annotations (this was partially implemented before, but is now fully
correct).
Tested: on GKE, automatically populated and identical objects like
gke-resource-quotas are no longer marked as being modified.

Better comparison of propagated objects

---

incubator/hnc/pkg/controllers/object_controller.go
incubator/hnc/pkg/controllers/object_controller_test.go

Fixing a bug I introduced in
https://github.com/kubernetes-sigs/multi-tenancy/pull/171. I should have
checked the callers more carefully; this caller assumed that HNC labels
were _not_ deleted from the object returned by `canonical()`.
Tested: verified that changes to integ test would have caught this, then
fixed the bug. Verified behaviour on a real cluster.
/cc @rjbez17

Fix inheritedFrom label to point to the orginal namespace

---

incubator/hnc/pkg/kubectl/tree.go

What this PR does / why we need it:
This PR adds a feature that allow kubectl hnc tree --all-namespaces to show all namespaces. This feature enables users to list all namespaces along with their heirarchies.
Suggested changes :
`kubectl hnc tree foo # displays foo`
`kubectl hnc tree # error`
`kubectl hnc tree --all-namespaces # displays the tree of all namespaces`
`kubectl hnc tree -A # synonym for --all-namespaces`
Which issue(s) this PR fixes:
Fixes #130

Flag added to show tree of all namespaces

---

incubator/hnc/pkg/controllers/object_controller.go
incubator/hnc/pkg/controllers/object_controller_test.go

a part of #76 and as the next step in 0.1 after this [discussion](https://github.com/kubernetes-sigs/multi-tenancy/pull/183#issuecomment-546472222)

Remove object modified annotation and fix flaky tests

---

incubator/hnc/pkg/forest/forest.go

Signed-off-by: sph <shepenghui1@huawei.com>

fix golint error

---

tenant/Makefile
tenant/cmd/manager/main.go
tenant/pkg/apis/addtoscheme_tenancy_v1alpha1.go
tenant/pkg/apis/tenancy/v1alpha1/doc.go
tenant/pkg/apis/tenancy/v1alpha1/register.go
tenant/pkg/controller/add_tenant.go
tenant/pkg/controller/add_tenantnamespace.go
tenant/pkg/controller/tenant/tenant_controller.go
tenant/pkg/controller/tenant/tenant_controller_suite_test.go
tenant/pkg/controller/tenant/tenant_controller_test.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_suite_test.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_event_handler.go
tenant/pkg/util/tenant_utils.go
tenant/pkg/webhook/add_default_server.go
tenant/pkg/webhook/default_server/add_validating_tenant.go
tenant/pkg/webhook/default_server/add_validating_tenantnamespace.go
tenant/pkg/webhook/default_server/tenant/validating/create_update_webhook.go
tenant/pkg/webhook/default_server/tenant/validating/tenant_create_update_handler.go
tenant/pkg/webhook/default_server/tenantnamespace/validating/create_update_webhook.go
tenant/pkg/webhook/default_server/tenantnamespace/validating/tenantnamespace_create_update_handler.go

I should include "kubernetes-sigs" in the project path. This change fixes the problem.

Fix project path

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/go.mod
incubator/virtualcluster/pkg/syncer/controller/controller.go
incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/syncer.go

[incubator][VC] fix resource syncer issue

---

incubator/virtualcluster/pkg/syncer/controllers/register.go
incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go

[incubator][vc] add service sync controller

---

incubator/hnc/pkg/controllers/hierarchy_controller.go

changes-
indentation changes.
Tested- run code and tested everything is working fine.

run go fmt in the code

---

incubator/hnc/pkg/controllers/hierarchy_controller.go
incubator/hnc/pkg/controllers/object_controller.go
incubator/hnc/pkg/kubectl/root.go
incubator/hnc/pkg/metadata/metav1.go
incubator/hnc/pkg/validators/object.go
incubator/hnc/pkg/validators/object_test.go

Move some helper functions for interacting with k8s API Object to be a standalone package

Create Metadata package

---

incubator/hnc/Makefile
incubator/hnc/hack/hnc.yaml

Tested: Require to have archive `hnc.tar.gz` in the `<hnc>/plugin` , do `sha256sum` on it and copy the checksum value into `<hnc>/plugin/hnc.yaml`. 
Then run `make krew-local`
Fixes #132

Package kubectl plugin for krew

---

incubator/hnc/pkg/validators/hierarchy.go
incubator/hnc/pkg/validators/hierarchy_test.go

This validates required child and parent of a required children. It will close #99 .
Tested manually first by setting parent of a required child and setting
different NS as required child. Then unit tests are added.

Ensure hierarchy doesn't violate required children

---

tenant/pkg/apis/tenancy/v1alpha1/tenant_types.go

fix typo in tenancy

---

incubator/virtualcluster/cmd/syncer/app/config/config.go
incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/cmd/syncer/app/server.go
incubator/virtualcluster/cmd/syncer/main.go
incubator/virtualcluster/pkg/syncer/apis/config/types.go
incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/controller/controller.go
incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
incubator/virtualcluster/pkg/syncer/controllers/node/node.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/register.go
incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/handler/enqueue_object.go
incubator/virtualcluster/pkg/syncer/handler/types.go
incubator/virtualcluster/pkg/syncer/listener/listener.go
incubator/virtualcluster/pkg/syncer/manager/manager.go
incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
incubator/virtualcluster/pkg/syncer/syncer.go

Reverts kubernetes-sigs/multi-tenancy#232

Revert "pull back syncer code"

---

incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
incubator/virtualcluster/pkg/syncer/controllers/node/node.go

fixes https://github.com/kubernetes-sigs/multi-tenancy/issues/220

[incubator][VC] update virtual node status by events from super master

---

incubator/hnc/pkg/controllers/hierarchy_controller.go
incubator/hnc/pkg/forest/forest.go
incubator/hnc/pkg/forest/forest_test.go
incubator/hnc/pkg/validators/hierarchy.go

Some typos  confuse the readability of the source code, so I fixed them.

fix some typo

---

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go

This is done by introducing a finalizer.  Some codes are refactored as well.

Remove namespace from tenant clusterrole when tenantnamespace CR is deleted

---

tenant/README.md

Rewrite the README.md to explain the basic RBAC settings for tenant admins.

Update Tenant README.md

---

incubator/virtualcluster/cmd/vcctl/subcmd/create.go

[incubator][VC] flying check for vckbcfg option

---

incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go

kubelet will auto generate service env from super master side
we must set env var when creating pod, and kubelet won't
overwrite it
```bash
[root@vm vc]# kubectl get svc -A
NAMESPACE                          NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default                            kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP                  3d7h
kube-system                        kube-dns        ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   3d7h
tenant1admin-vc-sample-1-default   kubernetes      ClusterIP   10.99.108.4      <none>        443/TCP                  2d23h
tenant1admin                       apiserver-svc   NodePort    10.102.122.129 …
```

[incubator][VC] inject service related env var to pod

---

incubator/virtualcluster/config/sampleswithspec/virtualcluster_1.yaml
incubator/virtualcluster/pkg/syncer/controller/controller.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/syncer.go

use `<namespace>-<name>` as the unique if for cluster
everything still works fine 😄

[incubator][VC] add work queue for virtual cluster controller

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/controller/controller.go
incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/listener/listener.go
incubator/virtualcluster/pkg/syncer/syncer.go

stop the virtual cluster cache and remove record

[incubator][VC] support to teardown virtual cluster from syncer

---

incubator/hnc/Makefile
incubator/hnc/README.md
incubator/hnc/cloudbuild.yaml

partially resolve #228 
Need to manually upload images to Docker Hub later. 
/assign @adrianludwin

Config Cloud Build YAML file for HNC releases

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/cmd/vcctl/subcmd/create.go
incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/controller/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go

1. delete the pod in super master with grace period after observing
delete timestamp of virtual pod
2. in uws, delete virtual pod with 0 grace period second after the pod
in super master has been deleted
3. virtual pod actually deleted by tenant controller

[incubator][VC] reconcile pod deletion event

---

incubator/virtualcluster/OWNERS

Jerry has done tremendous work on virtual cluster project. Add him to approver list to enable faster development cycle.

Add Jerry(zhuangqh) to VC approver

---

incubator/hnc/Makefile
incubator/hnc/config/certmanager/certificate.yaml
incubator/hnc/config/default/kustomization.yaml

* This PR closes #275 
* Update certmanager version to `v0.12.0-beta.1`
[UPDATE]
* Update certmanager version to `v0.11.0`

Closes #275: fix certmanager version

---

incubator/virtualcluster/Makefile
incubator/virtualcluster/hack/make-rules/test-e2e-k8s.sh

```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig
```

[incubator][VC] add script to run k8s e2e test on a local cluster

---

incubator/virtualcluster/pkg/syncer/conversion/helper.go

```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS=InitContainer
```
test pass

[incubator][VC] fix: mutate spec of init containers of the pod

---

incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/conversion/helper_test.go

```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="\[sig-node\].*Downward.*API"
```
test pass

[incubator][VC] fix: replace fieldRef env with virtual pod's value

---

incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go

```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="ConfigMap"
```
```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="Projected.*configMap"
```
test pass

[incubator][VC] feature: observe value update event

---

incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/equality_test.go

```bash
make test-e2e-k8s KUBECONFIG=~/vc/vc-1.kubeconfig BUILD_DEPENDENCIES=false FOCUS="updates.*should.*be.*reflected.*in.*volume"
```
update value related test all pass.

[incubator][VC] observe endpoints, secrets value update event 

---

incubator/hnc/pkg/controllers/hierarchy_controller.go
incubator/hnc/pkg/controllers/object_controller_new.go

Also removes some verbose logs from the new object controller.
Tested: this one's hard to test. I manually created a namespace with 10
children and restarted the controller, and the root is only reconciled
twice even though each of the children try to enqueue it. Then again, we
barely testing multithreading before enabling it and the client code
referenced in
https://github.com/kubernetes-sigs/multi-tenancy/issues/212 seems pretty
clear, so I think this is fairly safe.
Fixed #212 
/assign @Fei-Guo 

Remove redundant per-namespace locks

---

incubator/hnc/pkg/controllers/hierarchy_controller.go

Before this change, *every* time an ancestor namespace was reconciled,
*all* descendants would be as well. This change only enqueues
descendants when the subtree's parent has been changed, since this is
the only thing that could affect all descendants (apart from the
addition/removal of a critical condition, which already enqueues all
descendants).
Tested: changed parent and verified that all labels were updated. Looked
at logs and everything is working as expected.

Only enqueue descendants when labels are changed

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/controllers/node/uws.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/uws.go
incubator/virtualcluster/pkg/syncer/syncer.go

- Add some comments to improve code readability. 
- Replace variable name innerCluster with tenantCluster
- Add 'go' for a sync.WaitGroup use case.

[incubator][VC]Code cleanup plus minor bug fix

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/controllers/configmap/controller.go
incubator/virtualcluster/pkg/syncer/controllers/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/controllers/namespace/controller.go
incubator/virtualcluster/pkg/syncer/controllers/node/controller.go
incubator/virtualcluster/pkg/syncer/controllers/pod/controller.go
incubator/virtualcluster/pkg/syncer/controllers/secret/controller.go
incubator/virtualcluster/pkg/syncer/controllers/service/controller.go
incubator/virtualcluster/pkg/syncer/controllers/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/listener/listener.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/syncer.go

Rename controller/controller.go to mccontroller/mccontroller.go
Rename NewController to NewMCController
Revise comment.

[incubator][VC] Clean up MultiClusterController

---

incubator/virtualcluster/go.mod
incubator/virtualcluster/pkg/syncer/controllers/event/controller.go

[vc] fix resource syncer build issue

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/syncer.go

add tenant dns setup script 
support tenant aware dns server
1. get tenant name server from service kube-system/kube-dns
2. mutate pPod's dns config to bypass kubelet's behavior

[incubator][VC] support tenant aware dns server

---

benchmarks/README.md
benchmarks/documentation/definitions.md
benchmarks/e2e/tests/block_add_capabilities/README.md
benchmarks/e2e/tests/block_bind_mounts/README.md
benchmarks/e2e/tests/block_cluster_resources/README.md
benchmarks/e2e/tests/block_host_ipc/README.md
benchmarks/e2e/tests/block_host_net_ports/README.md
benchmarks/e2e/tests/block_host_pid/README.md
benchmarks/e2e/tests/block_multitenant_resources/README.md
benchmarks/e2e/tests/block_nodeports/README.md
benchmarks/e2e/tests/block_ns_quotas/README.md
benchmarks/e2e/tests/block_other_tenant_resources/README.md
benchmarks/e2e/tests/block_privilege_escalation/README.md
benchmarks/e2e/tests/block_privileged_containers/README.md
benchmarks/e2e/tests/configure_ns_quotas/README.md
benchmarks/e2e/tests/default_deny_net_conn/README.md
benchmarks/e2e/tests/require_run_as_non_root/README.md

complete MT-PL1 benchmarks and update definitions

[MTB] Complete multi-tenancy profile level 1 benchmarks

---

incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go

[incubator][VC] add ownerReference meta info to super pod meta as annotation

---

incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go

if dns server has not configured, fallback to DNSDefault

[incubator][VC] make tenant dns server optional

---

incubator/virtualcluster/pkg/syncer/resources/node/util.go

[incubator][VC] make virtual node unschedulable to avoid possible scheduler

---

incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go

[incubator][VC] add extend info (deployment) to vPod

---

incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/manager/manager.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go

1. add service checker
2. meta extender: add clusterIP info to service
3. fix a closure trick

[incubator][VC] add service resource checker

---

incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/dws.go
incubator/virtualcluster/pkg/syncer/resources/node/util.go
incubator/virtualcluster/pkg/syncer/resources/node/uws.go

- Make sure we only reconcile Virtual Node created by syncer
- Ignore host updates other than condition changes
- Make sure if a tenant cluster is removed, it is removed from nodeNameToCluster map.

[Incubator][VC]Refactor Node syncer

---

incubator/hnc/pkg/controllers/object_controller.go
incubator/hnc/pkg/controllers/setup.go

Tested by 'make test' and manual testing on GKE cluster.

Rename ObjectReconcilerNew to ObjectReconciler

---

incubator/virtualcluster/pkg/controller/util/kube/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go

when creating the default namespace of the Virtualcluster, add vc related annotation to the object

[Incubator][VC] add vc annotations to default namespace

---

incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/utils/string.go

Reverts kubernetes-sigs/multi-tenancy#389
The function provided by this PR will be included in a future PR.

Revert "[Incubator][VC] ignore annotations that have specific prefixes "

---

incubator/hnc/config/rbac/role.yaml

This update is generated from a previous change.

Update the generated role.yaml

---

incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go

Add standard periodic checks for namespace and configmap resources.

[Incubator][VC] Add checker for namespace and configmap resources

---

incubator/virtualcluster/config/crds/tenancy_v1alpha1_virtualcluster.yaml
incubator/virtualcluster/pkg/apis/tenancy/v1alpha1/virtualcluster_types.go
incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go

1. add service cidr to vc crd
2. in aliyun mode, annotate vc cr with ask clusterID

[Incubator][VC] add service cidr to vc crd

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go

[incubator][VC] fix compile error and correct vc spec

---

incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws.go

1. dws service account token type secret remove event
2. check service account token secret of tenant

[incubator][VC] complete secret syncer

---

incubator/virtualcluster/pkg/syncer/conversion/equality.go

[incubator][VC] fix: ep equality checker panic

---

incubator/virtualcluster/pkg/controller/util/kube/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go
incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go
incubator/virtualcluster/pkg/syncer/resources/event/uws.go

1. implement the DeletionVirtualcluster function, which deletes
namespace affiliated to target virtualcluster on the super master
2. add annotations (i.e. clusterkey, admin-kubeconfig) for aliyun mode

[Incubator][VC]implement the DeleteVirtualcluster function

---

incubator/virtualcluster/pkg/syncer/metrics/metrics.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
incubator/virtualcluster/pkg/syncer/resources/node/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go

This change adds metrics to measure the time spent in running periodic checker.
We also adds metrics to measure the time spent in sending node heartbeats.

[Incubator][VC]  Add metrics to measure checker scan duration

---

incubator/virtualcluster/pkg/syncer/syncer.go

The key format is namespace/name which is different from cluster name whose format is namespace-hash-name.

[Incubator][VC]Fix a small bug on handling WaitForCache failure.

---

incubator/virtualcluster/pkg/syncer/resources/pod/uws.go

shorten the pod syncing latency by
1. checking if the target vnode exist before creating
2. fetching the latest version of vpod after binding instead of requeuing

[Incubator][VC] shorten the pod syncing latency

---

incubator/virtualcluster/pkg/syncer/resources/node/util.go

[incubator][VC] attach well known label to vNode

---

incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go

[incubator][VC] remove endpoints uid checker

---

incubator/virtualcluster/pkg/syncer/resources/pod/checker.go

[incubator][VC] requeue pPod if status diff from vPod

---

incubator/virtualcluster/pkg/syncer/conversion/mutate.go

Pod affinity rules take effect by only considering Pod labels. It is possible that a Pod from one tenant is affected by the affinity rules set in Pods from another tenant. 
This change resolves the problem by adding the tenant label in all affinity terms so that the rules only apply for Pods belong to the same tenant.

[Incubator][VC]Ensure Pod affinity rule is only applied within tenant scope

---

incubator/hnc/pkg/reconcilers/hnc_config_test.go
incubator/hnc/pkg/reconcilers/object.go

This PR adds the support for 'remove' mode in ConfigReconciler. If the mode of a type is set to 'remove', all the propagated objects (i.e., objects created by HNC) of the type will be removed. However, source objects (i.e., objects created by users) of the type will not be removed.
Tested: GKE cluster; unit tests.
Design doc: http://bit.ly/hnc-type-configuration
Issue: #411

Support 'remove' mode in ConfigReconciler.

---

incubator/hnc/pkg/reconcilers/object_test.go

Update `isModified()` to return a function for `Eventually` to retry.
Change `ExpectWithOffset` to `EventuallyWithOffset` to get the object.
This prevents wierd cases of failure when the object does exist but the
first attempts of getting the object fails.
Tested with "make test" for 20+ times to make sure it's not flaky.

Update `isModified()` to remove sleeps in tests

---

incubator/virtualcluster/cmd/manager/main.go
incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
incubator/virtualcluster/pkg/controller/controller.go
incubator/virtualcluster/pkg/controller/vcmanager/vcmanager.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

1. allow the user to specify the max number of reconcilers
2. add the status condition that records the vc starting time

[Incubator][VC] allow the user to specify max number of reconcilers

---

incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/syncer/syncer.go

[incubator][VC] syncer: try to get tenant admin kubeconfig from vc object

---

incubator/virtualcluster/pkg/syncer/syncer.go

[incubator][VC] fix: decode kubeconfig base64 string

---

incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/cluster/fake_cluster.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go

1. make each component testable
2. add test for namespace downward syncer 

[incubator][VC ] add mock testing framework

---

incubator/hnc/pkg/validators/hierarchy.go
incubator/hnc/pkg/validators/hncconfig.go

This PR changes the StatusReason from StatusReasonForbidden to StatusReasonInvalid when handling invalid requests in `hncconfig.go`. To show the custom error message when the request is invalid, we need to add the message in the `Status.Details` field.
Issue: #411

Change from StatusReasonForbidden to StatusReasonInvalid for invalid requests

---

benchmarks/e2e/config/config.go
benchmarks/e2e/config/utils.go

Signed-off-by: Nguyen Le Vu Long <vulongvn98@gmail.com>

[MTB] refactor: use yaml unmarshal

---

benchmarks/e2e/config/config.go
benchmarks/e2e/config/utils.go
benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go

This pull request handles an empty config file gracefully instead of panicking.

Handles an empty config file

---

benchmarks/e2e/config/config.go

Corrects path of config.yaml

---

benchmarks/e2e/tests/configure_ns_object_quotas/README.md

added test definition of configure ns object limits

---

benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
benchmarks/e2e/tests/e2e.go
incubator/hnc/go.mod
poc/tenant-controller/go.mod

Fixes #402. Adds test for [https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_privileged_containers/README.md](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/e2e/tests/block_privileged_containers/README.md)

Adds block_privileged_container test

---

incubator/hnc/api/v1alpha1/hierarchy_types.go
incubator/hnc/pkg/forest/forest.go
incubator/hnc/pkg/reconcilers/hierarchy_config.go
incubator/hnc/pkg/reconcilers/object.go

Special thanks to @yiqigao217 for recommending some key parts of this
approach.
Our handling of conditions in the forest has been pretty lax - we
basically use strings with magical formatting. This change tightens up
the interface by allowing us to use the API's AffectedObject struct
instead of the string keys. This also makes conversions and
manipulations much easier, and is used by two followon PRs to address
#326 and #328.
This change also includes some minor cleanups, e.g. removing the term
"keys" from the original objects in the forest and replacing it with
"names" instead.
Tested: existing tests plus confirmed that conditions from #328 still
look good via `kubectl hns tree`.

Use API objects to store conditions

---

incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml

[incubator][VC] recreate a strict rbac role to syncer

---

incubator/virtualcluster/README.md
incubator/virtualcluster/doc/demo.md

Revise README.md to describe virtualcluster in more details.

[Incubator][VC]Revise README.md

---

incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go

if pPV is gone, we cannot find any related info for vPVC
rely on checker to clean vPVC and vPV

[incubator][VC] drop pv uws delete event

---

incubator/virtualcluster/cmd/vcctl/subcmd/create.go
incubator/virtualcluster/cmd/vcctl/util/util.go
incubator/virtualcluster/cmd/vn-agent/app/options/options.go
incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

1. use scheme.Scheme for vcctl
2. if kubelet-client-crt is empty or not set, forward the request to super master
3. `vcctl create` supports reading yaml file from url

[Incubator][VC] fixes for the first release

---

incubator/virtualcluster/README.md
incubator/virtualcluster/doc/demo.md

This change revises the virtualcluster demo readme file to provide more details about the setup and the experiments.

[Incubator][VC]Revise demo.md

---

incubator/hnc/pkg/reconcilers/hierarchy_config.go

Only log a message if the finalizers on an HC have changed. Also changed
the log message when enqueuing modified subnamespaces because I couldn't
really understand why we needed it at first.
Tested: created an HNS, observed the finalizer logs being printed only
when appropriate.

Fewer log messages about finalizers

---

incubator/hnc/README.md

Added a section on developer workflow to make it easier for developers
to onboard and get started more quickly

Enhance README.md to show developer workflow

---

incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

This change adds mock test cases for service dws.  They are similar to what have been added for namespace dws.

[Incubator][VC]Add service DWS mock tests

---

incubator/hnc/pkg/kubectl/set.go

The main change here is to add --forbidCascadingDelete, as well as some
short flags (-p for --parent, -r for --root, -a for
--allowCascadingDelete and -f for --forbidCascadingDelete). It also adds
an "examples" section to the documentation and prints out fewer messages
if allowCD is unchanged.
Tested: manual testing for all the modified variants of 'set'; verified
that new example documentation looks good.

Better flags, output and examples for hns-set

---

tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller_test.go

When tenant object is removed, all the tenantnamespace CRs should be deleted since their namepsace, aka, the tenant admin namespace is deleted. The Tenantnamespace reconciler needs to first retrieve the tenant list. The reconciler will keep reporting err since the tenant object has gone. Hence the finalizer of tenantnamespace CR can never be removed.
This change makes sure that if tenantnamespace CR is deleted and the tenant object is not found,
the finalizer should be removed so that the tenantnamespace CR can be removed from apiserver eventually.
A UT is added to test this scenario.

Break cyclical dependency when tenant CR is deleted

---

incubator/hnc/pkg/reconcilers/hierarchy_config.go

I noticed while doing a cascading deletion that the HCR was trying to
write back the HC, because after it's deleted, it looks like we want to
sync it with the namespace's owner attribute. This was causing a lot of
errors in the log because you can't create an object in a namespace
that's being deleted. This change allows HNC to continue writing back
_existing_ HCs (e.g. to remove their finalizers) but will never write
back a _new_ HC to a namespace being deleted.
I also took out the code that allows the HCR to _create_ namespaces
since this is now owned entirely by the HNSR.
Tested: watched logs during cascading deletion before and after this
change. Before, there were tons of error messages (although it did
successfully delete the NS); after, the log was clean.

Don't create HC in namespaces being deleted

---

incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

This change adds Pod dws mock tests. Pods creation needs some other objects in the client, hence the mock infra code is changed to accommodate the request.
Fix some bugs in previous mock tests code.

[Incubator][VC]Add Pod DWS mock tests

---

incubator/hnc/pkg/reconcilers/hierarchical_namespace_test.go

Instead of changing the annotation of the namespace created by the hns
instance, this PR creates a conflict hns instance with the name of an
already-existing namespace.
Tested by 'make test'.
Fixes #560

Fix a flaky test on changing namespace annotation

---

incubator/hnc/README.md

Add HierarchicalNamespace Reconciler to README. Make some other minor
changes.
Tested with "make test"

Add HierarchicalNamespace Reconciler doc to README

---

incubator/hnc/api/v1alpha1/hierarchy_types.go
incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml

Add documentation on new codes and delete the obsolete codes.
Tested with "make test".
Fixes #622

Update condition code documentation

---

incubator/virtualcluster/pkg/controller/util/kube/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

if fail to create virtualcluster, update the cluster status to `ClusterError` and update the message

[Incubator][VC] update the cluster status to ClusterError on fail 

---

incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/reconciler/reconciler.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/uws.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/uws.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go
incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go

This change introduces UpwardController to unify all uws controllers. This helps to avoid duplicate code and enable the uws mock test.

[Incubator][VC]Introduce UpwardController to unify resource uws controller

---

incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go

pod dws coverage 65.3% -> 82.3%
there are cases not covered:
- client-go failure. fail to get object
- operation race. such create pPod but already exists

[incubator][VC] add more test case to pod dws test

---

incubator/hnc/README.md

Tested: followed instructions and successfully installed v0.3.0-rc1 on
my cluster and the plugin on my workstation. Created some self-service
namespaces.

Update readme for v0.3.0-rc1

---

incubator/virtualcluster/cmd/syncer/app/server.go
incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
incubator/virtualcluster/pkg/syncer/patrol/patroller.go

[incubator][VC] syncer: add health check port

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/pkg/syncer/cluster/cluster.go

[incubator][VC] syncer: make leader election the default config

---

incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
incubator/virtualcluster/pkg/syncer/util/test/runUWS.go

pvc test coverage 0%->76.9%
defer remove cluster after test to increase test coverage

[incubator][VC] test: add pvc related unit test

---

incubator/virtualcluster/pkg/syncer/resources/persistentvolume/check_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go

filter readonly action after run test
test coverage 0->73.8%

[incubator][VC] test: add pv related test

---

incubator/hnc/README.md

Update readme for hnc-v0.3.0

---

incubator/virtualcluster/pkg/syncer/resources/register.go

[incubator][VC] fix register compile error

---

incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go

- test: add namespace checker test
-  confirm no operation in test

[incubator][VC] test: add namespace test

---

incubator/virtualcluster/cmd/syncer/app/options/options.go

fix invalid memory address error caused by empty '--super-master' command line option

[Incubator][VC] fix syncer command line option bug

---

incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

[incubator][VC] test: add secret test

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/pkg/syncer/apis/config/types.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/dws.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/uws.go

[incubator][VC] syncer: DefaultOpaqueMetaDomains config for each vc

---

benchmarks/.gitattributes

[MTB] defined merging strategy for e2e.go

---

benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go

This pull request adds some corrections for block_privilege_container_test

Makes some corrects for test: block_privileged_contaiker

---

incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws_test.go

[incubator][VC] add secret checker test

---

incubator/virtualcluster/pkg/syncer/resources/configmap/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/configmap/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

[incubator][VC] add configmap test

---

incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws_test.go

[incubator][VC] add service account test

---

incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

retry delete virtualcluster on failure

[Incubator][VC] retry delete virtualcluster on failure

---

incubator/virtualcluster/pkg/syncer/resources/service/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/service/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/service/uws_test.go

[incubator][VC] add service test

---

incubator/virtualcluster/pkg/controller/add_clusterversion.go
incubator/virtualcluster/pkg/controller/add_virtualcluster.go
incubator/virtualcluster/pkg/controller/controller.go
incubator/virtualcluster/pkg/controller/util/aliyun/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_aliyun.go

1. create package for all aliyun related functions
2. allow vc-manager to add controller based on the type of the masterprovisioner

[Incubator][VC] create a package for aliyun related functions

---

incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

[incubator][VC] add endpoints test

---

incubator/virtualcluster/README.md

This change adds a detailed demo from WG meeting in the README, plus a few editions in text.

[Incubator][VC] Add a demo link in README.md

---

benchmarks/config.yaml
benchmarks/e2e/tests/block_add_capabilities/block_add_capabilities.go
benchmarks/e2e/tests/e2e.go
benchmarks/go.mod

Block add capabilities

---

incubator/virtualcluster/README.md

I found some typos in the README.

chore: fixed typos in README

---

benchmarks/documentation/run.md
benchmarks/e2e/tests/block_cluster_resources/block_cluster_resources.go
benchmarks/e2e/tests/block_host_pid/block_host_pid.go
benchmarks/e2e/tests/block_multitenant_resources/block_multitenant_resources.go
benchmarks/e2e/tests/block_ns_quotas/block_ns_quotas.go
benchmarks/e2e/tests/block_other_tenant_resources/block_other_tenant_resources.go
benchmarks/e2e/tests/block_privileged_containers/block_privilege_container.go
benchmarks/e2e/tests/configure_ns_quotas/configure_ns_quotas.go
benchmarks/e2e/tests/create_role_bindings/create_role_bindings.go

classified tests in PLs

---

incubator/hnc/pkg/foresttest/foresttest.go
incubator/hnc/pkg/validators/anchor_test.go
incubator/hnc/pkg/validators/hierarchy_test.go
incubator/hnc/pkg/validators/namespace_test.go

I removed some of the tests about missing intermediate namespaces since they're not actually possible anymore, and my next PR will remove the ability to express them.

More flexible way to create and test forests

---

incubator/virtualcluster/pkg/syncer/resources/endpoints/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

- endpoints checker test
- event test

[incubator][VC] add event test

---

incubator/virtualcluster/README.md

Markdown style, spelling and grammar tweaks in the vc `README.md`.

[VC]: Fixing up spelling & grammar in the readme

---

incubator/hnc/pkg/reconcilers/anchor_test.go
incubator/hnc/pkg/reconcilers/hierarchy_config_test.go

Observed this flake on #703, made it retryable.
Tested: ran the tests six times, they all passed

Fix a test flake

---

incubator/hnc/api/v1alpha1/hierarchy_types.go
incubator/hnc/pkg/forest/forest.go
incubator/hnc/pkg/reconcilers/hierarchy_config.go

I never liked the fix to #328 since there was basically only one chance
to notice that conditions were now obsolete - when the parent was being
changed. This felt weird, and when I started looking at (fittingly)
issue #666, which requires us to allow cycles in the in-memory forest,
it became difficult to see how to make the existing logic work.
This new approach, by contrast, annotates each condition code with the
knowledge of whether it can be caused by an ancestor or descendant
namespace, making it easy to look at the *current* state of the forest
(and not of any one change) and determine whether the condition should
be removed. This will make future logic changes easier and just seems
cleaner overall.
This also makes a minor improvement to kubectl-hns-describe. It also
removes the …

Stable removal of obsolete conditions

---

incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go

[incubator][VC] fix: container diff if webhook add to super pod

---

incubator/hnc/pkg/reconcilers/hierarchy_config.go
incubator/hnc/pkg/reconcilers/hierarchy_config_test.go
incubator/hnc/pkg/reconcilers/test_helpers_test.go

See #660. Even when a namespace has a critical condition, we should
still update its tree labels - both because there are things we *can*
say about a namespace's ancestry, and also to *remove* labels that are
no longer valid (e.g. missing parents, ancestors in cycles).
Tested: For cycles, new unit tests plus manual checks. For orphans, I
couldn't add a unit test since the test env can't delete namespaces (I
had another go at this but failed). But I created an orphan manually and
verified that the missing parent's labels were removed from all
descendants, but other labels were not.
Fixes #660

Update tree labels even with critical conditions

---

incubator/hnc/LICENSE

This will need to be done as a prerequisite before moving HNC into its
own repository

Add Apache license from root to HNC

---

incubator/hnc/docs/user-guide/concepts.md

Made the definitions pop a bit more

Better formatting for definitions

---

incubator/hnc/docs/user-guide/README.md
incubator/hnc/docs/user-guide/concepts.md
incubator/hnc/docs/user-guide/how-to.md

Just copying over the last little bit of info from the Google docs

Add footnotes

---

incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/uws.go
incubator/virtualcluster/pkg/syncer/resources/node/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/resources/service/uws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runUWS.go

[VC] add node test

---

incubator/virtualcluster/pkg/syncer/handler/enqueue_object_test.go

[VC] add request queue test

---

incubator/virtualcluster/pkg/syncer/manager/manager.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/uws_test.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
incubator/virtualcluster/pkg/syncer/util/test/runUWS.go

1. unify resourceSyncerNew interface
2. unify testing interface
3. add storageclass test 

[VC] add storageclass test

---

incubator/hnc/internal/validators/anchor.go
incubator/hnc/internal/validators/namespace.go

See https://github.com/kubernetes-sigs/multi-tenancy/issues/688. If we
can't validate the deletion because OldObject doesn't exist, we need to
just allow the deletion.
In the case of a namespace with children and allowCascadingDelete
*unset*, this will delete the parent but *not* the children; they will
be left with two conditions (CritMissingParent and
MissingSubnamespaceAnchor). If allowCascadingDelete *is* set, everything
will work properly.
Tested: verified that everything works as expected in 1.14 and that
there are no changes in 1.16.
Fixes #688 
cc @sophieliu15 @adrianchung

Allow namespace deletion in K8s 1.14

---

incubator/virtualcluster/pkg/syncer/manager/manager.go

[VC] unify reconciler interface

---

incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/uws.go
incubator/virtualcluster/pkg/syncer/resources/event/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go

[VC] support service type event

---

incubator/virtualcluster/cmd/vcctl/subcmd/create.go
incubator/virtualcluster/pkg/controller/add_virtualcluster.go
incubator/virtualcluster/pkg/controller/clusterversion/clusterversion_controller.go
incubator/virtualcluster/pkg/controller/controller.go
incubator/virtualcluster/pkg/controller/vcmanager/vcmanager.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

Make the term used in the code consistent with the crd Kind name.

[VC] Remove the use of "Virtualcluster" term in code

---

incubator/hnc/docs/user-guide/best-practices.md
incubator/hnc/docs/user-guide/how-to.md

Also update some unclear Gitops directions.

Document uninstallation, backup and restore

---

incubator/virtualcluster/cmd/syncer/app/server.go
incubator/virtualcluster/cmd/vn-agent/app/server.go
incubator/virtualcluster/hack/lib/build.sh
incubator/virtualcluster/pkg/syncer/constants/constants.go
incubator/virtualcluster/pkg/version/base.go
incubator/virtualcluster/pkg/version/verflag/verflag.go
incubator/virtualcluster/pkg/version/version.go

```
[root@vm virtualcluster]# ./_output/bin/syncer --version
VirtualCluster v1.0.0 2020-06-02T05:04:08Z b620783
```

[VC] add version to binary

---

incubator/hnc/hack/test-issue-501.sh

Update subnamespace tests to match the latest
"SubnamespaceAnchorMissing" condition and admission controller. Current
admission controller allows adding anchor if it's missing and still
doesn't allow removing anchor when allow-cascading-delete is not set.
Fixes #768

Update subnamespace tests

---

incubator/virtualcluster/cmd/manager/main.go

add `-version` option for vc-manager

[VC] add version option for vc-manager

---

benchmarks/e2e/tests/block_nodeports/block_nodeports.go
benchmarks/e2e/tests/e2e.go

added test for block_nodeports

---

benchmarks/e2e/tests/block_add_capabilities/block_add_capabilities.go
benchmarks/e2e/tests/block_host_ipc/block_host_ipc.go
benchmarks/e2e/tests/configure_ns_object_quotas/configure_ns_object_quotas.go

added Profile level selectors

---

benchmarks/e2e/tests/create_network_policies/README.md
benchmarks/e2e/tests/create_network_policies/create_network_policies.go
benchmarks/e2e/tests/e2e.go

Added test for [MTB-PL2-BC-OPS-4]

---

benchmarks/e2e/tests/block_bind_mounts/block_bind_mounts.go
benchmarks/e2e/tests/e2e.go
benchmarks/go.sum

#404 added test for block use of bind mounts

---

benchmarks/e2e/tests/block_host_net_ports/block_host_net_ports.go
benchmarks/e2e/tests/e2e.go
benchmarks/go.mod
benchmarks/go.sum

#406 added test for block_host_net_ports

---

benchmarks/e2e/tests/e2e.go
benchmarks/e2e/tests/require_run_as_non_root/require_run_as_non_root.go

Adds test for require_as_non_root

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/README.md
incubator/hnc/docs/user-guide/how-to.md

Update docs for HNC v0.4

---

incubator/virtualcluster/cmd/vcctl/subcmd/create.go
incubator/virtualcluster/cmd/vcctl/subcmd/delete.go
incubator/virtualcluster/go.sum

This adds support for All Auth Providers for the `vcctl` cli.

Imports for all Auth providers

---

incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_loadbalancer.yaml
incubator/virtualcluster/config/sampleswithspec/clusterversion_v1_nodeport.yaml

[VC] update tenant master component to v1.16.x

---

incubator/hnc/docs/user-guide/how-to.md

Fix one-char typo

---

docs/profiles/profile-soft-multitenancy-s1.md

duplicated from https://github.com/kubernetes-sigs/multi-tenancy/pull/548

Spelling corrections 

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/pkg/syncer/cluster/cluster.go
incubator/virtualcluster/pkg/syncer/constants/constants.go

[VC] syncer: set timeout to client so request to apiserver don't hang forever

---

incubator/virtualcluster/pkg/syncer/metrics/metrics.go
incubator/virtualcluster/pkg/syncer/patrol/patroller.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
incubator/virtualcluster/pkg/syncer/syncer.go

1. fix conflict label name with grafana
2. unify checker metric collection
3. remove redundant message

[VC] cleanup: unify checker metric collection

---

incubator/virtualcluster/pkg/syncer/syncer.go

[VC] fix: respect vc status when reconciling

---

incubator/hnc/api/v1alpha1/hierarchy_types.go
incubator/hnc/internal/reconcilers/hierarchy_config.go

Tested by make test and verified the updated finalizer name in GKE
cluster.
Part of #667

Update HC finalizer from hasOwnedNamespace to hasSubnamespace

---

incubator/virtualcluster/pkg/syncer/metrics/metrics.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/checker.go

[VC] fix: register UWSOperationCounter

---

incubator/hnc/README.md
incubator/hnc/docs/releasing.md

Move the release instructions from the README to their own doc. Expand
with the latest on branching and doc updates.
cc @adrianchung @rjbez17 @GinnyJI

Update release instructions

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/README.md
incubator/hnc/docs/user-guide/how-to.md

Also update some minor out-of-date information in the README.
This is a cherry pick of #848 onto the v0.5 branch

Update docs to refer to HNC v0.5

---

tenant/pkg/controller/tenant/tenant_controller.go
tenant/pkg/controller/tenantnamespace/tenantnamespace_controller.go

Fix compilation error with latest k8s API

---

incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml

Pick up a small change to the CRD documentation.

Regenerate manifest files

---

benchmarks/kubectl-mtb/go.mod
benchmarks/kubectl-mtb/go.sum
benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
benchmarks/kubectl-mtb/internal/reporter/reporter.go
benchmarks/kubectl-mtb/internal/reporter/types.go

[MTB] added policy reporter

---

incubator/hnc/e2e/tests/delete_crd_test.go
incubator/hnc/e2e/tests/e2e_test.go

convert hack/test-delete-anchor-crd.sh to
e2e/tests/delete-anchor-crd_test.go

convert test-delete-anchor-crd to go test file

---

incubator/hnc/e2e/tests/delete_crd_test.go
incubator/hnc/e2e/tests/e2e_test.go
incubator/hnc/e2e/tests/namespace_test.go
incubator/hnc/e2e/tests/subnamespace_test.go

Use function mustRun(), mustNotRun() for running command and logging
output. Use function cleanUpNses() to clean up the namespaces after each
test.

Refactor e2e test

---

incubator/virtualcluster/pkg/syncer/errors/errors.go
incubator/virtualcluster/pkg/syncer/errors/errors_test.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/resources/event/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
incubator/virtualcluster/pkg/syncer/resources/service/uws.go
incubator/virtualcluster/pkg/syncer/syncer.go
incubator/virtualcluster/pkg/syncer/uwcontroller/uwcontroller.go

- fix: enqueue error status vc
- drop uws request if cluster is not found

[VC] syncer: drop uws request if cluster is not found

---

incubator/hnc/e2e/tests/delete_crd_test.go
incubator/hnc/e2e/tests/e2e_test.go

Convert test-delete-hc-and-anchor-crd-test.sh to delete_crd_test.go. Add
helper function runCommand() to return the stdout and err from running
the input command.

Add delete-hc-and-anchor-crd test

---

incubator/hnc/e2e/tests/delete_crd_test.go
incubator/hnc/e2e/tests/e2e_test.go
incubator/hnc/e2e/tests/issues_test.go

Add issue_test.go that test github issue #328. Add helper function
runShouldContain() to run the command and check if the output contains
the give slice of strings.

Add e2e test for issue 328

---

benchmarks/kubectl-mtb/go.mod
benchmarks/kubectl-mtb/go.sum
benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite.go
benchmarks/kubectl-mtb/pkg/benchmark_suite/benchmarks_suite_test.go

[MTB] Sort benchmarks according to profile level, category and id respectively

---

benchmarks/kubectl-mtb/Makefile
benchmarks/kubectl-mtb/internal/mtb_builder/tpl.go
benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers_test.go
benchmarks/kubectl-mtb/test/utils/unittestutils/cluster.go
benchmarks/kubectl-mtb/test/utils/unittestutils/tenants_test_util.go

Benchmarks can now run on a single cluster. 

[MTB]Changed unit test setup

---

benchmarks/kubectl-mtb/go.mod
benchmarks/kubectl-mtb/go.sum
benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go
benchmarks/kubectl-mtb/internal/reporter/reporter.go
benchmarks/kubectl-mtb/internal/reporter/types.go

/assign @JimBugwadia 
Sample Output :

[MTB]Added table to display benchmark summary

---

benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
benchmarks/kubectl-mtb/test/utils/apiutils.go

[MTB]Added check for tenant-admin and tenant namespace

---

incubator/hnc/e2e/tests/e2e_test.go
incubator/hnc/e2e/tests/issues_test.go

Translate test-issue-501 to issue_test.go. Add helper function
runShouldNorContainMultiple().

Add e2e test for issue 501

---

incubator/hnc/e2e/tests/issues_test.go

hierachy changes
Convert test for issue #605 to issue_test.go

Add e2e test for clearing CannotUpdate conditions in descendants when a

---

incubator/virtualcluster/Makefile

[VC] exclude e2e test from default test

---

benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go
benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies_test.go

[MTB] added network policy test

---

benchmarks/kubectl-mtb/go.sum
benchmarks/kubectl-mtb/internal/kubectl-mtb/test.go
benchmarks/kubectl-mtb/internal/reporter/default_reporter.go
benchmarks/kubectl-mtb/internal/reporter/policy_reporter.go

[MTB] Added minor tweaks and skip flag

---

benchmarks/kubectl-mtb/internal/kubectl-mtb/get.go
benchmarks/kubectl-mtb/internal/kubectl-mtb/root.go
benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go
benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml

[MTB] Bugs removal and ux enhancement

---

benchmarks/kubectl-mtb/internal/kubectl-mtb/run.go

[MTB] changed validation check for tenantnamespaces

---

incubator/hnc/Makefile
incubator/hnc/docs/releasing.md

Add e2e tests to release instructions

---

incubator/hnc/pkg/testutils.go
incubator/hnc/test/e2e/delete_crd_test.go
incubator/hnc/test/e2e/e2e_test.go
incubator/hnc/test/e2e/issues_test.go
incubator/hnc/test/e2e/namespace_test.go
incubator/hnc/test/e2e/subnamespace_test.go

Refactor e2e test related helper functions into pkg/testutils.go

Add testutils package

---

incubator/hnc/test/e2e/demo_test.go

Add e2e test for 'Basic functionality' part in demo

---

incubator/hnc/test/e2e/demo_test.go

Add e2e test for 'Propagating different types' in demo

---

incubator/hnc/test/e2e/demo_test.go

Add e2e test for subnamespaces in hnc demo

---

incubator/hnc/pkg/testutils/testutils.go
incubator/hnc/test/e2e/delete_crd_test.go
incubator/hnc/test/e2e/demo_test.go
incubator/hnc/test/e2e/issues_test.go
incubator/hnc/test/e2e/namespace_test.go
incubator/hnc/test/e2e/subnamespace_test.go

Run gofmt on all tests

---

incubator/hnc/pkg/testutils/testutils.go
incubator/hnc/test/e2e/demo_test.go

E2e test for hierarchical network policy

---

incubator/virtualcluster/config/setup/all_in_one.yaml

support legacy csr api, before signerName is added

[VC] Improvement: support legacy signer kubernetes.io/legacy-unknown

---

incubator/hnc/test/e2e/demo_test.go

Forgot to remove the focused test from last PR

Remove the focused test

---

incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go

webhook code was omitted when bumping kubernetes dependency to 1.18.  This change fixes it. 
Btw, the vn-agent UT breaks which I believe is because of bumping the version. This should be fixed later.

[VC] Fix 1.18 dependency for vc webhook

---

incubator/virtualcluster/pkg/vn-agent/server/server_test.go

The vn-agent UT breaks after switching to 1.18 dependency. This change fixes the UTs.
Basically, the vn-agent UT follows the upstream Kubelet server UT framework. In 1.18, all the streaming requests that are forwarded to the streaming server need to have "X-Stream-Protocol-Version" field in the http header. This changes follows the modification in the upstream Kubelet UT. 
Also, the "stdout stderr and tty" test is removed from the upstream. I have tried it and found it will cause UT timeout (I have not dig into it).

[VC] Fix vn-agent UT for Kubernetes 1.18 dependency

---

incubator/hnc/third_party/open-policy-agent/gatekeeper/pkg/webhook/certs.go

Update the iteration to make sure no early return before attempting to
inject certs to all webhooks. This is to address comment in
https://github.com/open-policy-agent/cert-controller/pull/7/commits/1a1e6f93f227bffb771588dd7cf9eb255336200d#r463349960
Tested manually by deploying v0.5 and config/sample/v1alpha1_anchor.yaml
first and then deploying the change. Worked as expected.

Try injecting certs to all webhooks before early exit

---

incubator/hnc/internal/reconcilers/hnc_config_test.go

From the fail logs on issue #871, the flaky tests all happen after a
HNCConfigue update, but the supposed follwing updates could not be
detected. We give these lines more time in Eventually() so that
HNCConfigue update gets more time to propogate. However, I was not able
to reproduce the flaky test results when running locally, so I cannot
confirm that they are fully fixed by this pr.

Fix flaky test

---

incubator/virtualcluster/cmd/vcctl/subcmd/create.go

Reopening this pull requests now that my CLA and identity stuff should be figured out :)

update kubeconfig generation to use ClientConfig

---

incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/pkg/syncer/apis/config/types.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go
incubator/virtualcluster/pkg/syncer/resources/register.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go

Add priority class syncer (priority class is an extra resource, needs to be activated using --extra-syncing-resources flag)
https://github.com/kubernetes-sigs/multi-tenancy/issues/1007

 Add priority class syncer 

---

incubator/hnc/README.md

Seem reasonable? It started to seem weird that my name was the only one there now that we're getting traffic.

Add contributor list

---

incubator/hnc/internal/kubectl/tree.go

Tested: manually. The output looks like this:
```
#setup
$ k create ns root
namespace/root created
$ k create ns nonsub
namespace/nonsub created
$ k hns set nonsub --parent root
Setting the parent of nonsub to root
Succesfully updated 1 property of the hierarchical configuration of nonsub
$ k hns create child -n root
Successfully created "child" subnamespace anchor in "root" namespace
#result
$ k hns tree root
root
├── [s] child
└── nonsub
[s] indicates subnamespaces.
```
Fix #844

Add annotation for subnamespace when print tree

---

benchmarks/kubectl-mtb/README.md
benchmarks/kubectl-mtb/test/quotas/ns_quota.yaml

[MTB] Updated Docs

---

incubator/virtualcluster/cmd/manager/main.go
incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/config/setup/all_in_one_aliyun.yaml
incubator/virtualcluster/pkg/controller/util/logr/util.go
incubator/virtualcluster/pkg/controller/virtualcluster/virtualcluster_controller.go

Allow user to disable the stacktrace and caller fields of the logger

[VC] Feature: disable the logger caller and stacktrace field

---

incubator/hnc/cloudbuild.yaml

Cherrypick of #1032. Will ask @tcnksm to test when I create HNC v0.5.2-rc1 as I don't have a Mac, and also because testing changes to the build process on v0.5 is very difficult (it's easier on `master` right now).
Fixes #1029

Add support for plugin build for darwin amd64

---

incubator/virtualcluster/cmd/manager/main.go
incubator/virtualcluster/config/setup/all_in_one.yaml
incubator/virtualcluster/pkg/webhook/virtualcluster/virtualcluster_webhook.go

1. add command line option (`--enable-webhook`) that allows user to turn on/off webhook 
2. add detailed error messages

[VC] Features: add webhook cmd option, add detailed error messages

---

benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources.go
benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/README.md

[MTB] resolved namespace bug

---

incubator/hnc/docs/user-guide/how-to.md

[This](https://github.com/kubernetes-sigs/multi-tenancy/pull/1032) changes the plugin installation URL so update the user guide to support it.

Update guide to choose OS for the plugin

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/how-to.md

Update 0.5 docs to 0.5.2

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/how-to.md

Update master docs to 0.5.2

---

benchmarks/kubectl-mtb/.gitignore
benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/block_add_capabilities.go
benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/block_privilege_escalation.go
benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/block_privileged_containers.go
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_bind_mounts/block_use_of_bind_mounts.go
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/block_use_of_host_ipc.go
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/block_use_of_host_networking_and_ports.go
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/block_use_of_host_pid.go
benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml
benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go

Corrected policy file

---

benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies.go

Network policy bug fix

---

incubator/virtualcluster/README.md

This change revises the README page to include the kubecon talk.

[VC] Add kubecon talk to README.md

---

incubator/virtualcluster/README.md

Fix the broken link for CRD VirtualCluster in README.md

fix broken link for VirtualCluster

---

incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws_test.go

Mutates synced pods with:
```
KUBERNETES_SERVICE_HOST=kubernetes
```

Add KUBERNETES_SERVICE_HOST env variable to synced pods

---

incubator/hnc/cmd/manager/main.go

According to
https://github.com/kubernetes-sigs/controller-runtime/issues/1148,
there's a race condition between manager start and webhook register.
This commit moved webhook setup before manager start.
Tested on GKE cluster. The nil pointer error was not detected for 20
times.

Move webhook setup before manager start

---

incubator/hnc/README.md
incubator/hnc/devenv

Update dev instructions

---

benchmarks/kubectl-mtb/Makefile

[MTB] Added releases

---

benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/block_access_to_cluster_resources_test.go
benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/block_ns_quota_test.go
benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/create_network_policies_test.go
benchmarks/kubectl-mtb/test/utils/unittestutils/client.go
benchmarks/kubectl-mtb/test/utils/unittestutils/rbac_create.go

[MTB] added 3 unit tests

---

incubator/hnc/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml
incubator/hnc/config/crd/bases/hnc.x-k8s.io_hncconfigurations.yaml
incubator/hnc/config/crd/bases/hnc.x-k8s.io_subnamespaceanchors.yaml

Just ran `make manifests` but nothing else.
Tested: installed HNC

Regenerate CRD yamls

---

incubator/hnc/pkg/testutils/testutils.go
incubator/hnc/test/e2e/demo_test.go
incubator/hnc/test/e2e/issues_test.go

Update the output format; change the wait time; add verification to make
sure the ns anchor is created; add verification in RecoverHNC().

Fix some e2e tests

---

incubator/hnc/Makefile
incubator/hnc/hack/ci-test.sh

Closes #1129 
Open to discuss the solution :)

Add gofmt enforcement

---

incubator/hnc/internal/reconcilers/object_test.go
incubator/hnc/internal/reconcilers/test_helpers_test.go

Update and add test case for exception

---

benchmarks/README.md
benchmarks/kubectl-mtb/docs/main.go
benchmarks/kubectl-mtb/test/benchmarks/block_access_to_cluster_resources/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_add_capabilities/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_multitenant_resources/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_ns_quota/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_privilege_escalation/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_privileged_containers/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_ipc/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_networking_and_ports/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_path/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_host_pid/README.md
benchmarks/kubectl-mtb/test/benchmarks/block_use_of_nodeport_services/README.md
benchmarks/kubectl-mtb/test/benchmarks/configure_ns_object_quota/README.md
benchmarks/kubectl-mtb/test/benchmarks/configure_ns_quotas/README.md
benchmarks/kubectl-mtb/test/benchmarks/create_network_policies/README.md
benchmarks/kubectl-mtb/test/benchmarks/create_role_bindings/README.md
benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/README.md
benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/config.yaml
benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image.go
benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image_test.go
benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml

Fixes #1108:
- added policy
- skip generating sub-titles in README if not defined

[MTB] Add Kyverno policy - Require always image pull

---

incubator/hnc/test/e2e/demo_test.go

Change from --allowCascadingDelete to --allowCascadingDeletion
Tested: test now passes

Unbreak demo e2e test

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/how-to.md

Update all references to v0.5.3 and document the user-facing changes.

Update docs for v0.5.3

---

incubator/hnc/internal/reconcilers/hierarchy_config.go

While looking into a sporadic but reproducible (maybe 1/5 times) failure
of the rolebinding recreation test, I observed that the objects in the
`parent` namespace were occasionally not being reconciled after HNC
restarted. This appeared to be because the HC reconciler was not
modifying either the HC or the namespace, and so was skipping the update
of the object reconcilers. This resulted in source objects not being
inserted into the forest, and as a result, propagated objects were being
removed.
By adding a check that the object reconcilers are called when a
namespace is first added to the forest, we can be certain that all
objects are present in the forest.
Tested: ran the rolebinding e2e test 10/10 times successfully.

Ensure all objects are reconciled at least once

---

incubator/hnc/pkg/testutils/testutils.go
incubator/hnc/test/e2e/rolebinding_test.go

Made several debuggability and functional improvements:
* Added timestamps to all output to correlate with logs. Timestamps are
of the form "seconds since Unix epoch" which isn't human friendly but
is identical to the timestamps produced by HNC logs.
* Fully deleted the HNC deployment in RecoverHNC since HNC doesn't
really seem to recover well if various things are changed without
restarting the pod.
* Make the post-recovery test far more robust by not ignoring failures
to delete the test namespaces.
* Stop force-deleting pods in the rolebinding test and instead just wait
a few moments. I found that we don't actually need to wait for the pod
object to be fully deleted on the server for it to stop getting in the
way; the container in the pod appears to stop running ~instantly while
the pod …

Make e2e test repairs more robust

---

incubator/hnc/api/v1alpha2/hierarchy_types.go
incubator/hnc/internal/forest/namespace.go
incubator/hnc/internal/reconcilers/hierarchy_config.go
incubator/hnc/internal/reconcilers/object.go
incubator/hnc/internal/reconcilers/object_test.go

Implement selector feature using 'select' annotation

---

incubator/virtualcluster/pkg/syncer/fairqueue/fair.go
incubator/virtualcluster/pkg/syncer/fairqueue/fair_test.go
incubator/virtualcluster/pkg/syncer/fairqueue/fifo.go
incubator/virtualcluster/pkg/syncer/fairqueue/option.go
incubator/virtualcluster/pkg/syncer/mccontroller/mccontroller.go

1. implement idle queue gc in fairqueue
2. fix: close channel when shutdown fairqueue
3. switch from workqueue to fairqueue

VC: do idle queue gc in fair queue

---

incubator/hnc/internal/kubectl/describe.go

If there's no event, it will show `No recent HNC events for objects in this namespace`.
Tested:

Add events to `kubectl hns describe`

---

benchmarks/README.md
benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/README.md
benchmarks/kubectl-mtb/test/benchmarks/require_run_as_non_root_user/config.yaml
benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml

[MTB] update kyverno policy - disallow root user

---

incubator/hnc/internal/validators/object_test.go

Tested: go test ./internal/validators

Add test for invalid selector

---

incubator/hnc/docs/user-guide/README.md
incubator/hnc/docs/user-guide/faq.md

These didn't seem to fit well in "concepts," "how-to" or "best
practices" so I put them into a catch-all topic.
Testing: staged at
https://github.com/adrianludwin/multi-tenancy/tree/docs/incubator/hnc/docs/user-guide
Fixes #973, fixes #1006

Add an FAQ with requirements and scaling info

---

incubator/hnc/docs/user-guide/concepts.md
incubator/hnc/docs/user-guide/how-to.md

Update the docs for the latest in condition schemas; make some slight
tweaks to the resource config section and explain how to bypass the
overwrite protection.
Tested: staged at
https://github.com/adrianludwin/multi-tenancy/tree/doc-updates/incubator/hnc/docs/user-guide.
Fixes #1172, fixes #1181

HNC v0.6 docs: conditions and configuration

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/how-to.md

This is the cherrypick to th v0.6 branch.

Update latest version to v0.6.0 (cherrypick)

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/how-to.md

Update latest version to v0.6.0

---

incubator/hnc/internal/validators/object.go
incubator/hnc/internal/validators/object_test.go

Check if more than one selector is created

---

incubator/virtualcluster/pkg/syncer/resources/node/uws.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
incubator/virtualcluster/pkg/syncer/vnode/native/provider.go
incubator/virtualcluster/pkg/syncer/vnode/vnode.go

vnode provider enable developer to customize
the vnode object. eg. capability, address

VC: introduce vnode provider

---

incubator/virtualcluster/pkg/syncer/fairqueue/fair.go

VC: fix: don't call next twice in a loop

---

benchmarks/kubectl-mtb/test/policies/kyverno/all_policies.yaml

fixes: https://github.com/kubernetes-sigs/multi-tenancy/issues/1109

MTB: added pv reclaim kyverno policy

---

incubator/virtualcluster/Makefile

This change fixes the Makefile error in running the UTs.

[VC] Fix makefile error

---

incubator/hnc/docs/user-guide/concepts.md

Published at https://github.com/adrianludwin/multi-tenancy/blob/doc-annot/incubator/hnc/docs/user-guide/concepts.md#admin-labels.
Fixes #1301

Document HNC labels and annotations

---

incubator/virtualcluster/README.md

Based on the discussions in CAPN meeting and the feedbacks from community users, the README.md is revised to add more detailed explanations about VC project.

[VC] Revise README.md

---

incubator/hnc/docs/user-guide/concepts.md
incubator/hnc/docs/user-guide/how-to.md
incubator/hnc/docs/user-guide/quickstart.md

preview: https://github.com/GinnyJI/multi-tenancy/tree/userguide/incubator/hnc/docs/user-guide

Add user documentation for exceptions

---

benchmarks/kubectl-mtb/test/benchmarks/require_always_pull_image/require_always_pull_image.go
benchmarks/kubectl-mtb/test/utils/resources/pod/pod.go

[MTB] Added image pull policy benchmark

---

incubator/hnc/hack/krew-kubectl-hns.yaml

Update the docs that refer to HNC v0.5.

Update Krew docs for HNC v0.7

---

incubator/hnc/README.md
incubator/hnc/docs/user-guide/README.md
incubator/hnc/docs/user-guide/concepts.md
incubator/hnc/docs/user-guide/how-to.md
incubator/hnc/docs/user-guide/quickstart.md

Staged at:
* [README](https://github.com/adrianludwin/multi-tenancy/blob/docs/incubator/hnc/README.md)
* [User guide](https://github.com/adrianludwin/multi-tenancy/tree/docs/incubator/hnc/docs/user-guide)
/cc @rjbez17

Update docs for v0.7

---

incubator/hnc/docs/user-guide/how-to.md

preview at https://github.com/GinnyJI/multi-tenancy/blob/06doc/incubator/hnc/docs/user-guide/how-to.md

Update how-to to use v1alpha2

---

incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/uws.go
incubator/virtualcluster/pkg/syncer/vnode/vnode.go

usecase: vk node may change its address

VC: syncer: update node address upward to tenant

---

incubator/virtualcluster/pkg/syncer/conversion/helper.go
incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
incubator/virtualcluster/pkg/syncer/resources/service/dws.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/dws.go

for webhook convenience to find the vc cr

VC: add vc ns to each object

---

incubator/virtualcluster/pkg/util/cluster/cluster.go

The Cache Option has a field name of "Namespace" which is conflict with the Cluster "Namespace" field. Hence the VC namespace name is mistakenly used in the cache watch option. This change fixes the bug.

[VC] Fix a field name conflict in Cluster

---

incubator/virtualcluster/cmd/syncer/app/server.go
incubator/virtualcluster/cmd/vn-agent/app/server.go
incubator/virtualcluster/pkg/syncer/conversion/equality.go
incubator/virtualcluster/pkg/syncer/conversion/equality_test.go
incubator/virtualcluster/pkg/syncer/conversion/mutate.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/configmap/dws.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/dws.go
incubator/virtualcluster/pkg/syncer/resources/ingress/checker.go
incubator/virtualcluster/pkg/syncer/resources/ingress/dws.go
incubator/virtualcluster/pkg/syncer/resources/ingress/uws.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/dws.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/dws.go
incubator/virtualcluster/pkg/syncer/resources/pod/uws.go
incubator/virtualcluster/pkg/syncer/resources/secret/checker.go
incubator/virtualcluster/pkg/syncer/resources/secret/dws.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/service/dws.go
incubator/virtualcluster/pkg/syncer/resources/service/uws.go
incubator/virtualcluster/pkg/syncer/util/helper.go
incubator/virtualcluster/pkg/util/flag/flags.go

[VC] refactor: get whole vc object instead of spec only

---

incubator/hnc/internal/validators/hierarchy.go
incubator/hnc/internal/validators/hncconfig.go

fixes #1218
tests:
make test
make kind-deploy

HNC produces double colons on error message

---

incubator/virtualcluster/pkg/syncer/manager/manager.go
incubator/virtualcluster/pkg/syncer/resources/configmap/controller.go
incubator/virtualcluster/pkg/syncer/resources/endpoints/controller.go
incubator/virtualcluster/pkg/syncer/resources/event/controller.go
incubator/virtualcluster/pkg/syncer/resources/ingress/controller.go
incubator/virtualcluster/pkg/syncer/resources/namespace/controller.go
incubator/virtualcluster/pkg/syncer/resources/node/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/controller.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/controller.go
incubator/virtualcluster/pkg/syncer/resources/pod/controller.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/controller.go
incubator/virtualcluster/pkg/syncer/resources/secret/controller.go
incubator/virtualcluster/pkg/syncer/resources/service/controller.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/controller.go
incubator/virtualcluster/pkg/syncer/resources/storageclass/controller.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
incubator/virtualcluster/pkg/syncer/util/test/runPatrol.go
incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
incubator/virtualcluster/pkg/util/listener/adapter.go
incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go

VC: mccontroller: add listener adapter

---

incubator/hnc/pkg/testutils/testutils.go

Fixes #1354 
Signed-off-by: sheetalsingala <ssingala@redhat.com>

HNC: Add MustNotApplyYAML() func to testutils package

---

incubator/hnc/internal/forest/namespacestructure_test.go
incubator/hnc/internal/object/object_test.go
incubator/hnc/internal/validators/anchor_test.go
incubator/hnc/internal/validators/hierarchy_test.go
incubator/hnc/internal/validators/hncconfig_test.go
incubator/hnc/internal/validators/namespace_test.go
incubator/hnc/internal/validators/object_test.go
incubator/hnc/test/e2e/quickstart_test.go

Replace  'NewGomegaWithT' in favor of  'NewWithT' + fix some typo 
tested:
make test

Replace deprecated 'NewGomegaWithT' with 'NewWithT'

---

incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go

[VC] fix minor bug in cluster cache copy

---

incubator/virtualcluster/config/crds/cluster.x-k8s.io_clusters.yaml

[VC] Adding capi generated type

---

incubator/virtualcluster/pkg/syncer/patrol/differ/handler.go
incubator/virtualcluster/pkg/syncer/resources/configmap/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker.go
incubator/virtualcluster/pkg/syncer/resources/namespace/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/namespace/dws_test.go
incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go
incubator/virtualcluster/pkg/syncer/util/helper.go
incubator/virtualcluster/pkg/syncer/util/test/featuregate.go
incubator/virtualcluster/pkg/syncer/util/test/runDWS.go
incubator/virtualcluster/pkg/syncer/util/test/runUWS.go
incubator/virtualcluster/pkg/util/mccontroller/mccontroller.go

VC: selective consistency ns checks 

---

incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/cluster_test.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/namespace_test.go
incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go
incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go

cleanup: more test and comments
fix minor language trick

[VC] cleanup: add cache test

---

incubator/virtualcluster/pkg/syncer/resources/endpoints/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/persistentvolumeclaim/checker.go

[VC] refactor ep, pv, pvc checker by differ

---

incubator/virtualcluster/pkg/syncer/resources/persistentvolume/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker.go
incubator/virtualcluster/pkg/syncer/resources/pod/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/service/checker.go
incubator/virtualcluster/pkg/syncer/resources/serviceaccount/checker.go

[VC] refactor pod, service, serviceaccount checker by differ

---

incubator/virtualcluster/experiment/pkg/scheduler/algorithm/namespacesched.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot.go
incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go

This change adds a simple namespace scheduling algorithm and adds the missing parts in the end-to-end workflow.

[VC] Add simple first fit namespace scheduling algorithm

---

incubator/virtualcluster/README.md
incubator/virtualcluster/experiment/README.md

The change adds basic readme information for the namespace scheduler feature.

[VC] Add README.md for the experiment feature

---

incubator/virtualcluster/experiment/cmd/scheduler/virtualclusterresource.go
incubator/virtualcluster/experiment/pkg/scheduler/algorithm/namespacesched.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/cache.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/interface.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/pod.go
incubator/virtualcluster/experiment/pkg/scheduler/cache/snapshot.go
incubator/virtualcluster/experiment/pkg/scheduler/engine/schedulerengine.go
incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/pod/controller.go
incubator/virtualcluster/experiment/pkg/scheduler/util/helper.go

[VC] support pod scheduling

---

incubator/virtualcluster/pkg/syncer/resources/node/uws.go

[VC] update vnode daemon port during heartbeats

---

incubator/virtualcluster/pkg/syncer/util/featuregate/gate.go

I noticed as I was about to add a new feature gate that this comment was cut off.

[VC] Finishing superclusterpooling feature gate comment

---

incubator/virtualcluster/pkg/syncer/conversion/equality.go

This PR gives an example of custom resource syncer. The proposed design is at: https://github.com/kubernetes-sigs/multi-tenancy/issues/1388 (will generate a readme later)

Export checkDWObjectMetaEquality for custom resource syncer (Add an example custom resource syncer)

---

incubator/hnc/internal/reconcilers/object.go

In #1091, we update HNC to delete and recreate any object that it can't update. However, if another object has an ownerReference pointing to the object we're deleting, it could be deleted as well, which isn't desirable. So we're restricting the recreate-on-failed-update logic to RBs only.
Tested: passed e2e:rolebinding_test.go
Fix: #1254

Restrict recreate-on-failed-update semantics to Rolebindings

---

OWNERS

This should allow me (yiqigao217) to approve PRs.

Update OWNERS to include yiqigao217

---

incubator/hnc/docs/user-guide/quickstart.md
incubator/hnc/test/e2e/quickstart_test.go

Fix several commands in quick-start.
Fix #1324

Add e2e test for quickstart exceptions

---

incubator/virtualcluster/pkg/vn-agent/server/translate.go

Add support for all kubectl logs options

[VC] add support for all kubectl logs options

---

incubator/virtualcluster/cmd/syncer/app/config/config.go
incubator/virtualcluster/cmd/syncer/app/options/options.go
incubator/virtualcluster/cmd/syncer/app/server.go
incubator/virtualcluster/pkg/syncer/apis/config/types.go
incubator/virtualcluster/pkg/syncer/syncer.go

it allows vc-syncer deploy on external cluster

[VC] syncer: introduce meta cluster

---

incubator/virtualcluster/doc/clusterpooling-demo.md
incubator/virtualcluster/experiment/config/setup/all_in_one.yaml
incubator/virtualcluster/experiment/config/setup/cluster-id.yaml.sed
incubator/virtualcluster/experiment/config/setup/create-cluster-minikube.sh
incubator/virtualcluster/experiment/config/setup/deploy-cluster-id.sh
incubator/virtualcluster/experiment/config/setup/deploy-syncer.sh
incubator/virtualcluster/experiment/config/setup/syncer.yaml.sed

add some script to deploy components

[VC] docs: add clusterpooling demo instruction

---

incubator/virtualcluster/pkg/syncer/resources/crd/checker.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker.go

do not remove/update unlabled (PublicObjectKey!=true) resources in virtual cluster
/assign @christopherhein @Fei-Guo

Do not remove/update un-Labled resources in virtual cluster

---

incubator/virtualcluster/pkg/syncer/resources/priorityclass/checker_test.go
incubator/virtualcluster/pkg/syncer/resources/priorityclass/uws_test.go

1) add non-public tenant priority class test cases
2) correct old test case with public/non public labels

add non-public tenant priorityclass testcases 

---

incubator/virtualcluster/experiment/pkg/scheduler/resource/virtualcluster/namespace/controller.go

If the namespace quota is deleted, the existing namespace placement result should be removed from namespace annoation. This change fixes this problem.

[VC] Remove namespace placement result when quota is deleted
